package com.aiinterviewcoach.domain.platform;

/**
 * 稳定的领域拒绝类别。适配层可将其映射为协议错误码，但不得把基础设施异常伪装成领域拒绝。
 */
public enum DomainErrorCode {
    INVALID_ARGUMENT,
    INVALID_STATE,
    VERSION_CONFLICT,
    TENANT_MISMATCH,
    OWNERSHIP_DENIED,
    RESOURCE_NOT_ACTIVE,
    ACCOUNT_NOT_ACTIVE,
    MEMBERSHIP_NOT_ACTIVE,
    CONSENT_REQUIRED,
    QUESTION_NOT_PUBLISHABLE,
    CONTENT_SOURCE_REQUIRED,
    RUBRIC_REQUIRED,
    ANSWER_REQUIRED,
    ANSWER_ALREADY_SUBMITTED,
    ANSWER_ALREADY_CONFIRMED,
    ENTITLEMENT_NOT_ACTIVE,
    ENTITLEMENT_EXPIRED,
    USAGE_EXCEEDED,
    RESERVATION_EXPIRED,
    RESERVATION_ALREADY_FINALIZED,
    PLAN_NOT_CONFIRMED,
    PLAN_EXPIRED,
    SESSION_ALREADY_ACTIVE,
    STALE_TURN,
    JOB_LEASE_NOT_HELD,
    JOB_NOT_CANCELLABLE,
    IDEMPOTENCY_CONFLICT,
    IDEMPOTENCY_IN_PROGRESS,
    RETRY_NOT_ALLOWED,
    POLICY_DENIED
}
