package com.ruoyi.aps.application.foundation;

/**
 * APS 稳定错误码的最小公共集合。
 */
public enum ApsErrorCode
{
    INVALID_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    IDEMPOTENCY_CONFLICT,
    STALE_VERSION,
    INVALID_EXECUTION_TRANSITION,
    EXECUTION_CONFLICT,
    QUANTITY_BALANCE_VIOLATION,
    INSUFFICIENT_QUANTITY,
    QUALITY_DISPOSITION_REQUIRED,
    EXECUTION_INPUT_STALE,
    UNSUPPORTED_SYNC_RULE,
    PERSISTENCE_UNAVAILABLE,
    INTERNAL_ERROR
}
