-- 生产排程业务雏形数据库基线草案（29 表）
-- 编号：DDL-APS-MYSQL-001；版本：3.1.0；状态：Review-only / Not executed
-- 对应设计：数据库设计.md（29 张实施规划基线候选表）
-- 目标方言：MySQL 8.0.16+ / InnoDB / utf8mb4
-- 使用边界：仅用于独立空库评审；不是 Flyway migration，未在真实 MySQL 执行。
-- 已确认：单站点部署，不建 aps_factory，所有表均不含 factory_id。
-- 已确认：技能只保留 aps_resource_skill 一张表；工艺需求直接保存技能编码和最低等级。
-- 首版范围：具名人机有限排程、共享加工批、阶段分段、版本发布、现场反馈和数量守恒。
-- 明确延期：跨工厂、单位换算、多供给自动匹配、通用领域事件、ERP/MES Inbox/Outbox。
-- 同步边界：M12/M17 可保存 SAME_START 来源关系，但 P0 数据就绪与发布必须以 UNSUPPORTED_SYNC_RULE 阻断，禁止执行或降级。
-- 时间约定：业务时间统一保存 UTC DATETIME(3)，展示时区由应用参数 aps.timezone 提供。
-- 标识约定：业务主键为应用生成 UUID；RuoYi 用户只保存逻辑标识，不建立跨模块外键。
-- 安全约定：本文件不含 CREATE/DROP DATABASE、DROP/TRUNCATE/DELETE、seed 或关闭外键检查。

-- ============================================================================
-- A. 组织、人员和资源（M01-M05）
-- ============================================================================

CREATE TABLE aps_workshop (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    workshop_code VARCHAR(64) NOT NULL,
    workshop_name VARCHAR(128) NOT NULL,
    manager_user_id VARCHAR(64) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    remark VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_workshop PRIMARY KEY (id),
    CONSTRAINT uk_workshop_code UNIQUE (workshop_code),
    CONSTRAINT ck_workshop_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M01 车间；单站点下的组织根节点';

CREATE TABLE aps_work_center (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    workshop_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    center_code VARCHAR(64) NOT NULL,
    center_name VARCHAR(128) NOT NULL,
    center_type VARCHAR(16) NOT NULL DEFAULT 'MIXED',
    concurrent_capacity DECIMAL(18,6) NOT NULL DEFAULT 1,
    capacity_uom_code VARCHAR(16) NOT NULL DEFAULT 'COUNT',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    remark VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_work_center PRIMARY KEY (id),
    CONSTRAINT uk_work_center_code UNIQUE (center_code),
    CONSTRAINT uk_work_center_scope UNIQUE (id, workshop_id),
    CONSTRAINT fk_work_center_workshop FOREIGN KEY (workshop_id) REFERENCES aps_workshop (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_work_center_type CHECK (center_type IN ('MACHINE', 'LABOR', 'MIXED', 'BATCH')),
    CONSTRAINT ck_work_center_capacity CHECK (concurrent_capacity > 0),
    CONSTRAINT ck_work_center_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    KEY idx_work_center_workshop (workshop_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M02 工作中心；候选产能组，不重复扣减资源容量';

CREATE TABLE aps_resource (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    workshop_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    work_center_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    resource_code VARCHAR(64) NOT NULL,
    resource_name VARCHAR(128) NOT NULL,
    resource_type VARCHAR(20) NOT NULL,
    ruoyi_user_id VARCHAR(64) NULL,
    team_name VARCHAR(128) NULL,
    capacity_value DECIMAL(18,6) NOT NULL DEFAULT 1,
    capacity_uom_code VARCHAR(16) NOT NULL DEFAULT 'COUNT',
    capability_json JSON NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    remark VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_resource PRIMARY KEY (id),
    CONSTRAINT uk_resource_code UNIQUE (resource_code),
    CONSTRAINT uk_resource_type UNIQUE (id, resource_type),
    CONSTRAINT uk_resource_center_type UNIQUE (id, resource_type, work_center_id),
    CONSTRAINT fk_resource_workshop FOREIGN KEY (workshop_id) REFERENCES aps_workshop (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_resource_center_scope FOREIGN KEY (work_center_id, workshop_id) REFERENCES aps_work_center (id, workshop_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_resource_type CHECK (resource_type IN ('PERSON', 'MACHINE', 'WORKSTATION', 'TOOL')),
    CONSTRAINT ck_resource_capacity CHECK (capacity_value > 0),
    CONSTRAINT ck_resource_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')),
    KEY idx_resource_workshop (workshop_id, resource_type, status),
    KEY idx_resource_center (work_center_id, workshop_id, resource_type, status),
    KEY idx_resource_ruoyi_user (ruoyi_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M03 具名人员、设备、工位和工装统一资源';

CREATE TABLE aps_resource_skill (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    resource_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    skill_code VARCHAR(64) NOT NULL,
    skill_name VARCHAR(128) NOT NULL,
    skill_level SMALLINT UNSIGNED NOT NULL,
    valid_from DATETIME(3) NULL,
    valid_to DATETIME(3) NULL,
    certificate_ref VARCHAR(128) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_resource_skill PRIMARY KEY (id),
    CONSTRAINT uk_resource_skill UNIQUE (resource_id, skill_code),
    CONSTRAINT fk_resource_skill_resource FOREIGN KEY (resource_id) REFERENCES aps_resource (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_resource_skill_level CHECK (skill_level BETWEEN 1 AND 10),
    CONSTRAINT ck_resource_skill_window CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from),
    CONSTRAINT ck_resource_skill_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'EXPIRED')),
    KEY idx_resource_skill_lookup (skill_code, skill_level, status),
    KEY idx_resource_skill_resource (resource_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M04 唯一技能表；一名资源可按多行拥有多项技能';

CREATE TABLE aps_resource_availability (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    resource_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    window_type VARCHAR(20) NOT NULL,
    start_at DATETIME(3) NOT NULL,
    end_at DATETIME(3) NOT NULL,
    capacity_ratio DECIMAL(8,6) NOT NULL DEFAULT 1,
    source_type VARCHAR(24) NOT NULL DEFAULT 'MANUAL',
    source_ref VARCHAR(128) NULL,
    reason VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_resource_availability PRIMARY KEY (id),
    CONSTRAINT uk_resource_availability UNIQUE (resource_id, window_type, start_at, end_at),
    CONSTRAINT fk_availability_resource FOREIGN KEY (resource_id) REFERENCES aps_resource (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_availability_type CHECK (window_type IN ('AVAILABLE', 'UNAVAILABLE', 'OVERTIME', 'LEAVE', 'MAINTENANCE')),
    CONSTRAINT ck_availability_window CHECK (end_at > start_at),
    CONSTRAINT ck_availability_ratio CHECK (capacity_ratio > 0 AND capacity_ratio <= 1),
    KEY idx_availability_resource_time (resource_id, start_at, end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M05 资源绝对可用或不可用时间窗';

-- ============================================================================
-- B. 产品、工艺与路线（M06-M12）
-- ============================================================================

CREATE TABLE aps_item (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    item_code VARCHAR(64) NOT NULL,
    item_name VARCHAR(128) NOT NULL,
    item_type VARCHAR(16) NOT NULL,
    specification VARCHAR(255) NULL,
    base_uom_code VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    remark VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT uk_item_code UNIQUE (item_code),
    CONSTRAINT uk_item_unit UNIQUE (id, base_uom_code),
    CONSTRAINT ck_item_type CHECK (item_type IN ('PRODUCT', 'SEMI_FINISHED', 'MATERIAL')),
    CONSTRAINT ck_item_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M06 产品、半成品和物料主数据';

CREATE TABLE aps_operation_spec (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operation_code VARCHAR(64) NOT NULL,
    operation_name VARCHAR(128) NOT NULL,
    operation_mode VARCHAR(24) NOT NULL,
    output_item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    interruptible TINYINT UNSIGNED NOT NULL DEFAULT 0,
    quality_gate_required TINYINT UNSIGNED NOT NULL DEFAULT 0,
    batch_capacity DECIMAL(18,6) NULL,
    batch_uom_code VARCHAR(16) NULL,
    compatibility_rule_json JSON NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    remark VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_operation_spec PRIMARY KEY (id),
    CONSTRAINT uk_operation_spec_code UNIQUE (operation_code),
    CONSTRAINT fk_operation_output_item FOREIGN KEY (output_item_id) REFERENCES aps_item (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_operation_mode CHECK (operation_mode IN ('MANUAL', 'MAN_MACHINE', 'AUTO', 'BATCH', 'WAIT', 'TRANSPORT')),
    CONSTRAINT ck_operation_bool CHECK (interruptible IN (0, 1) AND quality_gate_required IN (0, 1)),
    CONSTRAINT ck_operation_batch CHECK ((operation_mode = 'BATCH' AND batch_capacity IS NOT NULL AND batch_capacity > 0 AND batch_uom_code IS NOT NULL) OR (operation_mode <> 'BATCH' AND batch_capacity IS NULL AND batch_uom_code IS NULL)),
    CONSTRAINT ck_operation_status CHECK (status IN ('DRAFT', 'ACTIVE', 'INACTIVE')),
    KEY idx_operation_output_item (output_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M07 可复用工序定义与基础批规则';

CREATE TABLE aps_operation_phase (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operation_spec_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    phase_no SMALLINT UNSIGNED NOT NULL,
    phase_type VARCHAR(16) NOT NULL,
    phase_name VARCHAR(128) NOT NULL,
    duration_model VARCHAR(16) NOT NULL,
    fixed_seconds INT UNSIGNED NOT NULL DEFAULT 0,
    seconds_per_unit DECIMAL(18,6) NOT NULL DEFAULT 0,
    resource_hold_policy VARCHAR(20) NOT NULL DEFAULT 'PHASE_ONLY',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_operation_phase PRIMARY KEY (id),
    CONSTRAINT uk_operation_phase_no UNIQUE (operation_spec_id, phase_no),
    CONSTRAINT uk_operation_phase_scope UNIQUE (operation_spec_id, id),
    CONSTRAINT uk_operation_phase_type UNIQUE (operation_spec_id, id, phase_type),
    CONSTRAINT fk_phase_operation FOREIGN KEY (operation_spec_id) REFERENCES aps_operation_spec (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_phase_type CHECK (phase_type IN ('SETUP', 'RUN', 'UNLOAD', 'WAIT', 'TRANSPORT')),
    CONSTRAINT ck_phase_duration_model CHECK (duration_model IN ('FIXED', 'PER_UNIT', 'FIXED_PLUS_UNIT')),
    CONSTRAINT ck_phase_duration CHECK ((duration_model = 'FIXED' AND fixed_seconds > 0 AND seconds_per_unit = 0) OR (duration_model = 'PER_UNIT' AND fixed_seconds = 0 AND seconds_per_unit > 0) OR (duration_model = 'FIXED_PLUS_UNIT' AND fixed_seconds > 0 AND seconds_per_unit > 0)),
    CONSTRAINT ck_phase_hold CHECK (resource_hold_policy IN ('PHASE_ONLY', 'UNTIL_NEXT_PHASE', 'WHOLE_JOB')),
    KEY idx_phase_operation_scope (operation_spec_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M08 准备、运行、卸料等工艺阶段';

CREATE TABLE aps_resource_requirement (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operation_phase_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    work_center_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    fixed_resource_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    requirement_no SMALLINT UNSIGNED NOT NULL,
    resource_type VARCHAR(20) NOT NULL,
    seat_count SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    required_skill_code VARCHAR(64) NULL,
    min_skill_level SMALLINT UNSIGNED NULL,
    capability_rule_json JSON NULL,
    optional_flag TINYINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_resource_requirement PRIMARY KEY (id),
    CONSTRAINT uk_resource_requirement UNIQUE (operation_phase_id, requirement_no),
    CONSTRAINT uk_requirement_scope UNIQUE (operation_phase_id, id),
    CONSTRAINT uk_requirement_type UNIQUE (operation_phase_id, id, resource_type),
    CONSTRAINT fk_requirement_phase FOREIGN KEY (operation_phase_id) REFERENCES aps_operation_phase (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_requirement_center FOREIGN KEY (work_center_id) REFERENCES aps_work_center (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_requirement_resource FOREIGN KEY (fixed_resource_id, resource_type) REFERENCES aps_resource (id, resource_type) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_requirement_resource_center FOREIGN KEY (fixed_resource_id, resource_type, work_center_id) REFERENCES aps_resource (id, resource_type, work_center_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_requirement_type CHECK (resource_type IN ('PERSON', 'MACHINE', 'WORKSTATION', 'TOOL')),
    CONSTRAINT ck_requirement_seats CHECK (seat_count > 0),
    CONSTRAINT ck_requirement_skill CHECK ((required_skill_code IS NULL AND min_skill_level IS NULL) OR (required_skill_code IS NOT NULL AND min_skill_level IS NOT NULL AND min_skill_level BETWEEN 1 AND 10)),
    CONSTRAINT ck_requirement_optional CHECK (optional_flag IN (0, 1)),
    KEY idx_requirement_phase_scope (operation_phase_id, id),
    KEY idx_requirement_center (work_center_id),
    KEY idx_requirement_resource (fixed_resource_id, resource_type, work_center_id),
    KEY idx_requirement_skill (required_skill_code, min_skill_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M09 阶段资源席位及单一核心技能要求';

CREATE TABLE aps_route_version (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    route_code VARCHAR(64) NOT NULL,
    version_no VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    effective_from DATETIME(3) NULL,
    effective_to DATETIME(3) NULL,
    change_note VARCHAR(500) NULL,
    approved_by VARCHAR(64) NULL,
    approved_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_route_version PRIMARY KEY (id),
    CONSTRAINT uk_route_version UNIQUE (item_id, route_code, version_no),
    CONSTRAINT uk_route_version_item UNIQUE (id, item_id),
    CONSTRAINT fk_route_item FOREIGN KEY (item_id) REFERENCES aps_item (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_route_status CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    CONSTRAINT ck_route_effective CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from),
    KEY idx_route_item_status (item_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M10 产品工艺路线版本';

CREATE TABLE aps_route_node (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    route_version_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operation_spec_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    node_code VARCHAR(64) NOT NULL,
    node_name VARCHAR(128) NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    quantity_multiplier DECIMAL(18,6) NOT NULL DEFAULT 1,
    terminal_flag TINYINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_route_node PRIMARY KEY (id),
    CONSTRAINT uk_route_node_code UNIQUE (route_version_id, node_code),
    CONSTRAINT uk_route_node_scope UNIQUE (route_version_id, id),
    CONSTRAINT uk_route_node_operation UNIQUE (route_version_id, id, operation_spec_id),
    CONSTRAINT fk_route_node_version FOREIGN KEY (route_version_id) REFERENCES aps_route_version (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_route_node_operation FOREIGN KEY (operation_spec_id) REFERENCES aps_operation_spec (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_route_node_qty CHECK (quantity_multiplier > 0),
    CONSTRAINT ck_route_node_terminal CHECK (terminal_flag IN (0, 1)),
    KEY idx_route_node_version (route_version_id, display_order),
    KEY idx_route_node_operation (operation_spec_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M11 路线中的工序节点';

CREATE TABLE aps_route_edge (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    route_version_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    predecessor_node_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    successor_node_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    dependency_type VARCHAR(16) NOT NULL DEFAULT 'FINISH',
    threshold_qty DECIMAL(18,6) NULL,
    threshold_ratio DECIMAL(8,6) NULL,
    transfer_batch_qty DECIMAL(18,6) NULL,
    lag_seconds INT UNSIGNED NOT NULL DEFAULT 0,
    consumes_output TINYINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_route_edge PRIMARY KEY (id),
    CONSTRAINT uk_route_edge UNIQUE (route_version_id, predecessor_node_id, successor_node_id),
    CONSTRAINT fk_route_edge_version FOREIGN KEY (route_version_id) REFERENCES aps_route_version (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_route_edge_predecessor FOREIGN KEY (route_version_id, predecessor_node_id) REFERENCES aps_route_node (route_version_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_route_edge_successor FOREIGN KEY (route_version_id, successor_node_id) REFERENCES aps_route_node (route_version_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_route_edge_distinct CHECK (predecessor_node_id <> successor_node_id),
    CONSTRAINT ck_route_edge_type CHECK (dependency_type IN ('FINISH', 'QUANTITY', 'SAME_START')),
    CONSTRAINT ck_route_edge_threshold CHECK ((dependency_type = 'FINISH' AND threshold_qty IS NULL AND threshold_ratio IS NULL AND transfer_batch_qty IS NULL) OR (dependency_type = 'QUANTITY' AND ((threshold_qty IS NOT NULL AND threshold_ratio IS NULL AND threshold_qty > 0) OR (threshold_qty IS NULL AND threshold_ratio IS NOT NULL AND threshold_ratio > 0 AND threshold_ratio <= 1))) OR (dependency_type = 'SAME_START' AND threshold_qty IS NULL AND threshold_ratio IS NULL AND transfer_batch_qty IS NULL AND lag_seconds = 0 AND consumes_output = 0)),
    CONSTRAINT ck_route_edge_transfer CHECK (transfer_batch_qty IS NULL OR transfer_batch_qty > 0),
    CONSTRAINT ck_route_edge_consume CHECK (consumes_output IN (0, 1)),
    KEY idx_route_edge_version (route_version_id),
    KEY idx_route_edge_predecessor (route_version_id, predecessor_node_id),
    KEY idx_route_edge_successor (route_version_id, successor_node_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M12 路线节点依赖；SAME_START 仅保留来源且 P0 阻断执行';

-- ============================================================================
-- C. 订单、生产实例与任务（M13-M18）
-- ============================================================================

CREATE TABLE aps_order (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    order_no VARCHAR(64) NOT NULL,
    source_system VARCHAR(32) NOT NULL DEFAULT 'LOCAL',
    external_id VARCHAR(128) NULL,
    customer_code VARCHAR(64) NULL,
    customer_name VARCHAR(128) NULL,
    priority SMALLINT NOT NULL DEFAULT 50,
    promised_at DATETIME(3) NULL,
    earliest_start_at DATETIME(3) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    remark VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_order PRIMARY KEY (id),
    CONSTRAINT uk_order_no UNIQUE (order_no),
    CONSTRAINT uk_order_external UNIQUE (source_system, external_id),
    CONSTRAINT ck_order_priority CHECK (priority BETWEEN 1 AND 100),
    CONSTRAINT ck_order_status CHECK (status IN ('DRAFT', 'RELEASED', 'IN_PRODUCTION', 'COMPLETED', 'CANCELLED')),
    KEY idx_order_due (status, promised_at, priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M13 生产订单头';

CREATE TABLE aps_order_line (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    order_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    line_no INT UNSIGNED NOT NULL,
    item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    route_version_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    demand_qty DECIMAL(18,6) NOT NULL,
    uom_code VARCHAR(16) NOT NULL,
    promised_at DATETIME(3) NULL,
    earliest_start_at DATETIME(3) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    component_snapshot_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_order_line PRIMARY KEY (id),
    CONSTRAINT uk_order_line_no UNIQUE (order_id, line_no),
    CONSTRAINT uk_order_line_scope UNIQUE (id, item_id, route_version_id, uom_code),
    CONSTRAINT fk_order_line_order FOREIGN KEY (order_id) REFERENCES aps_order (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_order_line_item FOREIGN KEY (item_id, uom_code) REFERENCES aps_item (id, base_uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_order_line_route FOREIGN KEY (route_version_id, item_id) REFERENCES aps_route_version (id, item_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_order_line_qty CHECK (demand_qty > 0),
    CONSTRAINT ck_order_line_status CHECK (status IN ('DRAFT', 'RELEASED', 'IN_PRODUCTION', 'COMPLETED', 'CANCELLED')),
    KEY idx_order_line_item (item_id, uom_code, status),
    KEY idx_order_line_route (route_version_id, item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M14 订单内独立产品需求行';

CREATE TABLE aps_production_lot (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    order_line_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    route_version_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    parent_lot_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    lot_no VARCHAR(64) NOT NULL,
    lot_type VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    planned_qty DECIMAL(18,6) NOT NULL,
    uom_code VARCHAR(16) NOT NULL,
    recovery_reason VARCHAR(500) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_production_lot PRIMARY KEY (id),
    CONSTRAINT uk_production_lot_no UNIQUE (lot_no),
    CONSTRAINT uk_production_lot_route UNIQUE (id, route_version_id, uom_code),
    CONSTRAINT uk_production_lot_item UNIQUE (id, item_id, uom_code),
    CONSTRAINT uk_production_lot_lineage UNIQUE (order_line_id, item_id, route_version_id, uom_code, id),
    CONSTRAINT fk_production_lot_line FOREIGN KEY (order_line_id, item_id, route_version_id, uom_code) REFERENCES aps_order_line (id, item_id, route_version_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_production_lot_parent FOREIGN KEY (order_line_id, item_id, route_version_id, uom_code, parent_lot_id) REFERENCES aps_production_lot (order_line_id, item_id, route_version_id, uom_code, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_production_lot_type CHECK (lot_type IN ('NORMAL', 'SPLIT', 'REWORK', 'REPLENISH')),
    CONSTRAINT ck_production_lot_parent CHECK ((lot_type = 'NORMAL' AND parent_lot_id IS NULL) OR (lot_type IN ('SPLIT', 'REWORK', 'REPLENISH') AND parent_lot_id IS NOT NULL AND parent_lot_id <> id)),
    CONSTRAINT ck_production_lot_qty CHECK (planned_qty > 0),
    CONSTRAINT ck_production_lot_status CHECK (status IN ('PLANNED', 'RELEASED', 'IN_PRODUCTION', 'COMPLETED', 'CANCELLED')),
    KEY idx_production_lot_line (order_line_id, item_id, route_version_id, uom_code, status),
    KEY idx_production_lot_parent (order_line_id, item_id, route_version_id, uom_code, parent_lot_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M15 正常、拆分、返工或补产生产实例';

CREATE TABLE aps_task (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    production_lot_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    route_version_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    route_node_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operation_spec_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    work_center_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    task_code VARCHAR(64) NOT NULL,
    task_name VARCHAR(128) NOT NULL,
    task_qty DECIMAL(18,6) NOT NULL,
    uom_code VARCHAR(16) NOT NULL,
    setup_seconds INT UNSIGNED NOT NULL DEFAULT 0,
    run_seconds INT UNSIGNED NOT NULL DEFAULT 0,
    unload_seconds INT UNSIGNED NOT NULL DEFAULT 0,
    wait_seconds INT UNSIGNED NOT NULL DEFAULT 0,
    transport_seconds INT UNSIGNED NOT NULL DEFAULT 0,
    interruptible TINYINT UNSIGNED NOT NULL DEFAULT 0,
    required_skill_code VARCHAR(64) NULL,
    min_skill_level SMALLINT UNSIGNED NULL,
    requirement_snapshot_json JSON NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'NOT_READY',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_task PRIMARY KEY (id),
    CONSTRAINT uk_task_code UNIQUE (task_code),
    CONSTRAINT uk_task_lot UNIQUE (id, production_lot_id, uom_code),
    CONSTRAINT uk_task_operation UNIQUE (id, operation_spec_id, uom_code),
    CONSTRAINT uk_task_unit UNIQUE (id, uom_code),
    CONSTRAINT fk_task_lot_route FOREIGN KEY (production_lot_id, route_version_id, uom_code) REFERENCES aps_production_lot (id, route_version_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_task_node_operation FOREIGN KEY (route_version_id, route_node_id, operation_spec_id) REFERENCES aps_route_node (route_version_id, id, operation_spec_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_task_center FOREIGN KEY (work_center_id) REFERENCES aps_work_center (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_task_qty CHECK (task_qty > 0),
    CONSTRAINT ck_task_duration CHECK (setup_seconds > 0 OR run_seconds > 0 OR unload_seconds > 0 OR wait_seconds > 0 OR transport_seconds > 0),
    CONSTRAINT ck_task_interruptible CHECK (interruptible IN (0, 1)),
    CONSTRAINT ck_task_skill CHECK ((required_skill_code IS NULL AND min_skill_level IS NULL) OR (required_skill_code IS NOT NULL AND min_skill_level IS NOT NULL AND min_skill_level BETWEEN 1 AND 10)),
    CONSTRAINT ck_task_status CHECK (status IN ('NOT_READY', 'READY', 'PLANNED', 'DISPATCHED', 'RUNNING', 'PAUSED', 'WAIT_QUALITY', 'COMPLETED', 'CANCELLED')),
    KEY idx_task_lot (production_lot_id, route_version_id, uom_code, status),
    KEY idx_task_route_node (route_version_id, route_node_id, operation_spec_id),
    KEY idx_task_operation (operation_spec_id),
    KEY idx_task_center (work_center_id, status),
    KEY idx_task_skill (required_skill_code, min_skill_level, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M16 已展开并冻结关键工艺参数的工序任务';

CREATE TABLE aps_task_dependency (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    predecessor_task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    successor_task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    dependency_type VARCHAR(16) NOT NULL DEFAULT 'FINISH',
    threshold_qty DECIMAL(18,6) NULL,
    threshold_ratio DECIMAL(8,6) NULL,
    transfer_batch_qty DECIMAL(18,6) NULL,
    uom_code VARCHAR(16) NULL,
    lag_seconds INT UNSIGNED NOT NULL DEFAULT 0,
    consumes_output TINYINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_task_dependency PRIMARY KEY (id),
    CONSTRAINT uk_task_dependency UNIQUE (predecessor_task_id, successor_task_id),
    CONSTRAINT fk_task_dep_predecessor FOREIGN KEY (predecessor_task_id) REFERENCES aps_task (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_task_dep_successor FOREIGN KEY (successor_task_id) REFERENCES aps_task (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_task_dep_distinct CHECK (predecessor_task_id <> successor_task_id),
    CONSTRAINT ck_task_dep_type CHECK (dependency_type IN ('FINISH', 'QUANTITY', 'SAME_START')),
    CONSTRAINT ck_task_dep_threshold CHECK ((dependency_type = 'FINISH' AND threshold_qty IS NULL AND threshold_ratio IS NULL AND transfer_batch_qty IS NULL AND uom_code IS NULL) OR (dependency_type = 'QUANTITY' AND ((threshold_qty IS NOT NULL AND threshold_ratio IS NULL AND threshold_qty > 0 AND uom_code IS NOT NULL) OR (threshold_qty IS NULL AND threshold_ratio IS NOT NULL AND threshold_ratio > 0 AND threshold_ratio <= 1))) OR (dependency_type = 'SAME_START' AND threshold_qty IS NULL AND threshold_ratio IS NULL AND transfer_batch_qty IS NULL AND uom_code IS NULL AND lag_seconds = 0 AND consumes_output = 0)),
    CONSTRAINT ck_task_dep_transfer CHECK (transfer_batch_qty IS NULL OR (transfer_batch_qty > 0 AND uom_code IS NOT NULL)),
    CONSTRAINT ck_task_dep_consume CHECK (consumes_output IN (0, 1)),
    KEY idx_task_dep_predecessor (predecessor_task_id),
    KEY idx_task_dep_successor (successor_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M17 任务依赖；SAME_START 仅冻结来源且 P0 阻断执行';

CREATE TABLE aps_material_demand (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    target_task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    demand_no SMALLINT UNSIGNED NOT NULL,
    item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    demand_type VARCHAR(16) NOT NULL DEFAULT 'COMPONENT',
    required_qty DECIMAL(18,6) NOT NULL,
    uom_code VARCHAR(16) NOT NULL,
    transfer_batch_qty DECIMAL(18,6) NULL,
    material_status VARCHAR(20) NOT NULL DEFAULT 'UNAVAILABLE',
    ready_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_material_demand PRIMARY KEY (id),
    CONSTRAINT uk_material_demand_no UNIQUE (target_task_id, demand_no),
    CONSTRAINT uk_material_demand_scope UNIQUE (id, target_task_id, item_id, uom_code),
    CONSTRAINT fk_material_demand_task FOREIGN KEY (target_task_id) REFERENCES aps_task (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_material_demand_item FOREIGN KEY (item_id, uom_code) REFERENCES aps_item (id, base_uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_material_demand_source FOREIGN KEY (source_task_id, uom_code) REFERENCES aps_task (id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_material_demand_type CHECK (demand_type IN ('COMPONENT', 'TRANSFER', 'EXTERNAL')),
    CONSTRAINT ck_material_demand_qty CHECK (required_qty > 0),
    CONSTRAINT ck_material_demand_batch CHECK (transfer_batch_qty IS NULL OR transfer_batch_qty > 0),
    CONSTRAINT ck_material_demand_source CHECK ((demand_type = 'TRANSFER' AND source_task_id IS NOT NULL AND source_task_id <> target_task_id) OR (demand_type = 'EXTERNAL' AND source_task_id IS NULL) OR (demand_type = 'COMPONENT' AND (source_task_id IS NULL OR source_task_id <> target_task_id))),
    CONSTRAINT ck_material_demand_status CHECK (material_status IN ('UNAVAILABLE', 'PARTIAL', 'AVAILABLE', 'CONSUMED', 'CANCELLED')),
    KEY idx_material_demand_task (target_task_id, material_status),
    KEY idx_material_demand_item (item_id, uom_code, material_status),
    KEY idx_material_demand_source (source_task_id, uom_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M18 P0 粗粒度物料或上游产出需求';

-- ============================================================================
-- D. 排程、共享批与发布（M19-M24）
-- ============================================================================

CREATE TABLE aps_plan_version (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    base_version_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    version_no BIGINT UNSIGNED NOT NULL,
    version_name VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    is_current TINYINT UNSIGNED NOT NULL DEFAULT 0,
    current_published_marker TINYINT GENERATED ALWAYS AS (CASE WHEN status = 'PUBLISHED' AND is_current = 1 THEN 1 ELSE NULL END) STORED,
    daily_baseline_date DATE NULL,
    request_id VARCHAR(64) NOT NULL,
    definition_revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
    execution_revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
    input_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    input_snapshot_json JSON NOT NULL,
    solver_summary_json JSON NULL,
    validation_summary_json JSON NULL,
    change_note VARCHAR(500) NULL,
    published_at DATETIME(3) NULL,
    published_by VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_plan_version PRIMARY KEY (id),
    CONSTRAINT uk_plan_version_no UNIQUE (version_no),
    CONSTRAINT uk_plan_version_request UNIQUE (request_id),
    CONSTRAINT uk_plan_version_current UNIQUE (current_published_marker),
    CONSTRAINT uk_plan_version_baseline UNIQUE (daily_baseline_date),
    CONSTRAINT fk_plan_version_base FOREIGN KEY (base_version_id) REFERENCES aps_plan_version (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_plan_version_status CHECK (status IN ('DRAFT', 'SOLVING', 'FEASIBLE', 'CONFLICT', 'CANCELLED', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'SUPERSEDED')),
    CONSTRAINT ck_plan_version_current CHECK (is_current IN (0, 1) AND (is_current = 0 OR status = 'PUBLISHED')),
    CONSTRAINT ck_plan_version_publish CHECK (((status IN ('PUBLISHED', 'SUPERSEDED')) AND published_at IS NOT NULL) OR ((status NOT IN ('PUBLISHED', 'SUPERSEDED')) AND published_at IS NULL)),
    CONSTRAINT ck_plan_version_baseline CHECK (daily_baseline_date IS NULL OR status IN ('PUBLISHED', 'SUPERSEDED')),
    KEY idx_plan_version_base (base_version_id),
    KEY idx_plan_version_status (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M19 候选、正式版本与每日冻结基线；不再单建 plan_scope';

CREATE TABLE aps_plan_job (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_version_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operation_spec_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    work_center_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    job_code VARCHAR(64) NOT NULL,
    job_type VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    batch_code VARCHAR(64) NULL,
    planned_qty DECIMAL(18,6) NOT NULL,
    uom_code VARCHAR(16) NOT NULL,
    capacity_value DECIMAL(18,6) NULL,
    capacity_uom_code VARCHAR(16) NULL,
    compatibility_key VARCHAR(128) NULL,
    planned_start_at DATETIME(3) NOT NULL,
    planned_end_at DATETIME(3) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_plan_job PRIMARY KEY (id),
    CONSTRAINT uk_plan_job_code UNIQUE (plan_version_id, job_code),
    CONSTRAINT uk_plan_job_version UNIQUE (plan_version_id, id),
    CONSTRAINT uk_plan_job_version_unit UNIQUE (plan_version_id, id, uom_code),
    CONSTRAINT uk_plan_job_operation UNIQUE (id, operation_spec_id, uom_code),
    CONSTRAINT fk_plan_job_version FOREIGN KEY (plan_version_id) REFERENCES aps_plan_version (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_plan_job_operation FOREIGN KEY (operation_spec_id) REFERENCES aps_operation_spec (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_plan_job_center FOREIGN KEY (work_center_id) REFERENCES aps_work_center (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_plan_job_type CHECK (job_type IN ('NORMAL', 'SPLIT', 'SHARED_BATCH')),
    CONSTRAINT ck_plan_job_qty CHECK (planned_qty > 0),
    CONSTRAINT ck_plan_job_capacity CHECK ((job_type = 'SHARED_BATCH' AND batch_code IS NOT NULL AND capacity_value IS NOT NULL AND capacity_value > 0 AND capacity_uom_code IS NOT NULL) OR (job_type <> 'SHARED_BATCH' AND batch_code IS NULL AND capacity_value IS NULL AND capacity_uom_code IS NULL)),
    CONSTRAINT ck_plan_job_time CHECK (planned_end_at > planned_start_at),
    KEY idx_plan_job_version_time (plan_version_id, planned_start_at, planned_end_at),
    KEY idx_plan_job_operation (operation_spec_id),
    KEY idx_plan_job_center (work_center_id, planned_start_at, planned_end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M20 普通、拆分或共享加工批计划作业';

CREATE TABLE aps_plan_job_member (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_job_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operation_spec_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    member_no SMALLINT UNSIGNED NOT NULL,
    planned_qty DECIMAL(18,6) NOT NULL,
    uom_code VARCHAR(16) NOT NULL,
    allocation_ratio DECIMAL(8,6) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_plan_job_member PRIMARY KEY (id),
    CONSTRAINT uk_plan_job_member_task UNIQUE (plan_job_id, task_id),
    CONSTRAINT uk_plan_job_member_no UNIQUE (plan_job_id, member_no),
    CONSTRAINT uk_plan_member_scope UNIQUE (plan_job_id, id, task_id, uom_code),
    CONSTRAINT fk_plan_member_job FOREIGN KEY (plan_job_id, operation_spec_id, uom_code) REFERENCES aps_plan_job (id, operation_spec_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_plan_member_task FOREIGN KEY (task_id, operation_spec_id, uom_code) REFERENCES aps_task (id, operation_spec_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_plan_member_qty CHECK (planned_qty > 0),
    CONSTRAINT ck_plan_member_ratio CHECK (allocation_ratio IS NULL OR (allocation_ratio > 0 AND allocation_ratio <= 1)),
    KEY idx_plan_member_job (plan_job_id, operation_spec_id, uom_code),
    KEY idx_plan_member_task (task_id, operation_spec_id, uom_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M21 共享批或拆批作业中的任务成员及数量归属';

CREATE TABLE aps_plan_segment (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_job_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operation_spec_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operation_phase_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    segment_no SMALLINT UNSIGNED NOT NULL,
    phase_type VARCHAR(16) NOT NULL,
    start_at DATETIME(3) NOT NULL,
    end_at DATETIME(3) NOT NULL,
    planned_qty DECIMAL(18,6) NULL,
    release_at DATETIME(3) NULL,
    release_qty DECIMAL(18,6) NULL,
    uom_code VARCHAR(16) NOT NULL,
    interruption_reason VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_plan_segment PRIMARY KEY (id),
    CONSTRAINT uk_plan_segment_no UNIQUE (plan_job_id, segment_no),
    CONSTRAINT uk_plan_segment_job UNIQUE (plan_job_id, id),
    CONSTRAINT uk_plan_segment_phase UNIQUE (id, operation_phase_id),
    CONSTRAINT fk_plan_segment_job FOREIGN KEY (plan_job_id, operation_spec_id, uom_code) REFERENCES aps_plan_job (id, operation_spec_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_plan_segment_phase FOREIGN KEY (operation_spec_id, operation_phase_id, phase_type) REFERENCES aps_operation_phase (operation_spec_id, id, phase_type) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_plan_segment_phase CHECK (phase_type IN ('SETUP', 'RUN', 'UNLOAD', 'WAIT', 'TRANSPORT')),
    CONSTRAINT ck_plan_segment_time CHECK (end_at > start_at),
    CONSTRAINT ck_plan_segment_qty CHECK ((planned_qty IS NULL OR planned_qty > 0) AND (release_qty IS NULL OR release_qty > 0)),
    CONSTRAINT ck_plan_segment_release CHECK ((release_at IS NULL AND release_qty IS NULL) OR (release_at IS NOT NULL AND release_qty IS NOT NULL AND release_qty > 0)),
    KEY idx_plan_segment_job (plan_job_id, operation_spec_id, uom_code, start_at, end_at),
    KEY idx_plan_segment_phase (operation_spec_id, operation_phase_id, phase_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M22 准备、运行、卸料与跨班中断的计划时间段';

CREATE TABLE aps_plan_allocation (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_segment_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    operation_phase_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    resource_requirement_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    resource_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    allocation_role VARCHAR(20) NOT NULL,
    seat_no SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    capacity_used DECIMAL(18,6) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_plan_allocation PRIMARY KEY (id),
    CONSTRAINT uk_plan_allocation_resource UNIQUE (plan_segment_id, resource_id),
    CONSTRAINT uk_plan_allocation_seat UNIQUE (plan_segment_id, allocation_role, seat_no),
    CONSTRAINT uk_plan_allocation_scope UNIQUE (plan_segment_id, id),
    CONSTRAINT uk_plan_allocation_resource_scope UNIQUE (plan_segment_id, id, resource_id),
    CONSTRAINT fk_plan_allocation_segment FOREIGN KEY (plan_segment_id, operation_phase_id) REFERENCES aps_plan_segment (id, operation_phase_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_plan_allocation_requirement FOREIGN KEY (operation_phase_id, resource_requirement_id, allocation_role) REFERENCES aps_resource_requirement (operation_phase_id, id, resource_type) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_plan_allocation_resource FOREIGN KEY (resource_id, allocation_role) REFERENCES aps_resource (id, resource_type) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_plan_allocation_role CHECK (allocation_role IN ('PERSON', 'MACHINE', 'WORKSTATION', 'TOOL')),
    CONSTRAINT ck_plan_allocation_capacity CHECK (capacity_used > 0),
    KEY idx_plan_allocation_segment (plan_segment_id, operation_phase_id),
    KEY idx_plan_allocation_requirement (operation_phase_id, resource_requirement_id, allocation_role),
    KEY idx_plan_allocation_resource_time (resource_id, allocation_role, plan_segment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M23 每个计划分段分配到的具体人员和设备';

CREATE TABLE aps_plan_lock (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_version_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_job_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_segment_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    plan_allocation_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    locked_resource_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    target_type VARCHAR(16) NOT NULL,
    lock_type VARCHAR(16) NOT NULL,
    locked_start_at DATETIME(3) NULL,
    locked_end_at DATETIME(3) NULL,
    lock_reason VARCHAR(500) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_plan_lock PRIMARY KEY (id),
    CONSTRAINT fk_plan_lock_job FOREIGN KEY (plan_version_id, plan_job_id) REFERENCES aps_plan_job (plan_version_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_plan_lock_segment FOREIGN KEY (plan_job_id, plan_segment_id) REFERENCES aps_plan_segment (plan_job_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_plan_lock_allocation FOREIGN KEY (plan_segment_id, plan_allocation_id) REFERENCES aps_plan_allocation (plan_segment_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_plan_lock_resource FOREIGN KEY (locked_resource_id) REFERENCES aps_resource (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_plan_lock_target_type CHECK (target_type IN ('JOB', 'SEGMENT', 'ALLOCATION')),
    CONSTRAINT ck_plan_lock_type CHECK (lock_type IN ('TIME', 'RESOURCE', 'FULL')),
    CONSTRAINT ck_plan_lock_target CHECK ((target_type = 'JOB' AND plan_segment_id IS NULL AND plan_allocation_id IS NULL) OR (target_type = 'SEGMENT' AND plan_segment_id IS NOT NULL AND plan_allocation_id IS NULL) OR (target_type = 'ALLOCATION' AND plan_segment_id IS NOT NULL AND plan_allocation_id IS NOT NULL)),
    CONSTRAINT ck_plan_lock_value CHECK ((lock_type = 'TIME' AND locked_start_at IS NOT NULL AND locked_end_at IS NOT NULL AND locked_end_at > locked_start_at AND locked_resource_id IS NULL) OR (lock_type = 'RESOURCE' AND locked_start_at IS NULL AND locked_end_at IS NULL AND locked_resource_id IS NOT NULL) OR (lock_type = 'FULL' AND locked_start_at IS NOT NULL AND locked_end_at IS NOT NULL AND locked_end_at > locked_start_at AND locked_resource_id IS NOT NULL)),
    CONSTRAINT fk_plan_lock_allocation_resource FOREIGN KEY (plan_segment_id, plan_allocation_id, locked_resource_id) REFERENCES aps_plan_allocation (plan_segment_id, id, resource_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    KEY idx_plan_lock_job (plan_version_id, plan_job_id),
    KEY idx_plan_lock_segment (plan_job_id, plan_segment_id),
    KEY idx_plan_lock_allocation (plan_segment_id, plan_allocation_id, locked_resource_id),
    KEY idx_plan_lock_resource (locked_resource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M24 时间锁、资源锁和全锁；锁定不绕过现实冲突';

-- ============================================================================
-- E. 执行、数量与质量（M25-M29）
-- ============================================================================

CREATE TABLE aps_execution_run (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_version_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_job_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    run_no INT UNSIGNED NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'READY',
    assigned_qty DECIMAL(18,6) NOT NULL,
    uom_code VARCHAR(16) NOT NULL,
    actual_start_at DATETIME(3) NULL,
    actual_end_at DATETIME(3) NULL,
    pause_reason VARCHAR(500) NULL,
    request_id VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_execution_run PRIMARY KEY (id),
    CONSTRAINT uk_execution_run_no UNIQUE (plan_job_id, run_no),
    CONSTRAINT uk_execution_run_request UNIQUE (request_id),
    CONSTRAINT uk_execution_run_job UNIQUE (plan_job_id, id),
    CONSTRAINT uk_execution_run_job_unit UNIQUE (plan_job_id, id, uom_code),
    CONSTRAINT fk_execution_run_job FOREIGN KEY (plan_version_id, plan_job_id, uom_code) REFERENCES aps_plan_job (plan_version_id, id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_execution_run_status CHECK (status IN ('READY', 'RUNNING', 'PAUSED', 'WAIT_QUALITY', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_execution_run_qty CHECK (assigned_qty > 0),
    CONSTRAINT ck_execution_run_time CHECK ((status = 'READY' AND actual_start_at IS NULL AND actual_end_at IS NULL) OR (status IN ('RUNNING', 'PAUSED') AND actual_start_at IS NOT NULL AND actual_end_at IS NULL) OR (status IN ('WAIT_QUALITY', 'COMPLETED') AND actual_start_at IS NOT NULL AND actual_end_at IS NOT NULL AND actual_end_at >= actual_start_at) OR (status = 'CANCELLED' AND ((actual_start_at IS NULL AND actual_end_at IS NULL) OR (actual_start_at IS NOT NULL AND actual_end_at IS NOT NULL AND actual_end_at >= actual_start_at)))),
    KEY idx_execution_run_version (plan_version_id, plan_job_id, uom_code),
    KEY idx_execution_run_job (plan_job_id, status),
    KEY idx_execution_run_status (status, actual_start_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M25 已发布计划作业的一次实际运行';

CREATE TABLE aps_actual_occupancy (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_job_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    execution_run_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_segment_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    resource_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    activity_type VARCHAR(20) NOT NULL,
    start_at DATETIME(3) NOT NULL,
    end_at DATETIME(3) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    correction_of_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    reason VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_actual_occupancy PRIMARY KEY (id),
    CONSTRAINT uk_actual_occupancy_correction UNIQUE (correction_of_id),
    CONSTRAINT uk_actual_occupancy_scope UNIQUE (id, plan_job_id, execution_run_id, resource_id),
    CONSTRAINT fk_actual_occupancy_run FOREIGN KEY (plan_job_id, execution_run_id) REFERENCES aps_execution_run (plan_job_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_actual_occupancy_segment FOREIGN KEY (plan_job_id, plan_segment_id) REFERENCES aps_plan_segment (plan_job_id, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_actual_occupancy_resource FOREIGN KEY (resource_id) REFERENCES aps_resource (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_actual_occupancy_correction FOREIGN KEY (correction_of_id, plan_job_id, execution_run_id, resource_id) REFERENCES aps_actual_occupancy (id, plan_job_id, execution_run_id, resource_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_actual_occupancy_type CHECK (activity_type IN ('SETUP', 'RUN', 'UNLOAD', 'WAIT_HOLD', 'PAUSE_HOLD', 'TRANSPORT')),
    CONSTRAINT ck_actual_occupancy_time CHECK ((status = 'ACTIVE' AND end_at IS NULL) OR (status IN ('COMPLETED', 'CORRECTION', 'VOID') AND end_at IS NOT NULL AND end_at >= start_at)),
    CONSTRAINT ck_actual_occupancy_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'CORRECTION', 'VOID')),
    CONSTRAINT ck_actual_occupancy_correction CHECK ((status = 'CORRECTION' AND correction_of_id IS NOT NULL AND correction_of_id <> id) OR (status <> 'CORRECTION' AND correction_of_id IS NULL)),
    KEY idx_actual_occupancy_run (plan_job_id, execution_run_id, start_at),
    KEY idx_actual_occupancy_segment (plan_job_id, plan_segment_id),
    KEY idx_actual_occupancy_resource (resource_id, start_at, end_at),
    KEY idx_actual_occupancy_correction (correction_of_id, plan_job_id, execution_run_id, resource_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M26 人员和设备真实占用时间段';

CREATE TABLE aps_production_report (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_job_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    execution_run_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_job_member_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    report_type VARCHAR(16) NOT NULL DEFAULT 'PROGRESS',
    reported_at DATETIME(3) NOT NULL,
    processed_qty DECIMAL(18,6) NOT NULL DEFAULT 0,
    good_qty DECIMAL(18,6) NOT NULL DEFAULT 0,
    pending_qty DECIMAL(18,6) NOT NULL DEFAULT 0,
    rejected_qty DECIMAL(18,6) NOT NULL DEFAULT 0,
    scrap_qty DECIMAL(18,6) NOT NULL DEFAULT 0,
    transferred_qty DECIMAL(18,6) NOT NULL DEFAULT 0,
    uom_code VARCHAR(16) NOT NULL,
    defect_reason VARCHAR(500) NULL,
    correction_of_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    request_id VARCHAR(64) NOT NULL,
    operator_user_id VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_production_report PRIMARY KEY (id),
    CONSTRAINT uk_production_report_request UNIQUE (request_id),
    CONSTRAINT uk_production_report_correction UNIQUE (correction_of_id),
    CONSTRAINT uk_production_report_task UNIQUE (id, task_id, uom_code),
    CONSTRAINT uk_production_report_run UNIQUE (id, execution_run_id, uom_code),
    CONSTRAINT uk_production_report_scope UNIQUE (id, plan_job_id, execution_run_id, plan_job_member_id, task_id, uom_code),
    CONSTRAINT fk_report_run FOREIGN KEY (plan_job_id, execution_run_id, uom_code) REFERENCES aps_execution_run (plan_job_id, id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_report_member FOREIGN KEY (plan_job_id, plan_job_member_id, task_id, uom_code) REFERENCES aps_plan_job_member (plan_job_id, id, task_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_report_correction FOREIGN KEY (correction_of_id, plan_job_id, execution_run_id, plan_job_member_id, task_id, uom_code) REFERENCES aps_production_report (id, plan_job_id, execution_run_id, plan_job_member_id, task_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_report_type CHECK (report_type IN ('PROGRESS', 'COMPLETE', 'CORRECTION')),
    CONSTRAINT ck_report_qty_nonnegative CHECK (processed_qty >= 0 AND good_qty >= 0 AND pending_qty >= 0 AND rejected_qty >= 0 AND scrap_qty >= 0 AND transferred_qty >= 0),
    CONSTRAINT ck_report_qty_positive CHECK (report_type = 'CORRECTION' OR processed_qty > 0),
    CONSTRAINT ck_report_qty_balance CHECK (processed_qty = good_qty + pending_qty + rejected_qty),
    CONSTRAINT ck_report_quality_subset CHECK (scrap_qty <= rejected_qty AND transferred_qty <= good_qty),
    CONSTRAINT ck_report_correction CHECK ((report_type = 'CORRECTION' AND correction_of_id IS NOT NULL AND correction_of_id <> id) OR (report_type <> 'CORRECTION' AND correction_of_id IS NULL)),
    KEY idx_report_run (plan_job_id, execution_run_id, uom_code, reported_at),
    KEY idx_report_member (plan_job_id, plan_job_member_id, task_id, uom_code, reported_at),
    KEY idx_report_task (task_id, reported_at),
    KEY idx_report_correction (correction_of_id, plan_job_id, execution_run_id, plan_job_member_id, task_id, uom_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M27 部分报工、质量数量与冲正依据';

CREATE TABLE aps_output_lot (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    production_lot_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_report_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_output_lot_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    output_lot_no VARCHAR(64) NOT NULL,
    quality_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    total_qty DECIMAL(18,6) NOT NULL,
    available_qty DECIMAL(18,6) NOT NULL DEFAULT 0,
    reserved_qty DECIMAL(18,6) NOT NULL DEFAULT 0,
    consumed_qty DECIMAL(18,6) NOT NULL DEFAULT 0,
    scrapped_qty DECIMAL(18,6) NOT NULL DEFAULT 0,
    uom_code VARCHAR(16) NOT NULL,
    disposition_type VARCHAR(20) NOT NULL DEFAULT 'NONE',
    disposition_reason VARCHAR(500) NULL,
    approved_by VARCHAR(64) NULL,
    approved_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    updated_by VARCHAR(64) NULL,
    row_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    CONSTRAINT pk_output_lot PRIMARY KEY (id),
    CONSTRAINT uk_output_lot_no UNIQUE (output_lot_no),
    CONSTRAINT uk_output_lot_item UNIQUE (id, item_id, uom_code),
    CONSTRAINT uk_output_lot_report UNIQUE (id, source_report_id),
    CONSTRAINT fk_output_lot_production FOREIGN KEY (production_lot_id, item_id, uom_code) REFERENCES aps_production_lot (id, item_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_output_lot_task FOREIGN KEY (source_task_id, production_lot_id, uom_code) REFERENCES aps_task (id, production_lot_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_output_lot_report FOREIGN KEY (source_report_id, source_task_id, uom_code) REFERENCES aps_production_report (id, task_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_output_lot_source FOREIGN KEY (source_output_lot_id, item_id, uom_code) REFERENCES aps_output_lot (id, item_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_output_lot_quality CHECK (quality_status IN ('PENDING', 'RELEASED', 'HOLD', 'REJECTED', 'CLOSED')),
    CONSTRAINT ck_output_lot_quantities CHECK (total_qty > 0 AND available_qty >= 0 AND reserved_qty >= 0 AND consumed_qty >= 0 AND scrapped_qty >= 0),
    CONSTRAINT ck_output_lot_balance CHECK (available_qty + reserved_qty + consumed_qty + scrapped_qty <= total_qty),
    CONSTRAINT ck_output_lot_disposition CHECK (disposition_type IN ('NONE', 'REWORK', 'SCRAP', 'USE_AS_IS')),
    CONSTRAINT ck_output_lot_disposition_detail CHECK (disposition_type = 'NONE' OR disposition_reason IS NOT NULL),
    KEY idx_output_lot_production (production_lot_id, item_id, uom_code),
    KEY idx_output_lot_task (source_task_id, production_lot_id, uom_code),
    KEY idx_output_lot_report (source_report_id, source_task_id, uom_code),
    KEY idx_output_lot_item_quality (item_id, quality_status),
    KEY idx_output_lot_source (source_output_lot_id, item_id, uom_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M28 实物产出批、当前数量投影和简化质量处置';

CREATE TABLE aps_quantity_event (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    output_lot_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    material_demand_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    execution_run_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    production_report_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    target_task_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    reversal_of_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    event_type VARCHAR(20) NOT NULL,
    from_bucket VARCHAR(20) NULL,
    to_bucket VARCHAR(20) NULL,
    quantity DECIMAL(18,6) NOT NULL,
    uom_code VARCHAR(16) NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    occurred_at DATETIME(3) NOT NULL,
    actor_user_id VARCHAR(64) NULL,
    reason VARCHAR(500) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    created_by VARCHAR(64) NULL,
    CONSTRAINT pk_quantity_event PRIMARY KEY (id),
    CONSTRAINT uk_quantity_event_request UNIQUE (request_id),
    CONSTRAINT uk_quantity_event_reversal UNIQUE (reversal_of_id),
    CONSTRAINT uk_quantity_event_scope UNIQUE (id, output_lot_id, item_id, uom_code),
    CONSTRAINT fk_quantity_event_lot_scope FOREIGN KEY (output_lot_id, item_id, uom_code) REFERENCES aps_output_lot (id, item_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_quantity_event_demand_scope FOREIGN KEY (material_demand_id, target_task_id, item_id, uom_code) REFERENCES aps_material_demand (id, target_task_id, item_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_quantity_event_run FOREIGN KEY (execution_run_id) REFERENCES aps_execution_run (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_quantity_event_report_scope FOREIGN KEY (production_report_id, execution_run_id, uom_code) REFERENCES aps_production_report (id, execution_run_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_quantity_event_lot_report FOREIGN KEY (output_lot_id, production_report_id) REFERENCES aps_output_lot (id, source_report_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_quantity_event_reversal_scope FOREIGN KEY (reversal_of_id, output_lot_id, item_id, uom_code) REFERENCES aps_quantity_event (id, output_lot_id, item_id, uom_code) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_quantity_event_type CHECK (event_type IN ('PRODUCE', 'QUALITY_RELEASE', 'RESERVE', 'UNRESERVE', 'CONSUME', 'TRANSFER', 'SCRAP', 'ADJUST', 'REVERSE')),
    CONSTRAINT ck_quantity_event_bucket CHECK ((from_bucket IS NULL OR from_bucket IN ('PENDING_QUALITY', 'AVAILABLE', 'RESERVED', 'CONSUMED', 'TRANSFERRED', 'SCRAPPED', 'ADJUSTMENT')) AND (to_bucket IS NULL OR to_bucket IN ('PENDING_QUALITY', 'AVAILABLE', 'RESERVED', 'CONSUMED', 'TRANSFERRED', 'SCRAPPED', 'ADJUSTMENT')) AND (from_bucket IS NULL OR to_bucket IS NULL OR from_bucket <> to_bucket)),
    CONSTRAINT ck_quantity_event_qty CHECK (quantity > 0),
    CONSTRAINT ck_quantity_event_reversal CHECK ((event_type = 'REVERSE' AND reversal_of_id IS NOT NULL AND reversal_of_id <> id) OR (event_type <> 'REVERSE' AND reversal_of_id IS NULL)),
    CONSTRAINT ck_quantity_event_shape CHECK ((event_type = 'PRODUCE' AND material_demand_id IS NULL AND execution_run_id IS NOT NULL AND production_report_id IS NOT NULL AND target_task_id IS NULL AND from_bucket IS NULL AND to_bucket = 'PENDING_QUALITY') OR (event_type = 'QUALITY_RELEASE' AND material_demand_id IS NULL AND execution_run_id IS NULL AND production_report_id IS NULL AND target_task_id IS NULL AND from_bucket = 'PENDING_QUALITY' AND to_bucket = 'AVAILABLE') OR (event_type = 'RESERVE' AND material_demand_id IS NOT NULL AND execution_run_id IS NULL AND production_report_id IS NULL AND target_task_id IS NOT NULL AND from_bucket = 'AVAILABLE' AND to_bucket = 'RESERVED') OR (event_type = 'UNRESERVE' AND material_demand_id IS NOT NULL AND execution_run_id IS NULL AND production_report_id IS NULL AND target_task_id IS NOT NULL AND from_bucket = 'RESERVED' AND to_bucket = 'AVAILABLE') OR (event_type = 'CONSUME' AND material_demand_id IS NOT NULL AND execution_run_id IS NOT NULL AND production_report_id IS NULL AND target_task_id IS NOT NULL AND from_bucket IN ('AVAILABLE', 'RESERVED') AND to_bucket = 'CONSUMED') OR (event_type = 'TRANSFER' AND material_demand_id IS NOT NULL AND execution_run_id IS NULL AND production_report_id IS NULL AND target_task_id IS NOT NULL AND from_bucket = 'AVAILABLE' AND to_bucket = 'TRANSFERRED') OR (event_type = 'SCRAP' AND material_demand_id IS NULL AND execution_run_id IS NULL AND production_report_id IS NULL AND target_task_id IS NULL AND from_bucket IN ('PENDING_QUALITY', 'AVAILABLE', 'RESERVED') AND to_bucket = 'SCRAPPED') OR (event_type = 'ADJUST' AND material_demand_id IS NULL AND execution_run_id IS NULL AND production_report_id IS NULL AND target_task_id IS NULL AND from_bucket IS NOT NULL AND to_bucket IS NOT NULL AND from_bucket <> to_bucket AND reason IS NOT NULL) OR (event_type = 'REVERSE' AND material_demand_id IS NULL AND execution_run_id IS NULL AND production_report_id IS NULL AND target_task_id IS NULL AND from_bucket IS NOT NULL AND to_bucket IS NOT NULL AND from_bucket <> to_bucket AND reason IS NOT NULL)),
    KEY idx_quantity_event_lot (output_lot_id, item_id, uom_code, occurred_at),
    KEY idx_quantity_event_demand (material_demand_id, target_task_id, item_id, uom_code, occurred_at),
    KEY idx_quantity_event_run (execution_run_id, occurred_at),
    KEY idx_quantity_event_report (production_report_id, execution_run_id, uom_code),
    KEY idx_quantity_event_lot_report (output_lot_id, production_report_id),
    KEY idx_quantity_event_reversal (reversal_of_id, output_lot_id, item_id, uom_code),
    KEY idx_quantity_event_task (target_task_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='M29 不可变数量流水；预留、投入、放行和冲正统一留痕';

-- ============================================================================
-- 需要服务层事务继续保证、不能由单表 CHECK 完成的规则
-- ============================================================================
-- 1. 路线与任务依赖必须无环，且依赖两端属于兼容的路线/订单实例。
-- 2. 工艺 required_skill_code 必须能在 aps_resource_skill 中找到有效且等级足够的资源。
-- 3. 工作中心、资源日历、已发布计划和实际占用在同一时间窗不得超出容量。
-- 4. 共享批成员容量与单位必须兼容；同一设备周期只能计算一次资源占用。
-- 5. 发布必须在事务内复验 input_hash、实际进度和资源日历，并原子切换唯一 current 版本。
-- 6. 报工、产出批投影和 aps_quantity_event 必须同事务写入；更正通过 REVERSE，不删除历史。
-- 7. 任一时点下游累计投入不得超过已放行且分配给该需求的上游数量。
-- 8. RuoYi 操作日志承担配置和人工操作审计；若其字段不能满足现场追责，再单独评审领域事件表。
