(() => {
  'use strict';
  const KEY = 'zhixuan-prototype-v1';
  const U = window.UI;
  const E = text => U.escape(String(text ?? ''));
  const I = name => U.icon(name);
  const money = cents => '¥' + (cents / 100).toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const wholeMoney = cents => '¥' + (cents / 100).toLocaleString('zh-CN', { maximumFractionDigits: 0 });
  const clone = object => JSON.parse(JSON.stringify(object));
  const products = [
    { id:177, sku:'ZX-D2601-BK', name:'黑底花卉长款连衣裙', cat:'连衣裙', color:'黑色', price:36800, stock:126, tags:['都市优雅','宴会','花卉'], status:'已确认' },
    { id:178, sku:'ZX-D2602-RD', name:'红色系带收腰长裙', cat:'连衣裙', color:'红色', price:42800, stock:64, tags:['摩登个性','宴会','系带'], status:'待复核' },
    { id:179, sku:'ZX-D2603-BK', name:'黑色系带收腰长裙', cat:'连衣裙', color:'黑色', price:39800, stock:82, tags:['都市优雅','宴会','修身'], status:'已确认' },
    { id:180, sku:'ZX-D2604-WH', name:'红点收腰无袖连衣裙', cat:'连衣裙', color:'白色', price:32800, stock:108, tags:['复古浪漫','日常','波点'], status:'已确认' },
    { id:181, sku:'ZX-D2605-RD', name:'酒红拼色长袖连衣裙', cat:'连衣裙', color:'红色', price:35800, stock:96, tags:['都市优雅','日常','拼色'], status:'已确认' },
    { id:185, sku:'ZX-S2611-BK', name:'黑色尖头浅口平底鞋', cat:'鞋履', color:'黑色', price:15800, stock:82, tags:['简约休闲','日常','平底'], status:'已确认' },
    { id:186, sku:'ZX-S2612-BK', name:'黑色双带露趾高跟鞋', cat:'鞋履', color:'黑色', price:22800, stock:124, tags:['都市优雅','宴会','露趾'], status:'已确认' },
    { id:187, sku:'ZX-S2613-GD', name:'金色细跟礼鞋', cat:'鞋履', color:'金色', price:24800, stock:76, tags:['复古浪漫','宴会','金属色'], status:'已确认' },
    { id:188, sku:'ZX-S2614-BK', name:'黑色尖头高跟鞋', cat:'鞋履', color:'黑色', price:19800, stock:96, tags:['都市优雅','日常','尖头'], status:'已确认' },
    { id:189, sku:'ZX-S2615-RD', name:'红色漆皮高跟鞋', cat:'鞋履', color:'红色', price:23800, stock:18, tags:['复古浪漫','宴会','漆皮'], status:'待复核' },
    { id:172, sku:'ZX-B2621-BL', name:'宝蓝色双提手包', cat:'包袋', color:'蓝色', price:18800, stock:118, tags:['都市优雅','日常','手提'], status:'已确认' },
    { id:173, sku:'ZX-B2622-BR', name:'棕色皮质肩包', cat:'包袋', color:'棕色', price:21800, stock:88, tags:['简约休闲','日常','肩背'], status:'已确认' },
    { id:174, sku:'ZX-B2623-BL', name:'浅蓝色结构感手提包', cat:'包袋', color:'蓝色', price:19800, stock:110, tags:['复古浪漫','日常','手提'], status:'已确认' },
    { id:175, sku:'ZX-B2624-WH', name:'白色简约双肩包', cat:'包袋', color:'白色', price:16800, stock:140, tags:['简约休闲','日常','双肩'], status:'已确认' },
    { id:176, sku:'ZX-B2625-BK', name:'黑色结构感手提包', cat:'包袋', color:'黑色', price:20800, stock:132, tags:['都市优雅','宴会','手提'], status:'已确认' }
  ];
  const initialLooks = [
    { name:'花间序曲', mood:'FLORAL STORY / 都市优雅', ids:[177,186,176], locks:[], selected:true, reason:'以黑底花卉长裙为视觉中心，露趾鞋与结构感包袋统一色调，保留利落线条。' },
    { name:'周末来信', mood:'SOFT CONTRAST / 复古浪漫', ids:[180,187,174], locks:[], selected:false, reason:'红色波点与浅蓝包袋形成清爽对比，金色鞋履补充亮点，适合轻社交场景。' },
    { name:'城市漫游', mood:'COLOR STORY / 拼色日常', ids:[181,188,172], locks:[], selected:false, reason:'以酒红拼色裙为视觉中心，黑色尖头鞋延伸比例，宝蓝包袋增加色彩层次。' }
  ];
  const defaults = {
    brief:{client:'澜序精品集合店', name:'2026 秋季 · 城市优雅系列', scene:'品牌秋季订货', style:'都市优雅', budget:980, qty:30, date:'2026-10-15', exclude:'', text:'为秋季门店选品做 3 套城市感女装搭配，适合 25–40 岁女性。每套预算 980 元，每款 30 套，连衣裙、鞋履和包袋完整搭配。', confirmed:true},
    looks:clone(initialLooks), edits:{}, quoteRows:null, quote:{discount:95,fee:300,tax:13,validUntil:'2026-09-30',note:'现货销售；报价有效期内价格保留，库存以订单确认时为准。'}, snapshots:[], history:[], customers:[
      {name:'澜序精品集合店',person:'林薇',city:'杭州',type:'品牌买手店',email:'linwei@example.com',note:'偏好都市优雅；以现货选品为主，秋季补货频率每月 2 次。'},
      {name:'泊岸生活百货',person:'陈悦',city:'上海',type:'零售集合店',email:'chenyue@example.com',note:'偏好简约休闲及基础色，小批量、多频次补货。'},
      {name:'榆见服饰',person:'周晴',city:'苏州',type:'区域经销商',email:'zhouqing@example.com',note:'关注商品组合毛利与交期，优先选择库存充足的基础款。'}
    ]
  };
  let state = U.load(KEY, defaults);
  if (!state || !state.brief || !state.looks || !state.customers) state = clone(defaults);
  let route = '', catalogQuery = '', catalogCat = '全部品类', catalogStatus = '全部状态', customerQuery = '', projectQuery = '', selectedVersion = null;
  const save = () => U.save(KEY, state);
  const getProduct = id => ({...products.find(p => p.id === Number(id)), ...(state.edits[id] || {})});
  const allProducts = () => products.map(p => getProduct(p.id));
  const photo = (p, cls = '') => `<img class="${cls}" src="assets/product-${p.id}.webp" alt="${E(p.name)}" loading="lazy">`;
  const button = (text, icon, cls, attrs='') => `<button class="btn ${cls || 'secondary'}" ${attrs}>${icon ? I(icon) : ''}${text}</button>`;
  const iconButton = (icon,title,attrs='',cls='') => `<button class="btn icon-btn ghost ${cls}" title="${E(title)}" aria-label="${E(title)}" ${attrs}>${I(icon)}</button>`;
  const go = target => { if(location.hash === '#' + target) render(); else location.hash = target; };
  const heading = (title, subtitle, actions='') => `<div class="page-heading"><div><h1 class="page-title">${title}</h1><p class="page-description">${subtitle}</p></div><div class="actions">${actions}</div></div>`;
  const empty = (title,text,action='') => `<div class="empty-state">${I('package-search')}<h3>${title}</h3><p>${text}</p>${action}</div>`;
  const field = (label,name,value,type='text',attrs='') => `<label class="field"><span class="field-label">${label}</span><input class="input" name="${name}" type="${type}" value="${E(value)}" ${attrs}></label>`;
  function shell() {
    const nav = [ ['workbench','方案工作台','panels-top-left'],['projects','全部方案','layers-3'],['brief','客户需求','notebook-pen'],['catalog','商品库与标签','shirt'],['quotes','报价与版本','receipt-text'],['delivery','交付预览','presentation'],['customers','客户档案','users-round'] ];
    document.getElementById('app').innerHTML = `<div class="app-shell"><aside class="sidebar"><a href="#workbench" class="brand"><span class="brand-mark fashion-mark">${I('swatch-book')}</span><span><span class="brand-name">织选 <span style="font-size:11px;font-weight:400">STUDIO</span></span><span class="brand-note">AI 搭配与报价</span></span></a><div class="nav-group"><div class="nav-label">销售工作空间</div>${nav.map(([id,label,icon])=>`<a href="#${id}" class="nav-item ${route===id?'active':''}">${I(icon)}<span>${label}</span>${id==='projects'?'<span class="nav-count">'+(state.history.length+1)+'</span>':''}</a>`).join('')}</div><div class="sidebar-footer"><a class="nav-item" href="../index.html">${I('arrow-left')}<span>返回原型总览</span></a><div class="client-row" style="padding:16px 8px 0"><span class="avatar fashion-avatar">林</span><span><strong style="font-size:12px">林亦 / 销售顾问</strong><small style="display:block;color:#879189;font-size:10px;margin-top:4px">织选品牌工作室</small></span></div></div></aside><div class="workspace"><header class="topbar"><div class="topbar-left">${iconButton('menu','打开导航','data-toggle-nav','mobile-menu')}<span class="breadcrumb">销售工作空间 <span class="muted">/</span> ${nav.find(n=>n[0]===route)?.[1]||'方案工作台'}</span></div><div class="topbar-right"><span class="context-badge"><span class="green-dot"></span>商品目录 · 15 款</span><span class="prototype-label">交互原型 · 示例数据</span><span class="avatar fashion-avatar">林</span></div></header><main class="content" id="main" tabindex="-1"></main></div></div>`;
    document.querySelector('a[href="../index.html"]').target='_top';
  }
  function render(){
    route = location.hash.slice(1).split('?')[0] || 'workbench';
    if(!['workbench','projects','brief','catalog','quotes','delivery','customers'].includes(route)) route='workbench';
    document.body.classList.remove('invalid-quote');
    shell();
    const pages={workbench:workbenchPage,projects:projectsPage,brief:briefPage,catalog:catalogPage,quotes:quotesPage,delivery:deliveryPage,customers:customersPage};
    pages[route]();
    if(route==='delivery')guardDelivery();
    U.icons();
  }
  const main = html => document.getElementById('main').innerHTML=html;
  const lookTotal = look => look.ids.reduce((sum,id)=>sum+getProduct(id).price,0);
  const selectedLooks = () => state.looks.filter(l=>l.selected);
  const excluded = p => state.brief.exclude.trim() && state.brief.exclude.split(/[，,、\s]+/).filter(Boolean).some(word=>[p.name,p.color,p.cat,...p.tags].join(' ').includes(word));
  const eligible = p => p.stock >= state.brief.qty && p.status==='已确认' && !excluded(p);
  const combinationReason = ids => `以${getProduct(ids[0]).name}为主体，搭配${getProduct(ids[1]).name}与${getProduct(ids[2]).name}；商品均满足当前预算和采购数量。`;
  function workbenchPage(){
    const b=state.brief, selected=selectedLooks(), sum=selected.reduce((s,l)=>s+lookTotal(l)*b.qty,0);
    main(heading('方案工作台',`${E(b.name)} <span class="muted">·</span> 方案 ZX-202609-018`,button('编辑需求','sliders-horizontal','secondary','data-go="brief"')+button('新建方案','plus','primary','id="new-project"'))+
      `<div class="steps-strip"><span><i class="step-num">1</i><b>确认需求</b></span>${I('chevron-right')}<span class="current"><i class="step-num">2</i><b>搭配选品</b></span>${I('chevron-right')}<span><i class="step-num">3</i><b>编辑报价</b></span>${I('chevron-right')}<span><i class="step-num">4</i><b>方案交付</b></span></div>
      <div class="brief-strip"><div class="brief-main"><span class="client-emblem">澜</span><div><div class="brief-title">${E(b.client)}</div><div class="brief-sub">${E(b.scene)} · ${E(b.style)}</div></div></div><div><div class="eyebrow">每套商品预算</div><div class="brief-value">${wholeMoney(b.budget*100)} <span class="muted" style="font-size:11px;font-weight:400">/ 套</span></div></div><div><div class="eyebrow">选定 Look 订购量</div><div class="brief-value">${b.qty} <span class="muted" style="font-size:11px;font-weight:400">套 / Look</span></div></div><div class="brief-date"><div class="eyebrow">期望交付</div><div class="brief-value">${E(b.date)}</div></div><div class="brief-edit"><span class="badge success">${I('check')} 需求已确认</span></div></div>
      <div class="work-tabs"><div class="section-heading"><h2 style="margin:0;font-size:16px">搭配候选 <span class="subtle-count">/ ${state.looks.length} 套</span></h2></div><div class="actions"><span class="subtle-count">单品价格与库存已关联</span>${button('重新搭配','refresh-cw','secondary','id="remix-all"')}</div></div>
      <div class="looks-grid">${state.looks.map((l,n)=>lookCard(l,n)).join('')}</div>
      ${!state.looks.length?empty('暂无满足条件的组合','请调整预算、数量或排除项，保留足够的可售商品。',button('调整需求','sliders-horizontal','primary','data-go="brief"')):''}
      <div class="selection-bar"><div class="selection-main"><span class="selection-icon">${I('check-check')}</span><div><strong>已选择 ${selected.length} 套搭配</strong><p>${selected.length*b.qty} 套商品组合 · 折扣、税费在报价中计算</p></div></div><div class="selection-total"><strong>${money(sum)}</strong>${button('生成报价','arrow-right','primary',`id="open-quote" ${!selected.length?'disabled':''}`)}</div></div>
      <div class="note-band"><span>${I('package-check')}商品库存更新于 2026-09-10 09:30</span><span>${I('clock-3')}方案已保存到本地</span></div>`);
    bindGo();
    if(!b.confirmed){const badge=document.querySelector('.brief-edit .badge');badge.className='badge warning';badge.textContent='需求待确认';}
    document.getElementById('new-project').onclick=newProject;
    document.getElementById('remix-all').onclick=()=>remix();
    document.getElementById('open-quote').onclick=()=>{ensureRows();go('quotes');};
    document.querySelectorAll('[data-select-look]').forEach(el=>el.onchange=()=>{state.looks[el.dataset.selectLook].selected=el.checked;state.quoteRows=null;save();render();});
    document.querySelectorAll('[data-lock]').forEach(el=>el.onclick=()=>{const[n,slot]=el.dataset.lock.split('-').map(Number),l=state.looks[n];l.locks=l.locks.includes(slot)?l.locks.filter(i=>i!==slot):[...l.locks,slot];save();render();});
    document.querySelectorAll('[data-replace]').forEach(el=>el.onclick=()=>{const[n,slot]=el.dataset.replace.split('-').map(Number);replaceModal(n,slot);});
    document.querySelectorAll('[data-remix]').forEach(el=>el.onclick=()=>remix(Number(el.dataset.remix)));
    document.querySelectorAll('[data-look-detail]').forEach(el=>el.onclick=()=>lookDetail(Number(el.dataset.lookDetail)));
  }
  function lookCard(l,n){
    const total=lookTotal(l),invalid=total>state.brief.budget*100 || l.ids.some(id=>!eligible(getProduct(id)));
    return `<article class="look-card ${l.selected?'selected':''}"><div class="look-top"><span class="look-kicker">LOOK 0${n+1}</span><label class="look-select"><input type="checkbox" data-select-look="${n}" ${l.selected?'checked':''}>纳入报价</label></div><h3 class="look-title">${E(l.name)}</h3><p class="look-mood">${E(l.mood)}</p><div class="look-board">${l.ids.map((id,s)=>`<button class="look-product" data-replace="${n}-${s}" title="查看并替换${E(getProduct(id).name)}">${photo(getProduct(id))}${l.locks.includes(s)?`<span class="lock-marker">${I('lock-keyhole')}</span>`:''}</button>`).join('')}</div><div class="look-price">${wholeMoney(total)}<small>/ 套</small><span class="badge ${invalid?'warning':'success'}">${invalid?'待调整':'预算内 · 库存充足'}</span></div><p class="look-explanation">${E(l.reason)}</p><div class="look-items">${l.ids.map((id,s)=>{const p=getProduct(id);return `<div class="look-item"><span class="look-item-name">${E(p.name)}<small>${p.sku} · 可售 ${p.stock}</small></span><span class="look-item-price">${wholeMoney(p.price)}</span>${iconButton(l.locks.includes(s)?'lock-keyhole':'lock-keyhole-open',l.locks.includes(s)?'解锁单品':'锁定单品',`data-lock="${n}-${s}"`,l.locks.includes(s)?'locked':'')}${iconButton('replace','替换单品',`data-replace="${n}-${s}"`)}</div>`;}).join('')}</div><div class="look-footer">${button('重搭未锁定单品','refresh-cw','ghost',`data-remix="${n}"`)}${button('搭配详情','arrow-up-right','ghost',`data-look-detail="${n}"`)}</div></article>`;
  }
  function bindGo(){document.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>go(el.dataset.go));}
  function invalidate(){state.quoteRows=null;save();}
  function bestCombination(look,seed=0){
    const categories=['连衣裙','鞋履','包袋'];
    const options=categories.map((cat,slot)=>look?.locks.includes(slot)?[getProduct(look.ids[slot])]:allProducts().filter(p=>p.cat===cat&&eligible(p)));
    const combos=[];
    for(const a of options[0])for(const b of options[1])for(const c of options[2]){
      if(a.price+b.price+c.price<=state.brief.budget*100&&[a,b,c].every(eligible))combos.push([a.id,b.id,c.id]);
    }
    if(!combos.length)return null;
    const different=combos.filter(ids=>!look||ids.join()!==look.ids.join());
    const pool=different.length?different:combos;
    const score=ids=>{const parts=ids.map(getProduct),styleMatches=parts.filter(p=>p.tags.includes(state.brief.style)).length;const neutrals=parts.filter(p=>['黑色','白色'].includes(p.color)).length;const uniqueColors=new Set(parts.map(p=>p.color)).size;return styleMatches*10+neutrals*2+(uniqueColors<=2?3:0);};
    pool.sort((a,b)=>score(b)-score(a)||a.join().localeCompare(b.join()));
    return pool[seed%Math.min(8,pool.length)];
  }
  function remix(index){
    const indices=index===undefined?state.looks.map((_,i)=>i):[index];let changed=0,blocked=0;
    indices.forEach(i=>{const l=state.looks[i];if(l.locks.length===3){blocked++;return;}const ids=bestCombination(l,Date.now()%97+i*13);if(ids&&ids.join()!==l.ids.join()){l.ids=ids;l.reason=combinationReason(ids);changed++;}else blocked++;});
    invalidate();render();
    if(blocked)U.modal('重搭结果',`<p class="muted-paragraph">已更新 ${changed} 套；${blocked} 套没有可替换的有效组合。请解锁单品，或调整预算、数量与排除项。</p>`,button('关闭','','primary','id="close-remix"'));
    document.getElementById('close-remix')?.addEventListener('click',U.closeModal);
  }
  function replaceModal(n,slot){
    const l=state.looks[n],current=getProduct(l.ids[slot]);
    if(l.locks.includes(slot)){U.modal('此单品已锁定',`<p class="muted-paragraph">${E(current.name)} 将保留在当前搭配中。解锁后可以替换。</p>`,button('保留锁定','','secondary','id="keep-lock"')+button('解锁并替换','lock-keyhole-open','primary','id="unlock-replace"'));document.getElementById('keep-lock').onclick=U.closeModal;document.getElementById('unlock-replace').onclick=()=>{l.locks=l.locks.filter(s=>s!==slot);save();U.closeModal();render();replaceModal(n,slot);};return;}
    const pool=allProducts().filter(p=>p.cat===current.cat&&p.id!==current.id);
    U.modal('替换'+current.cat,`<p class="modal-subtitle">${E(l.name)} · 当前 ${E(current.name)} / ${wholeMoney(current.price)}</p><div class="replace-grid">${pool.map(p=>{let reason='';if(p.status!=='已确认')reason='商品标签待复核';else if(p.stock<state.brief.qty)reason='库存不足 '+state.brief.qty+' 件';else if(excluded(p))reason='不符合排除条件';else if(lookTotal(l)-current.price+p.price>state.brief.budget*100)reason='替换后超出每套预算';return `<button class="replace-option" data-pick="${p.id}" ${reason?'disabled':''}>${photo(p)}<strong>${E(p.name)}</strong><p>${wholeMoney(p.price)} · 库存 ${p.stock}</p><span class="badge ${reason?'warning':'success'}">${reason||'符合预算与库存'}</span></button>`;}).join('')}</div>`,button('取消','','secondary','id="cancel-replace"'));
    document.getElementById('cancel-replace').onclick=U.closeModal;
    document.querySelectorAll('[data-pick]').forEach(el=>el.onclick=()=>{l.ids[slot]=Number(el.dataset.pick);l.reason='单品已人工替换；预算、可售库存与排除条件已重新校验。';invalidate();U.closeModal();render();});
  }
  function lookDetail(n){const l=state.looks[n];U.drawer(l.name,`<div class="tag-row mb15"><span class="tag pink">${E(state.brief.style)}</span><span class="tag blue">${E(state.brief.scene)}</span></div><p class="muted-paragraph">${E(l.reason)}</p><div class="mini-board">${l.ids.map(id=>photo(getProduct(id))).join('')}</div><dl class="definition-list mt20"><dt>每套商品合计</dt><dd>${money(lookTotal(l))}</dd><dt>预算余量</dt><dd>${money(state.brief.budget*100-lookTotal(l))}</dd><dt>单品数量</dt><dd>${l.ids.length} 件</dd><dt>锁定单品</dt><dd>${l.locks.length} 件</dd><dt>采购数量</dt><dd>${state.brief.qty} 套</dd></dl><label class="field mt20"><span class="field-label">方案标题</span><input class="input" id="look-name" maxlength="40" value="${E(l.name)}"></label><label class="field mt20"><span class="field-label">搭配说明</span><textarea class="input" id="look-reason">${E(l.reason)}</textarea></label><p id="look-error" class="inline-error"></p>`,button('保存修改','check','primary','id="save-look"'));document.getElementById('save-look').onclick=()=>{const name=document.getElementById('look-name').value.trim(),reason=document.getElementById('look-reason').value.trim();if(!name||!reason){document.getElementById('look-error').textContent='请填写方案标题和搭配说明。';return;}l.name=name;l.reason=reason;save();U.closeDrawer();render();};}
  function newProject(){
    U.modal('新建搭配方案','<p class="muted-paragraph">当前方案会保留在「全部方案」中，新方案从客户需求开始。</p>'+field('方案名称','newName','','text','id="new-name" placeholder="例如：冬季门店补货方案" maxlength="60"')+'<p id="new-error" class="inline-error"></p>',button('取消','','secondary','id="new-cancel"')+button('创建方案','plus','primary','id="new-confirm"'));
    document.getElementById('new-cancel').onclick=U.closeModal;
    document.getElementById('new-confirm').onclick=()=>{const name=document.getElementById('new-name').value.trim();if(!name){document.getElementById('new-error').textContent='请填写方案名称。';return;}state.history.push({id:Date.now(),brief:clone(state.brief),looks:clone(state.looks),quoteRows:clone(state.quoteRows),quote:clone(state.quote),date:new Date().toLocaleDateString('zh-CN')});state.brief={...state.brief,name,confirmed:false};state.looks=[];state.quoteRows=null;save();U.closeModal();go('brief');};
  }
  function briefPage(){const b=state.brief;
    main(heading('客户需求',E(b.name),button('返回工作台','arrow-left','secondary','data-go="workbench"'))+`<div class="brief-layout"><form id="brief-form" class="brief-form"><section class="form-section"><h2>需求简报</h2><label class="field"><span class="field-label">客户原始需求</span><textarea class="input" name="text" rows="4">${E(b.text)}</textarea></label><div class="form-actions">${button('提取预算与数量','scan-text','secondary','type="button" id="parse-brief"')}</div></section><section class="form-section"><h2>采购条件</h2><div class="form-grid"><label class="field"><span class="field-label">客户</span><select class="input" name="client">${state.customers.map(c=>`<option ${b.client===c.name?'selected':''}>${E(c.name)}</option>`).join('')}</select></label>${field('方案名称 *','name',b.name,'text','required maxlength="60"')}${field('每套商品预算（元）*','budget',b.budget,'number','min="1" max="100000" step="0.01" required')}${field('选定 Look 采购数量（套）*','qty',b.qty,'number','min="1" max="10000" step="1" required')}<label class="field"><span class="field-label">采购场景</span><select class="input" name="scene">${['品牌秋季订货','门店季度补货','礼服专场选品'].map(s=>`<option ${s===b.scene?'selected':''}>${s}</option>`).join('')}</select></label><label class="field"><span class="field-label">风格偏好</span><select class="input" name="style">${['都市优雅','复古浪漫','简约休闲','摩登个性'].map(s=>`<option ${s===b.style?'selected':''}>${s}</option>`).join('')}</select></label>${field('期望交付日期 *','date',b.date,'date','required')}${field('排除项','exclude',b.exclude,'text','placeholder="如：红色、波点"')}<div class="wide callout">每套商品预算用于搭配筛选，不含运输费和税费；数量按每个选定 Look 计算。</div></div><p class="inline-error" id="brief-error" role="alert"></p><div class="form-actions">${button('保存需求','save','secondary','type="button" id="save-brief"')}${button('确认条件并生成搭配','sparkles','primary','type="submit"')}</div></section></form><aside class="brief-aside"><h3>当前商品池</h3><dl class="definition-list"><dt>商品总数</dt><dd>15 款</dd><dt>已确认标签</dt><dd>${allProducts().filter(p=>p.status==='已确认').length} 款</dd><dt>包含品类</dt><dd>连衣裙 / 鞋履 / 包袋</dd><dt>采购方式</dt><dd>现货销售</dd></dl><div class="callout"><strong>组合范围</strong><br>每套由 1 件连衣裙、1 双鞋履与 1 个包袋组成。</div><h3 class="mt20">最近确认</h3><p class="muted-paragraph">${b.confirmed?'需求已确认，可继续编辑商品组合。':'需求待确认，确认后生成首批搭配。'}</p></aside></div>`);
    bindGo(); const form=document.getElementById('brief-form');
    document.getElementById('parse-brief').onclick=()=>{const text=form.elements.text.value,budget=text.match(/(?:预算|每套)\s*(\d+(?:\.\d+)?)\s*元?/),qty=text.match(/(?:每款|每套|数量|采购)\s*(\d+)\s*套/);if(budget)form.elements.budget.value=budget[1];if(qty)form.elements.qty.value=qty[1];document.getElementById('brief-error').textContent=budget||qty?'已提取可识别的金额和套数，请核对采购条件后确认。':'未识别到明确金额或套数，请直接填写采购条件。';};
    const read=()=>{const data=new FormData(form),next=Object.fromEntries(data);next.budget=Number(next.budget);next.qty=Number(next.qty);if(!form.reportValidity())return null;if(!Number.isInteger(next.qty)||next.qty<1||next.budget<=0||!next.name.trim()){document.getElementById('brief-error').textContent='请填写有效名称、正数预算和整数采购套数。';return null;}return next;};
    document.getElementById('save-brief').onclick=()=>{const next=read();if(!next)return;state.brief={...next,confirmed:false};state.looks=[];invalidate();document.getElementById('brief-error').textContent='需求草稿已保存。请确认条件并生成搭配。';};
    form.onsubmit=event=>{event.preventDefault();const next=read();if(!next)return;state.brief={...next,confirmed:true};const combos=[];initialLooks.forEach((l,n)=>{const retain=next.style==='都市优雅'&&l.ids.every(id=>eligible(getProduct(id)))&&lookTotal(l)<=next.budget*100;const ids=retain?[...l.ids]:bestCombination(null,n*3);if(ids&&!combos.some(x=>x.ids.join()===ids.join()))combos.push({...clone(l),ids,reason:retain?l.reason:combinationReason(ids),selected:combos.length===0,locks:[]});});state.looks=combos;invalidate();go('workbench');};
  }
  function catalogPage(){main(heading('商品库与标签','2026 品牌现货目录 · 图片、价格与可售库存',button('导出商品表','download','secondary','id="export-products"'))+`<div class="filter-row"><label class="search-field">${I('search')}<input class="input" id="catalog-search" placeholder="搜索商品名称、SKU 或标签" value="${E(catalogQuery)}" aria-label="搜索商品"></label><select class="input" id="catalog-category" aria-label="品类筛选">${['全部品类','连衣裙','鞋履','包袋'].map(c=>`<option ${c===catalogCat?'selected':''}>${c}</option>`).join('')}</select><select class="input" id="catalog-status" aria-label="商品状态筛选">${['全部状态','已确认','待复核'].map(c=>`<option ${c===catalogStatus?'selected':''}>${c}</option>`).join('')}</select><span class="catalog-count" id="catalog-count"></span></div><div id="catalog-results"></div>`);
    const update=()=>{const list=allProducts().filter(p=>(catalogCat==='全部品类'||p.cat===catalogCat)&&(catalogStatus==='全部状态'||p.status===catalogStatus)&&[p.name,p.sku,p.color,...p.tags].join(' ').toLowerCase().includes(catalogQuery.toLowerCase()));document.getElementById('catalog-count').textContent='共 '+list.length+' 款商品';document.getElementById('catalog-results').innerHTML=list.length?`<div class="catalog-grid">${list.map(p=>`<button class="catalog-card" data-product="${p.id}">${p.status==='待复核'?'<span class="stock-marker badge warning">标签待复核</span>':''}<div class="catalog-image">${photo(p)}</div><div class="catalog-details"><h3>${E(p.name)}</h3><p>${p.sku}</p><footer><strong>${wholeMoney(p.price)}</strong><span class="${p.stock<30?'price-green':'muted'}">可售 ${p.stock}</span></footer></div></button>`).join('')}</div>`:empty('没有符合条件的商品','试试其他名称、SKU 或筛选条件。',button('清空筛选','rotate-ccw','secondary','id="clear-catalog"'));document.querySelectorAll('[data-product]').forEach(el=>el.onclick=()=>productDrawer(Number(el.dataset.product)));document.getElementById('clear-catalog')?.addEventListener('click',()=>{catalogQuery='';catalogCat='全部品类';catalogStatus='全部状态';render();});U.icons();};
    document.getElementById('catalog-search').oninput=event=>{catalogQuery=event.target.value;update();};document.getElementById('catalog-category').onchange=event=>{catalogCat=event.target.value;update();};document.getElementById('catalog-status').onchange=event=>{catalogStatus=event.target.value;update();};document.getElementById('export-products').onclick=()=>downloadCSV('织选商品目录.csv',[['SKU','商品名称','品类','颜色','销售价','可售库存','标签状态','标签'],...allProducts().map(p=>[p.sku,p.name,p.cat,p.color,p.price/100,p.stock,p.status,p.tags.join('、')])]);update();
  }
  function productDrawer(id){const p=getProduct(id);U.drawer('商品详情与标签',`${photo(p,'drawer-product-image')}<div class="product-facts"><span class="eyebrow">${p.sku}</span><h3>${E(p.name)}</h3><span class="badge ${p.status==='已确认'?'success':'warning'}">${p.status}</span></div><dl class="definition-list"><dt>销售单价</dt><dd>${money(p.price)}</dd><dt>可售库存</dt><dd>${p.stock} 件</dd><dt>品类</dt><dd>${p.cat}</dd><dt>颜色</dt><dd>${p.color}</dd></dl><label class="field mt20"><span class="field-label">商品标签（逗号分隔）</span><input id="product-tags" class="input" value="${E(p.tags.join('，'))}"></label><label class="field mt20"><span class="field-label">标签状态</span><select class="input" id="product-status"><option ${p.status==='已确认'?'selected':''}>已确认</option><option ${p.status==='待复核'?'selected':''}>待复核</option></select></label><p class="inline-error" id="product-error"></p>`,button('保存标签','check','primary','id="save-product"'));document.getElementById('save-product').onclick=()=>{const tags=document.getElementById('product-tags').value.split(/[,，、]/).map(t=>t.trim()).filter(Boolean);if(!tags.length){document.getElementById('product-error').textContent='至少保留一个商品标签。';return;}state.edits[id]={...state.edits[id],tags,status:document.getElementById('product-status').value};save();U.closeDrawer();render();};}
  function ensureRows(){if(state.quoteRows!==null)return;const counts={};selectedLooks().forEach(l=>l.ids.forEach(id=>counts[id]=(counts[id]||0)+state.brief.qty));state.quoteRows=Object.entries(counts).map(([id,qty])=>({id:Number(id),qty}));save();}
  function calculate(){ensureRows();const rows=state.quoteRows.map(row=>{const p=getProduct(row.id);const base=p.price*row.qty;const discounted=Math.round(base*Math.round(Number(state.quote.discount)*100)/10000);return {...row,...p,base,discounted};});const base=rows.reduce((s,r)=>s+r.base,0),net=rows.reduce((s,r)=>s+r.discounted,0),fee=Math.round(Number(state.quote.fee)*100),tax=Math.round((net+fee)*Math.round(Number(state.quote.tax)*100)/10000);return {rows,base,discount:base-net,net,fee,tax,total:net+fee+tax};}
  function quoteErrors(calc){const errors=[];if(!calc.rows.length)errors.push('请先选择至少一套搭配。');if(!Number.isFinite(Number(state.quote.discount))||state.quote.discount<1||state.quote.discount>100)errors.push('成交系数应为 1 至 100%。');if(!Number.isFinite(Number(state.quote.fee))||state.quote.fee<0)errors.push('运输与包装费必须是非负金额。');if(!Number.isFinite(Number(state.quote.tax))||state.quote.tax<0||state.quote.tax>100)errors.push('税率应为 0 至 100%。');calc.rows.forEach(r=>{if(!Number.isInteger(r.qty)||r.qty<1)errors.push(r.name+'：数量必须是正整数。');else if(r.qty>r.stock)errors.push(r.name+'：订购 '+r.qty+'，超出可售库存 '+r.stock+'。');if(r.status!=='已确认')errors.push(r.name+'：商品标签尚未复核。');if(excluded(r))errors.push(r.name+'：不符合客户排除条件。');});selectedLooks().forEach(l=>{if(lookTotal(l)>state.brief.budget*100)errors.push(l.name+'：商品合计超过每套预算。');});if(!state.quote.validUntil)errors.push('请设置报价有效期。');else if(state.quote.validUntil<'2026-09-10')errors.push('报价有效期不能早于示例业务日期 2026-09-10。');if(!state.brief.confirmed)errors.push('客户采购条件尚未确认。');return errors;}
  function quoteSummary(c){return `<div class="money-line"><span>商品原价合计</span><strong>${money(c.base)}</strong></div><div class="money-line"><span>折扣减免</span><strong>− ${money(c.discount)}</strong></div><div class="money-line"><span>商品成交金额</span><strong>${money(c.net)}</strong></div><div class="money-line"><span>运输与包装</span><strong>${money(c.fee)}</strong></div><div class="money-line"><span>税额（${E(state.quote.tax)}%）</span><strong>${money(c.tax)}</strong></div><div class="money-line total"><span>报价总额</span><strong>${money(c.total)}</strong></div>`;}
  function quotesPage(){ensureRows();const c=calculate();main(heading('报价编辑',`${E(state.brief.client)} · ${E(state.brief.name)}`,button('返回搭配','arrow-left','secondary','data-go="workbench"'))+`<div class="quote-layout"><div class="quote-main"><div class="quote-meta"><div class="field"><span class="field-label">客户</span><div class="input">${E(state.brief.client)}</div></div><div class="field"><span class="field-label">价格类型</span><div class="input">客户销售价</div></div><label class="field"><span class="field-label">报价有效期</span><input type="date" class="input" id="quote-valid" value="${E(state.quote.validUntil)}"></label></div><div class="table-wrap"><table class="quote-table"><thead><tr><th>商品 / SKU</th><th>单价</th><th>数量</th><th>可售</th><th>成交小计</th></tr></thead><tbody>${c.rows.map(r=>`<tr><td><div class="quote-product">${photo(r)}<span>${E(r.name)}<small>${r.sku}</small></span></div></td><td>${money(r.price)}</td><td><input class="input" type="number" min="1" max="10000" step="1" data-row-qty="${r.id}" value="${r.qty}" aria-label="${E(r.name)}数量"></td><td>${r.stock}</td><td id="row-total-${r.id}">${money(r.discounted)}</td></tr>`).join('')}</tbody></table></div>${!c.rows.length?empty('还没有报价商品','在方案工作台选择搭配后生成报价。',button('选择搭配','arrow-left','primary','data-go="workbench"')):''}<div id="quote-errors" role="alert"></div><label class="field mt20"><span class="field-label">商务备注</span><textarea id="quote-note" class="input">${E(state.quote.note)}</textarea></label><div class="quote-history"><h2>报价版本 <span class="muted">/ ${state.snapshots.length}</span></h2>${state.snapshots.length?state.snapshots.slice().reverse().map(s=>`<div class="version-row"><div><strong>${E(s.id)} · ${E(s.brief.client)}</strong><small>${E(s.created)} · ${s.rows.length} 个 SKU · 已保存</small></div><strong>${money(s.total)}</strong>${button('查看','eye','ghost',`data-version="${s.id}"`)}</div>`).join(''):'<p class="muted-paragraph">暂无历史版本。保存报价后，商品价格与商务条款将保留为独立版本。</p>'}</div></div><aside class="quote-summary"><h2>价格与费用</h2><label class="field"><span class="field-label">成交系数（%）</span><input class="input" id="quote-discount" type="number" min="1" max="100" step="0.01" value="${state.quote.discount}"></label><label class="field"><span class="field-label">运输与包装费（元）</span><input class="input" id="quote-fee" type="number" min="0" step="0.01" value="${state.quote.fee}"></label><label class="field"><span class="field-label">税率（%）</span><select class="input" id="quote-tax">${[0,6,9,13].map(n=>`<option value="${n}" ${Number(state.quote.tax)===n?'selected':''}>${n}%</option>`).join('')}</select></label><div id="quote-totals" class="mt20">${quoteSummary(c)}</div>${button('保存报价版本','save','primary','id="save-quote"')}${button('预览当前报价','eye','secondary','id="preview-draft"')}${button('导出报价明细','download','ghost','id="export-quote"')}<p class="muted-paragraph">税额按商品成交金额与运输包装费合计计算，逐行折扣金额保留两位小数。</p></aside></div>`);bindGo();
    const refresh=()=>{const calc=calculate();document.getElementById('quote-totals').innerHTML=quoteSummary(calc);calc.rows.forEach(r=>document.getElementById('row-total-'+r.id).textContent=money(r.discounted));const errors=quoteErrors(calc);document.getElementById('quote-errors').innerHTML=errors.length?'<div class="callout danger">'+errors.map(E).join('<br>')+'</div>':'';document.getElementById('save-quote').disabled=errors.length>0;document.getElementById('export-quote').disabled=errors.length>0;document.getElementById('preview-draft').disabled=errors.length>0;save();};
    document.querySelectorAll('[data-row-qty]').forEach(el=>el.oninput=()=>{state.quoteRows.find(r=>r.id===Number(el.dataset.rowQty)).qty=Number(el.value);refresh();});
    ['discount','fee','tax'].forEach(key=>document.getElementById('quote-'+key).oninput=event=>{state.quote[key]=Number(event.target.value);refresh();});
    document.getElementById('quote-valid').onchange=event=>{state.quote.validUntil=event.target.value;refresh();};document.getElementById('quote-note').oninput=event=>{state.quote.note=event.target.value;save();};
    document.getElementById('save-quote').onclick=()=>{const calc=calculate();if(quoteErrors(calc).length){refresh();return;}const snapshot={...clone(calc),id:'BQ-260910-V'+String(state.snapshots.length+1).padStart(2,'0'),brief:clone(state.brief),looks:clone(selectedLooks()),quote:clone(state.quote),created:new Date().toLocaleString('zh-CN')};state.snapshots.push(snapshot);save();selectedVersion=snapshot.id;go('delivery');};
    document.getElementById('preview-draft').onclick=()=>{selectedVersion='draft';go('delivery');};document.getElementById('export-quote').onclick=()=>exportQuote({...calculate(),brief:state.brief,quote:state.quote,id:'草稿'});
    document.querySelectorAll('[data-version]').forEach(el=>el.onclick=()=>{selectedVersion=el.dataset.version;go('delivery');});refresh();
  }
  function activeDocument(){if(selectedVersion&&selectedVersion!=='draft'){const found=state.snapshots.find(s=>s.id===selectedVersion);if(found)return found;}if(selectedVersion===null&&state.snapshots.length)return state.snapshots[state.snapshots.length-1];return {...calculate(),id:'当前草稿',brief:clone(state.brief),looks:clone(selectedLooks()),quote:clone(state.quote),created:new Date().toLocaleDateString('zh-CN')};}
  function deliveryPage(){const doc=activeDocument();main(heading('交付预览',E(doc.brief.name),button('编辑报价','arrow-left','secondary','data-go="quotes"')+button('导出明细','download','secondary','id="delivery-csv"')+button('打印 / PDF','printer','primary','id="print-delivery"'))+`<div class="delivery-toolbar"><select class="input" id="delivery-version" aria-label="选择报价版本"><option value="draft" ${doc.id==='当前草稿'?'selected':''}>当前编辑草稿</option>${state.snapshots.map(s=>`<option value="${s.id}" ${doc.id===s.id?'selected':''}>${s.id} · ${money(s.total)}</option>`).join('')}</select><span class="badge ${doc.id==='当前草稿'?'warning':'success'}">${doc.id==='当前草稿'?'未保存版本':'报价快照 · 已保存'}</span></div><article class="delivery-sheet"><header class="document-header"><div><div class="document-brand">织选 STUDIO</div><div class="document-number">${E(doc.id)} / CNY</div></div><div class="document-heading"><h2>搭配提案与商品报价</h2><p>${E(doc.brief.name)}</p></div></header><div class="delivery-intro"><div><strong>${E(doc.brief.client)}</strong>采购场景：${E(doc.brief.scene)}<br>风格偏好：${E(doc.brief.style)}</div><div>报价日期：${E(doc.created)}<br>有效期至：${E(doc.quote.validUntil)}<br>期望交付：${E(doc.brief.date)}</div></div><div class="document-looks">${doc.looks.map((l,n)=>`<section class="document-look"><h3>LOOK 0${n+1} / ${E(l.name)}</h3><div class="mini-board">${l.ids.map(id=>photo(doc.rows.find(p=>p.id===id)||getProduct(id))).join('')}</div><p>${E(l.reason)}</p></section>`).join('')}</div><div class="table-wrap"><table class="quote-table"><thead><tr><th>商品名称 / SKU</th><th>单价</th><th>数量</th><th>成交金额</th></tr></thead><tbody>${doc.rows.map(r=>`<tr><td>${E(r.name)}<small class="muted" style="display:block;margin-top:4px">${r.sku}</small></td><td>${money(r.price)}</td><td>${r.qty}</td><td>${money(r.discounted)}</td></tr>`).join('')}</tbody></table></div>${!doc.rows.length?'<p class="muted-paragraph">尚未选择报价商品。</p>':''}<div class="document-total"><div class="money-line"><span>商品成交金额（${E(doc.quote.discount)}%）</span><strong>${money(doc.net)}</strong></div><div class="money-line"><span>运输与包装费</span><strong>${money(doc.fee)}</strong></div><div class="money-line"><span>税额（${E(doc.quote.tax)}%）</span><strong>${money(doc.tax)}</strong></div><div class="money-line total"><span>含税报价总额</span><strong>${money(doc.total)}</strong></div></div><div class="document-footer"><div>${E(doc.quote.note)}<br>商品图片仅展示对应选品，尺码配比以采购双方确认为准。</div><span>织选品牌工作室<br>交互原型 · 示例报价</span></div></article>`);bindGo();document.getElementById('delivery-version').onchange=event=>{selectedVersion=event.target.value;render();};document.getElementById('delivery-csv').onclick=()=>exportQuote(doc);document.getElementById('print-delivery').onclick=()=>window.print();}
  function guardDelivery(){const doc=activeDocument();if(doc.id!=='当前草稿')return;const errors=quoteErrors(doc);if(!errors.length)return;document.body.classList.add('invalid-quote');document.getElementById('delivery-csv').disabled=true;document.getElementById('print-delivery').disabled=true;const warning=document.createElement('div');warning.className='callout danger delivery-error';warning.setAttribute('role','alert');warning.innerHTML='<strong>草稿存在以下问题，请返回报价编辑后再交付。</strong><br>'+errors.map(E).join('<br>');document.querySelector('.delivery-toolbar').after(warning);}
  function csvValue(value){const str=String(value??'');return '"'+(/^[=+@-]/.test(str)?"'":'')+str.replace(/"/g,'""')+'"';}
  function downloadCSV(name,rows){U.download(name,'\uFEFF'+rows.map(row=>row.map(csvValue).join(',')).join('\r\n'),'text/csv;charset=utf-8');}
  function exportQuote(doc){downloadCSV('织选报价-'+doc.id+'.csv',[['报价编号',doc.id],['客户',doc.brief.client],['方案',doc.brief.name],['有效期',doc.quote.validUntil],[],['SKU','商品名称','销售单价(元)','数量','成交系数(%)','成交金额(元)'],...doc.rows.map(r=>[r.sku,r.name,(r.price/100).toFixed(2),r.qty,doc.quote.discount,(r.discounted/100).toFixed(2)]),[],['商品成交合计',(doc.net/100).toFixed(2)],['运输与包装费',(doc.fee/100).toFixed(2)],['税额',(doc.tax/100).toFixed(2)],['含税总额',(doc.total/100).toFixed(2)],['商务备注',doc.quote.note]]);}
  function projectsPage(){main(heading('全部方案','客户需求、搭配与报价集中管理',button('新建方案','plus','primary','id="new-project"'))+`<div class="filter-row"><label class="search-field">${I('search')}<input class="input" id="project-search" aria-label="搜索方案" placeholder="搜索方案或客户" value="${E(projectQuery)}"></label></div><div id="project-results"></div>`);document.getElementById('new-project').onclick=newProject;const update=()=>{const list=[{current:true,brief:state.brief,looks:state.looks,date:'当前编辑'},...state.history.slice().reverse()].filter(p=>(p.brief.name+p.brief.client).includes(projectQuery));document.getElementById('project-results').innerHTML=list.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>方案名称</th><th>客户</th><th>搭配数</th><th>状态</th><th>更新时间</th><th></th></tr></thead><tbody>${list.map(p=>`<tr><td><span class="project-name">${E(p.brief.name)}</span></td><td>${E(p.brief.client)}</td><td>${p.looks.length} 套</td><td><span class="badge ${p.current?'success':'neutral'}">${p.current?'当前编辑':'已保留'}</span></td><td>${E(p.date)}</td><td><button class="link-button" data-open-project="${p.current?'current':p.id}">打开方案</button></td></tr>`).join('')}</tbody></table></div>`:empty('没有找到方案','可以更换关键词，或新建一份客户方案。');document.querySelectorAll('[data-open-project]').forEach(el=>el.onclick=()=>{const id=el.dataset.openProject;if(id==='current'){go('workbench');return;}const index=state.history.findIndex(p=>p.id===Number(id)),saved=state.history[index],current={id:Date.now(),brief:clone(state.brief),looks:clone(state.looks),quoteRows:clone(state.quoteRows),quote:clone(state.quote),date:new Date().toLocaleDateString('zh-CN')};state.brief=clone(saved.brief);state.looks=clone(saved.looks);state.quoteRows=clone(saved.quoteRows);state.quote=clone(saved.quote||defaults.quote);state.history.splice(index,1,current);save();go('workbench');});U.icons();};document.getElementById('project-search').oninput=event=>{projectQuery=event.target.value;update();};update();}
  function customersPage(){main(heading('客户档案','维护客户采购偏好与联系人',button('新增客户','user-plus','primary','id="new-customer"'))+`<div class="filter-row"><label class="search-field">${I('search')}<input class="input" id="customer-search" value="${E(customerQuery)}" placeholder="搜索客户、联系人或城市" aria-label="搜索客户"></label><span class="catalog-count">${state.customers.length} 位客户</span></div><div id="customer-results"></div>`);const update=()=>{const list=state.customers.filter(c=>(c.name+c.person+c.city).includes(customerQuery));document.getElementById('customer-results').innerHTML=list.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>客户</th><th>联系人</th><th>城市</th><th>客户类型</th><th>在库方案</th><th></th></tr></thead><tbody>${list.map(c=>`<tr><td><div class="client-row"><span class="client-emblem">${E(c.name.slice(0,1))}</span><strong>${E(c.name)}</strong></div></td><td>${E(c.person)}</td><td>${E(c.city)}</td><td>${E(c.type)}</td><td>${[state.brief,...state.history.map(h=>h.brief)].filter(b=>b.client===c.name).length}</td><td><button class="link-button" data-customer="${state.customers.indexOf(c)}">查看档案</button></td></tr>`).join('')}</tbody></table></div>`:empty('没有找到客户','更换名称、联系人或城市关键词。');document.querySelectorAll('[data-customer]').forEach(el=>el.onclick=()=>customerDrawer(Number(el.dataset.customer)));U.icons();};document.getElementById('customer-search').oninput=event=>{customerQuery=event.target.value;update();};document.getElementById('new-customer').onclick=()=>customerDrawer();update();}
  function customerDrawer(index){const existing=Number.isInteger(index),c=existing?state.customers[index]:{name:'',person:'',city:'',type:'品牌买手店',email:'',note:''};U.drawer(existing?'客户档案':'新增客户',`<form id="customer-form"><div class="form-grid">${field('客户名称 *','name',c.name,'text','required maxlength="60"')}${field('联系人 *','person',c.person,'text','required maxlength="30"')}${field('城市','city',c.city,'text','maxlength="30"')}${field('客户类型','type',c.type,'text','maxlength="30"')}<div class="wide">${field('联系邮箱','email',c.email,'email')}</div><label class="field wide"><span class="field-label">采购偏好与备注</span><textarea class="input" name="note">${E(c.note)}</textarea></label></div><p id="customer-error" class="inline-error"></p></form>`,button('保存客户','check','primary','id="save-customer"'));document.getElementById('save-customer').onclick=()=>{const form=document.getElementById('customer-form');if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));data.name=data.name.trim();data.person=data.person.trim();if(!data.name||!data.person){document.getElementById('customer-error').textContent='请填写客户名称和联系人。';return;}if(state.customers.some((x,i)=>i!==index&&x.name===data.name)){document.getElementById('customer-error').textContent='该客户名称已存在，请使用不同名称。';return;}if(existing){const previous=state.customers[index].name;state.customers[index]=data;if(state.brief.client===previous)state.brief.client=data.name;state.history.forEach(h=>{if(h.brief.client===previous)h.brief.client=data.name;});}else state.customers.push(data);save();U.closeDrawer();render();};}
  window.addEventListener('hashchange',render);
  save();
  render();
})();
