/* 管理员组合模板与销售递进同步；独立模块沿用统一事务和图片版本规则。 */
(function(){'use strict';const F=window.F,E=F.esc,$=id=>document.getElementById(id);const A=F.advanced={};const guard=fn=>async()=>{try{await fn();}catch(e){F.notify(e.message,'error');}};
A.validate=templates=>{for(const n of [1,2,3,4]){const slots=templates[n];if(!Array.isArray(slots)||slots.length!==n||new Set(slots).size!==n||slots.some(c=>!F.categories.includes(c)))throw Error(n+'品类模板必须有'+n+'个互不重复的启用品类');}return templates;};
A.renderSettings=()=>{const templates=F.state.settings.combinationTemplates||F.defaultTemplates(),editable=['manager','admin'].includes(F.state.role);F.main.insertAdjacentHTML('beforeend','<section class="panel" id="combination-settings"><div class="panel-head"><div><h2>组合模板</h2><p class="small-text">模板 V'+(F.state.settings.templateVersion||1)+'，每个档位使用互异品类；保存后用于新方案。</p></div><span class="badge">管理员配置</span></div>'+[1,2,3,4].map(n=>'<div class="field"><span>'+n+' 品类档位</span><div class="actions">'+templates[n].map((cat,i)=>'<label class="field" style="margin:0;min-width:120px"><span class="tiny">槽位 '+(i+1)+'</span><select data-template-group="'+n+'" '+(!editable?'disabled':'')+'>'+F.categories.map(c=>'<option '+(cat===c?'selected':'')+'>'+c+'</option>').join('')+'</select></label>').join('')+'</div></div>').join('')+'<div class="notice">递进模式建议上级槽位包含下级；不包含时按独立商品槽位处理，不能承诺自动继承。已有方案仍使用其保存的模板版本。</div><div class="actions"><button class="btn primary" id="template-save" '+(!editable?'disabled':'')+'>保存模板</button><button class="btn secondary" id="template-apply-current" '+(!editable?'disabled':'')+'>应用到当前需求草稿</button></div></section>');
 const read=()=>A.validate(Object.fromEntries([1,2,3,4].map(n=>[n,[...document.querySelectorAll('[data-template-group="'+n+'"]')].map(i=>i.value)])));
 $('template-save').onclick=guard(()=>{F.requireRole(['manager','admin']);const next=read();F.commit('保存组合模板',s=>{s.settings.combinationTemplates=next;s.settings.templateVersion=(s.settings.templateVersion||1)+1;});F.render();F.notify('模板已保存，将用于新建方案');});
 $('template-apply-current').onclick=guard(()=>{F.requireRole(['manager','admin']);const next=read();F.modal({title:'应用模板到当前需求',body:'<p>当前搭配将保留，但需求进入待确认。确认需求后重新生成候选才能使用新模板。已有报价快照不会改变。</p>',footer:'<button class="btn primary" id="template-apply-confirm">应用到草稿</button>',bind:()=>{$('template-apply-confirm').onclick=guard(()=>{F.commit('应用组合模板到需求',s=>{s.settings.combinationTemplates=next;s.settings.templateVersion=(s.settings.templateVersion||1)+1;s.brief.groupSlots=F.clone(next);s.brief.templateVersion=s.settings.templateVersion;s.brief.confirmed=false;s.quote.exception=null;});F.closeModal();F.go('brief');});}});});
};
A.changes=(original,draft)=>{const replacements=original.productIds.flatMap(oldId=>{const old=F.product(oldId),newId=draft.productIds.find(id=>F.product(id)?.category===old?.category);return newId&&newId!==oldId?[{oldId,newId}]:[];});return F.state.looks.filter(l=>l.group>original.group&&l.id!==draft.id).flatMap(l=>{const changes=replacements.filter(r=>l.productIds.includes(r.oldId));return changes.length?[{id:l.id,name:l.name,changes,conflict:changes.some(r=>(l.manualLocks||[]).includes(r.oldId))}]:[];});};
A.applyChanges=items=>{F.requireRole(['sales','manager','admin']);F.commit('同步递进基础商品',s=>{for(const item of items.filter(x=>!x.conflict)){const l=s.looks.find(l=>l.id===item.id);if(!l)throw Error('目标候选已变化，请重新预览');for(const r of item.changes){if(!l.productIds.includes(r.oldId)||(l.manualLocks||[]).includes(r.oldId))throw Error('出现新的锁定冲突，请重新预览');const p=s.products.find(p=>p.id===r.newId);l.productIds=l.productIds.map(id=>id===r.oldId?r.newId:id);l.locks=l.locks.map(id=>id===r.oldId?r.newId:id);delete l.allocations[r.oldId];l.allocations[r.newId]=F.allocate(p,l.qty);}l.revision++;l.allocationsConfirmed=false;l.imageId=null;l.imageMode='original';s.imageJobs.filter(j=>j.lookId===l.id).forEach(j=>{if(j.reserved){s.settings.credits+=j.points||0;j.reserved=false;}j.status='stale';j.message='递进商品同步后需重新复核';});}F.touch(s);});};
A.previewProgression=(original,draft)=>{const items=A.changes(original,draft);if(!items.length)return;F.modal({title:'同步基础款到递进档位',body:'<p>当前候选已保存。以下高档位使用同一基础款，可逐项选择同步。单独手动锁定的商品保持原值，需要先到对应候选解锁。</p>'+items.map(x=>'<label class="check notice"><input type="checkbox" name="progression-choice" value="'+E(x.id)+'" '+(x.conflict?'disabled':'checked')+'><span><b>'+E(x.name)+'</b><br>'+x.changes.map(r=>E(F.product(r.oldId).name)+' → '+E(F.product(r.newId).name)).join('<br>')+'<br>'+(x.conflict?'存在单独锁定冲突，跳过':'同步后重新确认尺码并核价')+'</span></label>').join(''),footer:'<button class="btn secondary" id="progression-cancel">仅修改当前候选</button><button class="btn primary" id="progression-apply">同步选中的档位</button>',bind:()=>{$('progression-cancel').onclick=F.closeModal;$('progression-apply').onclick=guard(()=>{const ids=[...document.querySelectorAll('[name=progression-choice]:checked')].map(i=>i.value);if(!ids.length)throw Error('请选择至少一个无锁定冲突的档位');A.applyChanges(items.filter(x=>ids.includes(x.id)));F.closeModal();F.render();F.notify('递进档位已同步，请重新核对报价条件');});}});};
})();
