/* 组合模板与同步竞态规则；内存夹具故意注入预览后的冲突，不替代浏览器业务流程。 */
'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const root=__dirname,checks=[];
const files=['core.js','advanced.js'];
const sources=Object.fromEntries(files.map(f=>[f,fs.readFileSync(path.join(root,f),'utf8')]));
const sourceHashes=Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(sources[f]).digest('hex')]));
const plain=value=>JSON.parse(JSON.stringify(value));
function fresh(){const disk=new Map(),sandbox={console,Date,Blob,URL,setTimeout,document:{},localStorage:{getItem:k=>disk.get(k)||null,setItem:(k,v)=>disk.set(k,v)}};sandbox.window=sandbox;vm.createContext(sandbox);for(const f of files)vm.runInContext(sources[f],sandbox,{filename:f});const F=sandbox.F;F.generateLooks();return{F,disk};}
function replacement(F){const original=F.clone(F.state.looks.find(l=>l.group===1)),draft=F.clone(original);draft.productIds=[F.state.products.find(p=>p.category==='上衣'&&p.id!==original.productIds[0]).id];return{original,draft,items:F.advanced.changes(original,draft)};}
function test(id,name,fn){try{fn();checks.push({id,name,result:'Pass'});}catch(e){checks.push({id,name,result:'Fail',error:e.stack});process.exitCode=1;}}
test('ADV-01','四档模板支持合法重排，重复/未知/错数量全部拒绝',()=>{const{F}=fresh(),templates=F.defaultTemplates();templates[1]=['鞋'];templates[2]=['帽子','上衣'];F.advanced.validate(templates);for(const change of [t=>t[2]=['鞋','鞋'],t=>t[1]=['背包'],t=>t[3]=['上衣','裤子']]){const bad=F.clone(templates);change(bad);assert.throws(()=>F.advanced.validate(bad),/互不重复/);}});
test('ADV-02','手动锁定预览标记冲突并跳过该候选，其余候选同步',()=>{const{F}=fresh(),{original,draft}=replacement(F);const target=F.state.looks.find(l=>l.group===3&&l.productIds.includes(original.productIds[0]));F.commit('测试夹具：单独手动锁定',s=>s.looks.find(l=>l.id===target.id).manualLocks=[original.productIds[0]]);const items=F.advanced.changes(original,draft);assert.equal(items.find(i=>i.id===target.id).conflict,true);const held=JSON.stringify(F.state.looks.find(l=>l.id===target.id));F.advanced.applyChanges(items);assert.equal(JSON.stringify(F.state.looks.find(l=>l.id===target.id)),held);for(const item of items.filter(i=>!i.conflict))assert.ok(F.state.looks.find(l=>l.id===item.id).productIds.includes(draft.productIds[0]));});
test('ADV-03','预览后出现新锁定冲突，整批不写且前序候选不部分生效',()=>{const{F,disk}=fresh(),{original,items}=replacement(F);assert.ok(items.length>=2);const last=items.at(-1);F.commit('测试夹具：预览后新锁定',s=>s.looks.find(l=>l.id===last.id).manualLocks=[original.productIds[0]]);const before=JSON.stringify(F.state),stored=disk.get(F.storageKey);assert.throws(()=>F.advanced.applyChanges(items),/新的锁定冲突/);assert.equal(JSON.stringify(F.state),before);assert.equal(disk.get(F.storageKey),stored);});
test('ADV-04','预览后目标被移除，原子拒绝并保留有效版本',()=>{const{F,disk}=fresh(),{items}=replacement(F);F.commit('测试夹具：预览后删除目标',s=>s.looks=s.looks.filter(l=>l.id!==items.at(-1).id));const before=JSON.stringify(F.state),stored=disk.get(F.storageKey);assert.throws(()=>F.advanced.applyChanges(items),/目标候选已变化/);assert.equal(JSON.stringify(F.state),before);assert.equal(disk.get(F.storageKey),stored);});
test('ADV-05','同步使图片失效、返还预留演示积分、配比重新确认且保留历史快照',()=>{const{F}=fresh(),{items,draft}=replacement(F);const target=items[0];F.commit('测试夹具：已有图片与不可变快照',s=>{const l=s.looks.find(l=>l.id===target.id);l.allocationsConfirmed=true;l.imageId='job-pending';l.imageMode='model';s.imageJobs.push({id:'job-pending',lookId:l.id,status:'running',reserved:true,points:2});s.settings.credits=100;s.snapshots.push({id:'historical-snapshot',groups:[{lines:[{productId:l.productIds[0],price:8000}]}]});});const history=plain(F.state.snapshots),previous=F.state.looks.find(l=>l.id===target.id).revision;F.advanced.applyChanges([target]);const l=F.state.looks.find(l=>l.id===target.id),job=F.state.imageJobs.find(j=>j.id==='job-pending');assert.equal(l.revision,previous+1);assert.equal(l.allocationsConfirmed,false);assert.equal(l.imageId,null);assert.equal(l.imageMode,'original');assert.equal(job.status,'stale');assert.equal(job.reserved,false);assert.equal(F.state.settings.credits,102);assert.equal(Object.values(l.allocations[draft.productIds[0]]).reduce((a,n)=>a+n,0),l.qty);assert.deepEqual(plain(F.state.snapshots),history);});
test('ADV-06','运营角色不能执行销售递进同步，状态保持',()=>{const{F}=fresh(),{items}=replacement(F);F.commit('测试夹具：运营角色',s=>s.role='operator');const before=JSON.stringify(F.state);assert.throws(()=>F.advanced.applyChanges(items),/无此操作权限/);assert.equal(JSON.stringify(F.state),before);});
const result={at:new Date().toISOString(),command:'node prototype/fashion-workbench-v2/advanced-test.cjs',sourceHashes,scope:'内存合成夹具：模板与递进变更、手动锁定竞态、原子失败、图片及演示积分；不证明真实服务端并发',passed:checks.filter(c=>c.result==='Pass').length,failed:checks.filter(c=>c.result==='Fail').length,checks};
const target=path.join(root,'verification','advanced-results.json');fs.mkdirSync(path.dirname(target),{recursive:true});if(fs.existsSync(target)){const previous=JSON.parse(fs.readFileSync(target,'utf8'));result.previousRuns=[...(previous.previousRuns||[]),{...previous,previousRuns:undefined}].slice(-8);}fs.writeFileSync(target,JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
