/* 本地销售工作台。外部服务入口明确展示来源，业务动作写入统一状态。 */
(function(){'use strict';
const F=window.F,E=F.esc,$=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
const nav=[['dashboard','工作概览','layout-dashboard','工作空间'],['projects','客户方案','folders'],['brief','需求工作台','clipboard-list'],['looks','搭配选品','layers-3'],['studio','图片工作室','image'],['quotes','报价确认','receipt-text'],['delivery','方案交付','presentation'],['catalog','商品库','shirt','商品资料'],['imports','数据导入','database'],['media','图片素材','images'],['customers','客户管理','contact','业务管理'],['settings','工作台设置','settings-2']];
F.main=$('#main');let lastFocus=null,lookTab=4,studioLook='',filterJob='all';
F.icon=name=>'<i data-lucide="'+E(name)+'" aria-hidden="true"></i>';
F.notify=(text,kind='success')=>{const div=document.createElement('div');div.className='toast '+kind;div.textContent=text;$('#notifications').append(div);while($('#notifications').children.length>3)$('#notifications').firstElementChild.remove();setTimeout(()=>div.remove(),6000);};
const safe=fn=>async ev=>{try{await fn(ev);}catch(e){F.notify(e.message,'error');}};
F.safe=safe;
F.modal=({title,body,footer='',bind})=>{lastFocus=document.activeElement;$('#modal-content').innerHTML='<div class="modal-head"><h2>'+E(title)+'</h2><button class="icon-button" id="modal-x" aria-label="关闭对话框">'+F.icon('x')+'</button></div><div class="modal-body">'+body+'</div><div class="modal-footer">'+footer+'</div>';if(!$('#modal').open)$('#modal').showModal();$('#modal-x').onclick=F.closeModal;bind?.();window.lucide?.createIcons();};
F.closeModal=()=>{$('#modal').close();if(lastFocus?.isConnected)lastFocus.focus();};$('#modal').addEventListener('cancel',()=>lastFocus?.focus());
$('#modal').addEventListener('keydown',event=>{if(event.key!=='Tab')return;const focusable=$$('button,input,select,textarea,a[href],[tabindex]',$('#modal')).filter(el=>!el.disabled&&el.tabIndex>=0&&el.getClientRects().length);if(!focusable.length){event.preventDefault();return;}const first=focusable[0],last=focusable[focusable.length-1],active=document.activeElement;if(!$('#modal').contains(active)||(event.shiftKey&&active===first)){event.preventDefault();last.focus();}else if(!event.shiftKey&&active===last){event.preventDefault();first.focus();}});
const btn=(text,id,primary=false,icon='')=>'<button class="btn '+(primary?'primary':'secondary')+'" '+(id?'id="'+id+'"':'')+'>'+(icon?F.icon(icon):'')+text+'</button>';
const field=(label,name,value,type='text',extra='')=>'<label class="field"><span>'+label+'</span><input id="'+name+'" name="'+name+'" type="'+type+'" value="'+E(value)+'" '+extra+'></label>';
const select=(label,name,items,value)=>'<label class="field"><span>'+label+'</span><select id="'+name+'" name="'+name+'">'+items.map(x=>{const [v,t]=Array.isArray(x)?x:[x,x];return'<option value="'+E(v)+'" '+(v===value?'selected':'')+'>'+E(t)+'</option>';}).join('')+'</select></label>';
const head=(eyebrow,title,desc,actions='')=>'<div class="page-heading"><div><div class="eyebrow">'+eyebrow+'</div><h1>'+title+'</h1><p>'+desc+'</p></div><div class="actions">'+actions+'</div></div>';
const empty=(title,desc,route,text)=>'<div class="empty">'+F.icon('layers-3')+'<h2>'+title+'</h2><p>'+desc+'</p>'+ (route?'<button class="btn primary" data-go="'+route+'">'+text+'</button>':'')+'</div>';
const date=t=>new Date(t).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
F.render=()=>{const item=nav.find(n=>n[0]===F.route)||nav[0];$('#breadcrumb').innerHTML='<div class="breadcrumb"><span>织选工作台</span><span>/</span><b>'+item[1]+'</b></div>';$('#sidebar').innerHTML='<a class="brand" href="#dashboard"><span class="brand-mark">织</span><span><b>织选</b><small>ZHIXUAN STUDIO</small></span></a>'+nav.map(n=>(n[3]?'<div class="nav-label">'+n[3]+'</div>':'')+'<button data-go="'+n[0]+'" class="nav-item '+(F.route===n[0]?'active':'')+'" '+(F.route===n[0]?'aria-current="page"':'')+'>'+F.icon(n[2])+n[1]+'</button>').join('')+'<div class="sidebar-bottom"><b>让每一套都有据可依</b>商品 · 搭配 · 报价 · 交付</div>';F.main.innerHTML='';try{const result=F.pages[F.route]?.();if(result instanceof Promise)result.catch(e=>F.notify(e.message,'error'));F.enhance?.();}catch(e){F.main.innerHTML=empty('页面暂时无法显示',E(e.message),'dashboard','返回概览');}window.lucide?.createIcons();};
F.go=route=>{if(!nav.some(n=>n[0]===route))route='dashboard';F.route=route;history.replaceState(null,'','#'+route);$('#sidebar').classList.remove('open');F.render();window.scrollTo(0,0);};
document.addEventListener('click',e=>{const target=e.target.closest('[data-go]');if(target)F.go(target.dataset.go);});$('#menu-toggle').onclick=()=>$('#sidebar').classList.toggle('open');$('#role-shortcut').onclick=()=>F.go('settings');
function projectDialog(copy=false){F.modal({title:copy?'复制当前客户方案':'新建客户方案',body:field('方案名称','new-title',copy?F.state.brief.title+' · 副本':'')+select('服务客户','new-client',F.state.clients.map(c=>[c.id,c.name]),F.state.brief.clientId),footer:btn('取消','new-cancel')+btn('创建方案','new-save',true),bind:()=>{$('#new-cancel').onclick=F.closeModal;$('#new-save').onclick=safe(()=>{const title=$('#new-title').value.trim();if(!title)throw Error('请填写方案名称');F.newProject(title,$('#new-client').value,copy);F.closeModal();F.go('brief');});}});}
F.pages.dashboard=()=>{
 const s=F.state,client=s.clients.find(c=>c.id===s.brief.clientId),q=F.quoteGroups(),ready=s.looks.filter(l=>l.selected).length;
 F.main.innerHTML=head('YOUR STYLING DESK','早安，开始一份好方案','从准确的商品资料，到让客户看得懂的搭配报价。',btn('新建客户方案','dash-new',true,'plus'))+
 '<section class="hero"><div class="hero-copy"><div class="eyebrow">AUTUMN / TEAM COLLECTION</div><h2>好搭配，从了解客户开始。</h2><p>'+E(client?.name||'选择一个客户')+' · '+E(s.brief.scene)+'<br>'+s.brief.qty+' 套需求，一至四品类自由组合。让选品有依据，让报价更清楚。</p><div class="actions">'+btn(s.looks.length?'继续搭配方案':'开始搭配选品','dash-continue',true,'arrow-right')+'<button class="btn ghost" data-go="brief">查看客户需求 '+F.icon('arrow-up-right')+'</button></div></div><div class="hero-visual"><img src="assets/model-olive.png" alt="米杏上衣、苔绿裤帽与米白鞋的模特搭配示例"><span class="hero-tag">AI 生成的设计示例</span></div></section>'+
 '<div class="grid four stats">'+[[s.products.filter(p=>p.status==='active').length,'可选商品','款色级 · 尺码独立库存','shirt'],[s.looks.length,'搭配候选','支持一至四品类','layers-3'],[s.snapshots.length,'已确认报价','独立版本，可追溯','receipt-text'],[s.imageJobs.filter(j=>j.status==='review').length,'待复核图片','逐件核对款式与颜色','scan-eye']].map(([n,t,h,i])=>'<div class="stat"><div class="stat-label">'+t+F.icon(i)+'</div><strong>'+n.toString().padStart(2,'0')+'</strong><small>'+h+'</small></div>').join('')+'</div>'+
 '<div class="split"><section class="panel"><div class="panel-head"><div><h2>正在推进的方案</h2><p>客户需求与搭配进度，保持在同一个版本中</p></div><button class="btn ghost small" data-go="projects">全部方案 '+F.icon('arrow-right')+'</button></div><div class="status-row"><span class="badge">'+(s.brief.confirmed?'需求已确认':'需求待确认')+'</span><span class="badge neutral">'+(s.quote.mode==='alternatives'?'备选报价':'合并采购')+'</span></div><h3 style="margin:16px 0 3px">'+E(s.brief.title)+'</h3><p class="small-text">'+E(client?.name)+' / '+E(client?.person)+' · '+E(s.brief.style)+'</p><div class="metric-line"><span><b>'+s.brief.qty+' 套</b>采购需求</span><span><b>'+(s.brief.budget===null?'未设上限':F.money(s.brief.budget))+'</b>总预算</span><span><b>'+ready+' 组</b>已选候选</span></div><div class="divider"></div><div class="panel-head" style="margin:0"><p>'+(s.looks.length?(q.errors.length?'有 '+q.errors.length+' 项报价问题待处理':'当前候选已具备核价条件'):'需求已就绪，可生成第一轮搭配。')+'</p><button class="btn secondary small" data-go="'+(s.looks.length?'quotes':'looks')+'">继续处理 '+F.icon('arrow-up-right')+'</button></div></section><section class="panel"><div class="panel-head"><h2>方案交付路径</h2><span class="tiny muted">4 STEPS</span></div><div class="step-list">'+[['商品准备','维护价格库存，确认每一张原图','catalog'],['理解需求','客户、场景、数量与预算','brief'],['搭配与核价','一至四品类，逐套比较','looks'],['确认与交付','版本快照，导出可编辑 PPT','delivery']].map((x,i)=>'<div class="step"><span class="step-no">'+(i+1)+'</span><div><b>'+x[0]+'</b><p>'+x[1]+'</p></div><button class="btn ghost small" data-go="'+x[2]+'">'+F.icon('arrow-up-right')+'</button></div>').join('')+'</div></section></div>'+
 '<section class="panel"><div class="panel-head"><div><h2>本季商品灵感</h2><p>低饱和配色与舒适面料，适合团队与日常通勤</p></div><button class="btn ghost small" data-go="catalog">查看商品库 '+F.icon('arrow-right')+'</button></div><div class="grid four">'+s.products.slice(0,4).map(p=>'<div>'+F.photo(p)+'<h3 style="font-size:12px;margin:12px 0 3px">'+E(p.name)+'</h3><div class="status-row"><span class="small-text">'+F.money(p.price)+'</span><span class="tiny muted">'+E(p.color)+' / '+E(p.category)+'</span></div></div>').join('')+'</div></section>';
 $('#dash-new').onclick=()=>projectDialog();$('#dash-continue').onclick=()=>F.go('looks');
};
F.pages.projects=()=>{const s=F.state;const projects=[{id:s.projectId,brief:s.brief,looks:s.looks,status:'active',updatedAt:new Date().toISOString()},...s.projects.filter(p=>p.id!==s.projectId)];F.main.innerHTML=head('CLIENT PROPOSALS','客户方案','每位客户拥有独立需求、搭配与图片记录。',btn('保存当前方案','save-project',false,'save')+btn('新建方案','new-project',true,'plus'))+'<div class="grid three">'+projects.map(p=>'<article class="customer-card"><div class="panel-head"><span class="badge '+(p.status==='closed'?'neutral':'')+'">'+(p.id===s.projectId?'当前方案':p.status==='closed'?'已关闭':'进行中')+'</span><span class="tiny muted">'+date(p.updatedAt)+'</span></div><h3>'+E(p.brief.title)+'</h3><p>'+E(s.clients.find(c=>c.id===p.brief.clientId)?.name)+'</p><div class="metric-line"><span><b>'+p.brief.qty+'套</b>采购需求</span><span><b>'+p.looks.length+'组</b>搭配候选</span></div><div class="actions"><button class="btn small primary" data-open-project="'+p.id+'">打开方案</button>'+(p.id===s.projectId?'<button class="btn small" id="copy-project">复制</button>':'<button class="btn small" data-close-project="'+p.id+'">'+(p.status==='closed'?'恢复':'关闭')+'</button>')+'</div></article>').join('')+'</div>';$('#save-project').onclick=safe(()=>{F.archiveProject();F.notify('客户方案已保存');F.render();});$('#new-project').onclick=()=>projectDialog();$('#copy-project').onclick=()=>projectDialog(true);$$('[data-open-project]').forEach(b=>b.onclick=safe(()=>{if(b.dataset.openProject!==s.projectId)F.openProject(b.dataset.openProject);F.go('brief');}));$$('[data-close-project]').forEach(b=>b.onclick=safe(()=>{F.commit('调整方案状态',s=>{const p=s.projects.find(p=>p.id===b.dataset.closeProject);p.status=p.status==='closed'?'active':'closed';});F.render();}));};
F.pages.brief=()=>{const b=F.state.brief;F.main.innerHTML=head('REQUIREMENT STUDIO','把需求，变成可执行的选品条件','从客户描述开始，再确认结构化条件。',btn('保存需求','brief-save',false,'save')+btn('确认并去搭配','brief-next',true,'arrow-right'))+'<div class="split"><div><section class="panel"><div class="panel-head"><div><h2>客户怎么说</h2><p>支持从描述提取数量、预算与场景，结果可逐项修改</p></div><span class="badge neutral">本地规则解析演示</span></div><label class="field"><span>需求原文</span><textarea id="brief-text" rows="5" placeholder="例如：100套团建服装，每套预算300元，休闲风">'+E(b.text)+'</textarea></label><div class="actions">'+btn('解析需求','brief-parse',true,'sparkles')+'<span class="tiny muted">解析后请核对，不自动替您确认</span></div><div id="parse-result" aria-live="polite"></div></section><section class="panel"><div class="panel-head"><h2>采购与风格条件</h2><span class="badge '+(b.confirmed?'':'warn')+'">'+(b.confirmed?'已确认':'待确认')+'</span></div><div class="grid two">'+field('方案名称','brief-title',b.title)+select('服务客户','brief-client',F.state.clients.map(c=>[c.id,c.name]),b.clientId)+field('采购套数','brief-qty',b.qty,'number','min="1" max="1000000"')+field('总预算（元）','brief-budget',(b.budget/100).toFixed(2),'number','min="0" step="0.01"')+select('使用场景','brief-scene',['企业团建','员工福利','门店补货','商务活动'],b.scene)+select('主要风格','brief-style',['休闲','商务','通勤','户外'],b.style)+select('适用季节','brief-season',['四季','春秋','夏季','冬季'],b.season)+field('排除条件','brief-exclude',b.exclude,'text','placeholder="如：藏蓝、棒球帽，以逗号分隔"')+'</div></section></div><aside><section class="panel"><div class="eyebrow">BUILD YOUR RANGE</div><h2>报价档位</h2><p class="small-text" style="margin:8px 0 20px">让客户看懂每一步增配的价值</p>'+[1,2,3,4].map(n=>'<label class="check" style="margin:15px 0"><input type="checkbox" name="brief-group" value="'+n+'" '+(b.groups.includes(n)?'checked':'')+'><span><b>'+n+' 品类</b><br><span class="tiny muted">'+F.categories.slice(0,n).join(' + ')+'</span></span></label>').join('')+'<div class="divider"></div>'+select('每档候选数','brief-per',[['1','1 个候选'],['2','2 个候选'],['3','3 个候选']],String(b.perGroup))+'<label class="check"><input id="brief-progressive" type="checkbox" '+(b.progressive?'checked':'')+'>递进比较，锁定基础商品</label><div class="notice">递进模式保留相同候选的基础款，新增裤子、帽子和鞋，避免更换整套后难以比较价格。</div></section><section class="panel"><h3>默认报价口径</h3><p class="small-text" style="margin-top:9px">人民币 · 客户销售价<br>按 SKU 核对尺码库存<br>备选方案分别报价<br>最终以确认快照为准</p></section></aside></div>';
 const save=confirmed=>{const qty=F.integer($('#brief-qty').value,'采购套数',1,100000),budget=$('#brief-budget').value.trim()?F.parseMoney($('#brief-budget').value):null,groups=$$('[name=brief-group]:checked').map(x=>Number(x.value));if(budget===0)throw Error('预算须为正数；不设上限请留空');if(!groups.length)throw Error('至少选择一个报价档位');const title=$('#brief-title').value.trim();if(!title||title.length>100)throw Error('方案名称须为1–100字');const next={clientId:$('#brief-client').value,title,qty,budget,scene:$('#brief-scene').value,style:$('#brief-style').value,season:$('#brief-season').value,exclude:$('#brief-exclude').value.trim(),text:$('#brief-text').value,groups,perGroup:Number($('#brief-per').value),progressive:$('#brief-progressive').checked,confirmed};F.commit('保存客户需求',s=>{const changed=s.brief.qty!==next.qty||s.brief.clientId!==next.clientId;s.brief={...s.brief,...next};s.quote.exception=null;if(changed)s.looks.forEach(l=>l.allocationsConfirmed=false);});};
 $('#brief-save').onclick=safe(()=>{save(false);F.notify('需求草稿已保存；请确认后继续选品');F.render();});$('#brief-next').onclick=safe(()=>{save(true);F.go('looks');});$('#brief-parse').onclick=()=>{const text=$('#brief-text').value,qty=text.match(/(\d+)\s*套/),per=text.match(/每套(?:预算)?\s*(\d+(?:\.\d{1,2})?)\s*元/),total=text.match(/总预算\s*(\d+(?:\.\d{1,2})?)\s*元/);if(qty)$('#brief-qty').value=qty[1];if(per)$('#brief-budget').value=(Number(per[1])*Number($('#brief-qty').value)).toFixed(2);else if(total)$('#brief-budget').value=total[1];if(/团建/.test(text))$('#brief-scene').value='企业团建';for(const style of ['休闲','商务','通勤','户外'])if(text.includes(style))$('#brief-style').value=style;$('#parse-result').innerHTML='<div class="notice">已提取 '+[qty?'采购量 '+qty[1]+' 套':'未识别采购量',per?'每套 '+per[1]+' 元':total?'总预算 '+total[1]+' 元':'未识别预算'].join('；')+'。未识别字段保留原值，请核对下方条件后确认。</div>';};
};
function lookBoard(l){return'<div class="look-board">'+F.categories.map((cat,i)=>{const p=l.productIds.map(F.product).find(p=>p.category===cat);return p?F.photo(p):'<div class="look-board-placeholder">'+cat+' / 未选</div>';}).join('')+'</div>';}
F.pages.looks=()=>{const s=F.state;F.main.innerHTML=head('CURATED OUTFITS','搭配选品','按客户条件筛选真实商品，锁定、替换并核对每个尺码。',btn('重新生成候选','looks-generate',false,'refresh-cw')+'<button class="btn primary" data-go="quotes">进入报价确认 '+F.icon('arrow-right')+'</button>')+'<div class="panel" style="padding:15px 20px"><div class="panel-head" style="margin:0"><div class="status-row"><span class="badge">'+E(s.brief.scene)+'</span><span class="badge neutral">'+E(s.brief.style)+'</span><span class="small-text">'+s.brief.qty+' 套 · 总预算 '+(s.brief.budget===null?'未设上限':F.money(s.brief.budget))+'</span></div><button class="btn ghost small" data-go="brief">修改需求 '+F.icon('sliders-horizontal')+'</button></div></div>';
 $('#looks-generate').onclick=safe(()=>{if(s.looks.length)F.modal({title:'重新生成搭配候选',body:'<p>将替换当前 '+s.looks.length+' 个候选及其手工调整。已确认的报价快照保持独立。可先在客户方案页复制保存。</p>',footer:btn('保留当前','regen-cancel')+btn('替换候选','regen-yes',true),bind:()=>{$('#regen-cancel').onclick=F.closeModal;$('#regen-yes').onclick=safe(()=>{F.generateLooks();F.closeModal();F.render();});}});else{F.generateLooks();F.render();}});
 if(!s.looks.length){F.main.insertAdjacentHTML('beforeend',empty('需求已就绪，生成第一组搭配','候选只来自已上架、有价、有库存且图片已确认的商品。生成后可以逐件替换。'));return;}
 if(!s.looks.some(l=>l.group===lookTab))lookTab=s.looks[0].group;
 F.main.insertAdjacentHTML('beforeend','<div class="tabs" role="tablist" aria-label="品类档位">'+s.brief.groups.map(n=>'<button class="tab '+(n===lookTab?'active':'')+'" data-look-tab="'+n+'" role="tab" aria-selected="'+(n===lookTab)+'">'+n+' 品类 <span class="tiny">/ '+s.looks.filter(l=>l.group===n).length+'</span></button>').join('')+'</div><div class="look-grid">'+s.looks.filter(l=>l.group===lookTab).map(l=>{const c=F.calcLook(l);return'<article class="look-card '+(l.selected?'selected':'')+'"><div class="look-head"><label class="check"><input type="checkbox" data-select-look="'+l.id+'" '+(l.selected?'checked':'')+'>'+E(l.name)+'</label><span class="badge '+(c.errors.length?'warn':'')+'">'+(c.errors.length?'待处理 '+c.errors.length+' 项':'可报价')+'</span></div>'+lookBoard(l)+'<div class="look-body"><p>'+E(l.reason)+'</p><div class="actions" style="margin-top:11px">'+l.productIds.map(id=>'<span class="badge neutral">'+E(F.product(id)?.category)+(l.locks.includes(id)?' · 锁定':'')+'</span>').join('')+'</div>'+(c.errors.length?'<div class="notice warn">'+E(c.errors[0])+'</div>':'')+'</div><div class="look-foot"><div class="look-price">'+F.money(c.total)+'<br><small>'+l.qty+' 套 / 约 '+F.money(c.perSet)+' 每套</small></div><div class="actions"><button class="btn small" data-edit-look="'+l.id+'">调整搭配</button><button class="btn small primary" data-studio-look="'+l.id+'">制作图片</button></div></div></article>';}).join('')+'</div>');
 $$('[data-look-tab]').forEach(b=>b.onclick=()=>{lookTab=Number(b.dataset.lookTab);F.render();});$$('[data-select-look]').forEach(i=>i.onchange=safe(()=>{F.commit('选择报价候选',s=>{s.looks.find(l=>l.id===i.dataset.selectLook).selected=i.checked;F.touch(s);});F.render();}));$$('[data-edit-look]').forEach(b=>b.onclick=()=>editLook(b.dataset.editLook));$$('[data-studio-look]').forEach(b=>b.onclick=()=>{studioLook=b.dataset.studioLook;F.go('studio');});
};
function editLook(id){const original=F.state.looks.find(l=>l.id===id);let draft=F.clone(original);const show=()=>F.modal({title:'调整搭配 · '+draft.name,body:field('本候选采购套数','look-qty',draft.qty,'number','min="1"')+'<div class="notice">每个商品的尺码数量合计须等于本候选套数。锁定商品在手动解锁前不可替换。</div>'+draft.productIds.map(pid=>{const p=F.product(pid);return'<div class="slot">'+F.photo(p,'medium-photo')+'<div class="slot-main"><div class="slot-title"><div><h3>'+E(p.name)+'</h3><p class="tiny">'+E(p.color)+' · '+F.money(F.price(p))+' · '+E(p.sku)+'</p></div><div class="actions"><button class="btn small" data-lock="'+pid+'">'+(draft.locks.includes(pid)?'解锁':'锁定')+'</button><button class="btn small" data-replace="'+pid+'" '+(draft.locks.includes(pid)?'disabled':'')+'>替换</button></div></div><div class="sizes">'+p.sizes.map(s=>'<label class="size-field">'+E(s.size)+' 码<input type="number" min="0" max="1000000" data-alloc-product="'+pid+'" data-size="'+E(s.size)+'" value="'+(draft.allocations[pid]?.[s.size]??0)+'"><small>库存 '+s.stock+'</small></label>').join('')+'</div></div></div>';}).join('')+'<div id="look-error"></div>',footer:btn('取消','edit-cancel')+btn('按库存均分尺码','edit-allocate')+btn('保存搭配','edit-save',true),bind:()=>{
 $('.modal-body').insertAdjacentHTML('afterbegin',field('候选名称','look-name',draft.name)+'<label class="field"><span>搭配说明</span><textarea id="look-reason" rows="2">'+E(draft.reason)+'</textarea></label>');
 const read=()=>{draft.name=$('#look-name').value.trim();if(!draft.name||draft.name.length>100)throw Error('候选名称须为1–100字');draft.reason=$('#look-reason').value.trim().slice(0,1000);draft.qty=F.integer($('#look-qty').value,'套数',1,100000);$$('[data-alloc-product]').forEach(i=>{draft.allocations[i.dataset.allocProduct][i.dataset.size]=F.integer(i.value,'尺码数量');});};
 $('#edit-cancel').onclick=F.closeModal;$('#edit-allocate').onclick=safe(()=>{draft.qty=F.integer($('#look-qty').value,'套数',1);draft.productIds.forEach(id=>draft.allocations[id]=F.allocate(F.product(id),draft.qty));show();});
 $$('[data-lock]').forEach(b=>b.onclick=safe(()=>{read();const id=b.dataset.lock,isLocked=draft.locks.includes(id);draft.locks=isLocked?draft.locks.filter(x=>x!==id):[...draft.locks,id];draft.manualLocks=isLocked?(draft.manualLocks||[]).filter(x=>x!==id):[...(draft.manualLocks||[]),id];show();}));
 $$('[data-replace]').forEach(b=>b.onclick=safe(()=>{read();const old=F.product(b.dataset.replace);F.modal({title:'替换'+old.category,body:'<p class="small-text">同品类候选，保存后重新核对预算、库存和图片。</p><div class="grid three" style="margin-top:18px">'+F.state.products.filter(p=>p.category===old.category&&p.status==='active'&&p.id!==old.id).map(p=>'<div>'+F.photo(p)+'<h3 class="small-text" style="margin-top:9px">'+E(p.name)+'</h3><p class="tiny">'+F.money(F.price(p))+' · 库存 '+F.stock(p)+'</p><button class="btn small full-width" style="margin-top:10px" data-pick="'+p.id+'">选用此款</button></div>').join('')+'</div>',footer:btn('返回调整','replace-back'),bind:()=>{$('#replace-back').onclick=show;$$('[data-pick]').forEach(p=>p.onclick=()=>{const id=p.dataset.pick;draft.productIds=draft.productIds.map(x=>x===old.id?id:x);delete draft.allocations[old.id];draft.allocations[id]=F.allocate(F.product(id),draft.qty);draft.imageId=null;draft.imageMode='original';show();});}});}));
 $('#edit-save').onclick=safe(()=>{read();const c=F.calcLook(draft);const structural=c.errors.filter(e=>/尺码合计|数量不合法|不存在|重复/.test(e));if(structural.length){$('#look-error').innerHTML='<div class="notice error">'+structural.map(E).join('<br>')+'</div>';return;}const visualChanged=JSON.stringify(draft.productIds)!==JSON.stringify(original.productIds),allocationChanged=draft.qty!==original.qty||JSON.stringify(draft.allocations)!==JSON.stringify(original.allocations);F.commit('调整搭配',s=>{if(visualChanged){draft.revision++;draft.imageId=null;draft.imageMode='original';s.imageJobs.filter(j=>j.lookId===id).forEach(j=>{j.status='stale';j.message='商品已替换，需重新生成或复核';});}if(visualChanged||allocationChanged)draft.allocationsConfirmed=false;s.looks[s.looks.findIndex(l=>l.id===id)]=draft;F.touch(s);});F.closeModal();F.render();F.notify('搭配已保存');if(visualChanged&&F.state.brief.progressive)F.advanced?.previewProgression(original,draft);});}});show();}
F.editLook=editLook;
async function boardImage(l,bg='#f4f1e8',title='商品搭配示意'){
 const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=900;const ctx=canvas.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,1200,900);ctx.fillStyle='#294839';ctx.font='34px Microsoft YaHei';ctx.fillText(title,60,76);ctx.font='18px Microsoft YaHei';ctx.fillStyle='#7b806f';ctx.fillText('原图拼版 · '+l.group+' 品类 · '+l.qty+' 套',60,112);
 for(let i=0;i<l.productIds.length;i++){const p=F.product(l.productIds[i]);if(!p.imageAllowed||!p.image)throw Error(p.name+'图片不可用');const im=await loadImage(p.image);const w=l.group===1?520:480,h=l.group<=2?570:275,x=l.group===1?340:70+(i%2)*570,y=l.group<=2?175:175+Math.floor(i/2)*335;const c=p.crop||{x:0,y:0,w:1,h:1},sw=im.naturalWidth*c.w,sh=im.naturalHeight*c.h,scale=Math.min(w/sw,h/sh),dw=sw*scale,dh=sh*scale;ctx.drawImage(im,im.naturalWidth*c.x,im.naturalHeight*c.y,sw,sh,x+(w-dw)/2,y+(h-dh)/2,dw,dh);ctx.fillStyle='#394735';ctx.font='17px Microsoft YaHei';ctx.fillText((p.name+' / '+p.color).slice(0,27),x,y+h+28);}
 ctx.fillStyle='#929484';ctx.font='15px Microsoft YaHei';ctx.fillText('织选 · 商品形态以实物为准 / 原型示例',60,868);return canvas.toDataURL('image/jpeg',.85);
}
function loadImage(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('图片加载失败，请检查文件'));im.src=src;});}
F.boardImage=boardImage;
const jobNames={queued:'排队中',running:'处理中',review:'待人工复核',approved:'复核通过',rejected:'已驳回',failed:'生成失败',cancelled:'已取消',stale:'内容已变更'};
function newJob(lookId,kind,source='sample',image=null){const l=F.state.looks.find(l=>l.id===lookId);if(!l)throw Error('请先选择一个搭配候选');if(l.productIds.some(id=>!F.product(id)?.imageAllowed))throw Error('请先确认商品图片');if(kind==='ecommerce'&&!image)source='composition';const points=source==='sample'?1:0;if(F.state.settings.credits<points)throw Error('演示积分不足，请减少张数；不会触发付费调用');const job={id:F.uid('image'),lookId,lookRevision:l.revision,productVersions:Object.fromEntries(l.productIds.map(id=>[id,F.product(id).imageVersion])),kind,status:image?'review':'queued',image,createdAt:new Date().toISOString(),review:null,reviewer:null,source,message:source==='sample'?'使用预置模特示例；多张用于任务流程演示，不代表不同实生成结果。':source==='composition'?'将以商品原图生成电商展示拼版。':'用户上传的图像，须按当前商品逐件复核。',cost:0,points,reserved:points>0};F.commit('创建图片任务',s=>{s.settings.credits-=points;s.imageJobs.unshift(job);});if(!image)processJob(job.id);return job;}
function refundJob(s,j){if(j.reserved){s.settings.credits+=j.points||0;j.reserved=false;}}
function processJob(id){setTimeout(()=>{const j=F.state.imageJobs.find(j=>j.id===id);if(j?.status!=='queued')return;try{F.commit('图片任务开始',s=>s.imageJobs.find(j=>j.id===id).status='running');if(F.route==='studio')F.render();}catch(e){F.notify(e.message,'error');return;}setTimeout(async()=>{const j=F.state.imageJobs.find(j=>j.id===id);if(j?.status!=='running')return;const l=F.state.looks.find(l=>l.id===j.lookId),supported=l?.productIds.length===4&&['p00','p01','p02','p03'].every(id=>l.productIds.includes(id))&&l.productIds.every(id=>F.product(id).imageVersion===1);try{const composed=j.source==='composition'?await boardImage(l,'#ffffff','电商商品展示'):null;F.commit('图片任务完成',s=>{const target=s.imageJobs.find(x=>x.id===id);if(target.status!=='running')return;if(supported||composed){target.status='review';target.image=composed||'assets/model-olive.png';target.reserved=false;target.message=composed?'商品电商拼版已生成，请检查清单与图片。':'四件模特预置示例已就绪，请逐一核对。';}else{target.status='failed';refundJob(s,target);target.message='此组合无匹配的预置模特示例。可上传外部生成图复核，或制作商品拼版；演示积分已释放。';}});if(F.route==='studio')F.render();}catch(e){try{F.commit('图片任务失败',s=>{const target=s.imageJobs.find(x=>x.id===id);target.status='failed';target.message=e.message;refundJob(s,target);});}catch{}F.notify(e.message,'error');if(F.route==='studio')F.render();}},1300);},600);}
function reviewJob(id){const j=F.state.imageJobs.find(j=>j.id===id),l=F.state.looks.find(l=>l.id===j.lookId);if(!l)throw Error('对应方案已不存在');F.modal({title:'复核图片 · '+l.name,body:'<div class="image-review"><img src="'+E(j.image)+'" alt="待复核的搭配图"><div><span class="badge">'+(j.source==='sample'?'AI 预置示例':j.source==='composition'?'商品电商拼版':'外部生成图上传')+'</span><h3 style="margin:14px 0">逐件核对，确认后才能采用</h3><div class="review-checks">'+l.productIds.map(id=>{const p=F.product(id);return'<label class="check"><input type="checkbox" name="review-check"><span>'+E(p.category)+' · '+E(p.name)+'<br><span class="tiny muted">'+E(p.color)+' / '+E(p.sku)+'，款式、颜色及关键细节一致</span></span></label>';}).join('')+'<label class="check"><input type="checkbox" name="review-check">人体、遮挡与边缘无明显错误</label></div><label class="field"><span>复核说明 / 驳回原因</span><textarea id="review-note" rows="3" placeholder="例如：帽子颜色不符，需重新生成"></textarea></label><div class="notice">示意图不代表实际试穿尺寸。原型记录复核动作，真实商品保真需业务样本验证。</div></div></div>',footer:btn('驳回此图','review-reject')+btn('全部符合，采用此图','review-approve',true),bind:()=>{const finish=approved=>{F.requireRole(['sales','manager','admin']);if(approved&&$$('[name=review-check]:checked').length!==l.productIds.length+1)throw Error('请完成每项复核');if(!approved&&!$('#review-note').value.trim())throw Error('驳回时请填写原因');if(l.revision!==j.lookRevision||Object.entries(j.productVersions).some(([id,v])=>F.product(id)?.imageVersion!==v||!F.product(id)?.imageAllowed))throw Error('商品或搭配已变化，请重新准备图片');const note=$('#review-note').value;F.commit(approved?'图片复核通过':'图片复核驳回',s=>{const job=s.imageJobs.find(x=>x.id===id);job.status=approved?'approved':'rejected';job.review=note||'逐项复核通过';job.reviewer=s.role;job.reviewedAt=new Date().toISOString();if(approved){const look=s.looks.find(x=>x.id===j.lookId);look.imageId=id;look.imageMode='model';}});F.closeModal();F.render();};$('#review-reject').onclick=safe(()=>finish(false));$('#review-approve').onclick=safe(()=>finish(true));}});}
F.pages.studio=()=>{const s=F.state;if(!s.looks.length){F.main.innerHTML=head('IMAGE STUDIO','图片工作室','把搭配转成可展示的视觉素材。')+empty('先准备一组搭配','图片任务必须绑定具体商品与版本，才能追溯和复核。','looks','前往搭配选品');return;}if(!s.looks.some(l=>l.id===studioLook))studioLook=s.looks.find(l=>l.group===4)?.id||s.looks[0].id;const l=s.looks.find(l=>l.id===studioLook);
 F.main.innerHTML=head('IMAGE STUDIO','让客户，看见搭配效果','模特示例、外部生成图和商品拼版统一管理，确认后用于提案。','<button class="btn secondary" data-go="looks">返回搭配</button>')+'<div class="split"><section class="panel"><div class="panel-head"><div><h2>准备图片</h2><p>所有任务绑定当前候选与商品图片版本</p></div><span class="badge neutral">本地任务演示 · 不计费</span></div>'+select('当前搭配','studio-look',s.looks.map(l=>[l.id,l.name]),studioLook)+lookBoard(l)+'<div class="grid two" style="margin-top:20px">'+select('素材用途','studio-kind',[['model','模特搭配图'],['ecommerce','电商展示图']], 'model')+select('输出张数','studio-count',[['1','1 张'],['2','2 张'],['3','3 张'],['4','4 张']], '2')+'</div><div class="actions">'+btn('创建模特示例任务','studio-generate',true,'sparkles')+btn('上传生成图','studio-upload',false,'upload')+btn('制作商品拼版','studio-board',false,'layout-grid')+'</div><input id="studio-file" type="file" accept="image/png,image/jpeg,image/webp" hidden><div class="notice">预置模特与“米杏 Polo + 苔绿裤子 + 苔绿帽子 + 米白鞋”绑定。其他组合可上传生成图逐件复核；原图拼版即时生成并实际下载。</div></section><section class="panel"><div class="eyebrow">QUALITY BEFORE DELIVERY</div><h2>商品一致性检查</h2><div class="step-list">'+[['看款式','领型、轮廓、口袋与细节一致'],['看颜色','不要把相近颜色当成同一款'],['看完整度','鞋帽齐全，商品不被错误遮挡'],['看版本','换款、换色、换原图后重新复核']].map((x,i)=>'<div class="step"><span class="step-no">'+(i+1)+'</span><div><b>'+x[0]+'</b><p>'+x[1]+'</p></div></div>').join('')+'</div><button class="btn full-width" style="margin-top:20px" id="studio-original">当前搭配采用原图拼版</button></section></div><div class="panel-head"><div><h2>图片任务</h2><p>状态和处理记录随方案保存</p></div><div class="tabs" style="margin:0">'+[['all','全部'],['review','待复核'],['approved','已采用'],['failed','失败']].map(([v,t])=>'<button class="tab '+(filterJob===v?'active':'')+'" data-job-filter="'+v+'">'+t+'</button>').join('')+'</div></div>'+
 (s.imageJobs.filter(j=>filterJob==='all'||j.status===filterJob).length?'<div class="grid three">'+s.imageJobs.filter(j=>filterJob==='all'||j.status===filterJob).map(j=>'<article class="job-card"><div class="job-image '+(['queued','running'].includes(j.status)?'skeleton':'')+'">'+(j.image?'<img src="'+E(j.image)+'" alt="'+E(s.looks.find(l=>l.id===j.lookId)?.name)+'搭配图">':F.icon(j.status==='failed'?'image-off':'scan-line'))+'<span class="job-meta badge '+(['failed','stale','rejected'].includes(j.status)?'warn':'')+'">'+jobNames[j.status]+'</span></div><h3>'+E(s.looks.find(l=>l.id===j.lookId)?.name||'历史搭配')+'</h3><p>'+E(j.message)+'</p><div class="actions">'+(j.status==='review'?'<button class="btn primary small" data-review="'+j.id+'">复核与采用</button>':'')+(['queued','running'].includes(j.status)?'<button class="btn small" data-cancel-job="'+j.id+'">取消任务</button>':'')+(['failed','rejected','cancelled'].includes(j.status)?'<button class="btn small" data-retry-job="'+j.id+'">重新准备</button>':'')+(j.image?'<button class="btn small" data-download-job="'+j.id+'">下载图片</button>':'')+'</div><p class="tiny muted">'+date(j.createdAt)+' · '+(j.source==='sample'?'预置示例':j.source==='composition'?'商品电商拼版':'本地上传')+' · ¥0.00</p></article>').join('')+'</div>':empty('暂无此状态的图片任务','选择搭配并创建任务，或上传您已经生成的图片。'));
 $('#studio-look').onchange=e=>{studioLook=e.target.value;F.render();};$('#studio-generate').onclick=safe(()=>{const count=Number($('#studio-count').value),kind=$('#studio-kind').value;for(let i=0;i<count;i++)newJob(studioLook,kind);F.render();});$('#studio-upload').onclick=()=>$('#studio-file').click();$('#studio-file').onchange=safe(async e=>{const file=e.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024)throw Error('请上传 2MB 以内的 PNG、JPG 或 WebP');const image=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});await loadImage(image);newJob(studioLook,$('#studio-kind').value,'upload',image);F.render();});
 $('#studio-board').onclick=()=>F.modal({title:'制作电商 / 搭配拼版',body:select('画布风格','board-bg',[['#f4f1e8','暖白简约'],['#e9eee6','浅绿自然'],['#ffffff','纯白电商']], '#f4f1e8')+field('图片标题','board-title',l.name)+'<p class="small-text">使用当前商品原图和名称生成实际图片。不会更改衣服形态，也不将拼版标记为 AI 模特图。</p><div id="board-preview"></div>',footer:btn('关闭','board-close')+btn('生成并下载 JPG','board-create',true),bind:()=>{$('#board-close').onclick=F.closeModal;$('#board-create').onclick=safe(async()=>{const title=$('#board-title').value.trim().slice(0,30)||l.name,img=await boardImage(l,$('#board-bg').value,title);$('#board-preview').innerHTML='<img style="width:100%;margin-top:15px;border-radius:8px" src="'+img+'" alt="生成的商品拼版">';const blob=await(await fetch(img)).blob();F.download(blob,title+'.jpg');F.log('下载商品拼版',l.name);});}});
 $('#studio-original').onclick=safe(()=>{F.commit('采用原图拼版',s=>{const look=s.looks.find(l=>l.id===studioLook);look.imageId=null;look.imageMode='original';});F.notify('当前候选将采用商品原图拼版交付');});$$('[data-job-filter]').forEach(b=>b.onclick=()=>{filterJob=b.dataset.jobFilter;F.render();});$$('[data-review]').forEach(b=>b.onclick=safe(()=>reviewJob(b.dataset.review)));$$('[data-cancel-job]').forEach(b=>b.onclick=safe(()=>{F.commit('取消图片任务',s=>{const j=s.imageJobs.find(j=>j.id===b.dataset.cancelJob);j.status='cancelled';j.message='用户取消，未计费。';});F.render();}));$$('[data-retry-job]').forEach(b=>b.onclick=safe(()=>{const j=s.imageJobs.find(j=>j.id===b.dataset.retryJob);studioLook=j.lookId;newJob(j.lookId,j.kind);F.render();}));$$('[data-download-job]').forEach(b=>b.onclick=safe(async()=>{const j=F.state.imageJobs.find(j=>j.id===b.dataset.downloadJob);if(j.status==='stale')throw Error('关联商品已变化，请重新复核图片后下载');const blob=await(await fetch(j.image)).blob();F.download(blob,'搭配图-'+j.id+(blob.type==='image/jpeg'?'.jpg':'.png'));}));
};
function quoteSettings(){const q=F.state.quote;return select('报价方式','q-mode',[['alternatives','备选报价 · 客户择一'],['combined','合并采购 · 全部购买']],q.mode)+select('优惠方式','q-discount-type',[['percent','优惠百分比'],['fixed','固定优惠金额']],q.discountType)+field(q.discountType==='percent'?'优惠率（%）· 5 代表 95 折':'优惠金额（元）','q-discount',q.discountType==='fixed'?(q.discount/100).toFixed(2):q.discount,'number','min="0" step="0.01"')+field('运费 / 其他费用（元）','q-fee',(q.fee/100).toFixed(2),'number','min="0" step="0.01"')+select('税费口径','q-tax',[['included','已含税 · 不再加税'],['excluded','未税 · 按税率加税']],q.taxMode)+ (q.taxMode==='excluded'?field('税率（%）','q-rate',q.taxRate,'number','min="0" max="100" step="0.01"')+select('费用税费口径','q-fee-tax',[['true','应税费用 · 按上方税率加税'],['false','已含税 / 不再加税']],String(q.feeTaxable!==false)):'')+field('报价有效期（天）','q-days',q.validDays,'number','min="1" max="30"')+'<label class="field"><span>对客报价说明</span><textarea id="q-note" rows="3">'+E(q.note)+'</textarea></label>'+btn('应用报价条件','quote-apply',true,'check');}
F.pages.quotes=()=>{const s=F.state,q=F.quoteGroups();F.main.innerHTML=head('QUOTE WITH CONFIDENCE','确认一份有据可依的报价','金额按分核算；确认后固化商品、尺码、图片与价格版本。',btn('负责人例外','quote-exception',false,'shield-check')+btn('确认版本并去交付','quote-confirm',true,'check-check'));
 if(!s.looks.length){F.main.insertAdjacentHTML('beforeend',empty('还没有搭配可供报价','完成需求确认并生成一至四品类候选。','looks','开始搭配'));$('#quote-confirm').disabled=true;$('#quote-exception').disabled=true;return;}
 F.main.insertAdjacentHTML('beforeend','<div class="quote-layout"><div><div class="notice '+(q.errors.length?'warn':'')+'">'+(q.errors.length?'<b>确认前需要处理 '+q.errors.length+' 项</b><ul>'+q.errors.slice(0,12).map(e=>'<li>'+E(e)+'</li>').join('')+'</ul>'+(q.errors.length>12?'另有 '+(q.errors.length-12)+' 项，请逐候选检查。':''):'已完成数量、价格、库存、预算与折扣检查。可以确认报价版本。')+'</div><div class="panel"><div class="panel-head"><div><h2>'+E(s.brief.title)+'</h2><p>'+E(s.clients.find(c=>c.id===s.brief.clientId)?.name)+' · '+(s.quote.mode==='alternatives'?'各方案独立报价，不相加':'合并为一个采购订单，费用只收一次')+'</p></div><span class="badge">价格 v'+s.priceVersion+' / 库存 v'+s.stockVersion+'</span></div>'+q.groups.map(g=>'<details class="quote-detail" open><summary><strong>'+E(g.name)+'</strong><span>'+F.money(g.total)+'</span></summary><div class="table-wrap"><table><thead><tr><th>商品 / SKU</th><th>尺码</th><th>数量</th><th>单价</th><th>金额</th></tr></thead><tbody>'+g.lines.map(l=>'<tr><td><strong>'+E(l.name)+'</strong><br><span class="tiny muted">'+E(l.sku)+' / '+E(l.color)+'</span></td><td>'+E(l.size)+'</td><td>'+l.qty+'</td><td>'+F.money(l.price)+'</td><td>'+F.money(l.amount)+'</td></tr>').join('')+'</tbody></table></div><div class="money-row"><span>商品小计</span><b>'+F.money(g.subtotal)+'</b></div><div class="money-row"><span>优惠</span><b>− '+F.money(g.discount)+'</b></div><div class="money-row"><span>运费 / 其他费用</span><b>'+F.money(g.fee)+'</b></div>'+(s.quote.taxMode==='excluded'?'<div class="money-row"><span>税额（'+s.quote.taxRate+'%）</span><b>'+F.money(g.tax)+'</b></div>':'')+'<div class="money-row total"><span>报价总额</span><b>'+F.money(g.total)+'</b></div><p class="tiny">'+g.imageLabel+' · '+g.qty+' 套'+(s.quote.mode==='alternatives'?' · 约 '+F.money(g.perSet)+' / 套':' · 各套构成见明细')+'</p></details>').join('<div class="divider"></div>')+'</div><div class="notice">库存更新于 '+date(s.stockAsOf)+'。报价确认不锁定库存，订单确认前需再次核实；备选方案不可汇总为客户应付金额。</div></div><aside class="panel quote-summary"><div class="panel-head"><h2>报价条件</h2>'+F.icon('sliders-horizontal')+'</div>'+quoteSettings()+'<div class="notice">销售优惠上限 10%。超限由负责人注明原因，授权随本方案修改失效。</div></aside></div>');
 let dirty=false;$$('.quote-summary input,.quote-summary select,.quote-summary textarea').forEach(i=>i.addEventListener('input',()=>dirty=true));
 const apply=()=>{const type=$('#q-discount-type').value,discount=type==='percent'?Number($('#q-discount').value):F.parseMoney($('#q-discount').value);if(!/^\d+(\.\d{1,2})?$/.test($('#q-discount').value)||!Number.isFinite(discount)||discount<0||(type==='percent'&&discount>100))throw Error('优惠值无效，最多两位小数');const fee=F.parseMoney($('#q-fee').value),validDays=F.integer($('#q-days').value,'有效期',1,30),taxMode=$('#q-tax').value,taxText=$('#q-rate')?.value??String(s.quote.taxRate),taxRate=Number(taxText);if(!/^\d+(\.\d{1,2})?$/.test(taxText)||taxRate<0||taxRate>100)throw Error('税率须为0–100%，最多两位小数');const next={...F.state.quote,mode:$('#q-mode').value,discountType:type,discount,fee,taxMode,taxRate,feeTaxable:$('#q-fee-tax')?$('#q-fee-tax').value==='true':s.quote.feeTaxable!==false,validDays,note:$('#q-note').value,exception:null};F.commit('应用报价条件',s=>s.quote=next);dirty=false;};
 F.main.querySelector('.page-heading .actions').insertAdjacentHTML('afterbegin',btn('核对尺码配比','quote-sizes',false,'ruler'));
 $('#quote-sizes').onclick=()=>F.modal({title:'确认客户实际尺码配比',body:'<p>下列数值最初按库存作参考分配。请与客户实际尺码需求逐一核对；需要更改时返回搭配页调整。</p>'+F.state.looks.filter(l=>l.selected).map(l=>'<div class="notice"><b>'+E(l.name)+' · '+l.qty+' 套</b><br>'+l.productIds.map(id=>E(F.product(id).name)+'：'+Object.entries(l.allocations[id]).map(([size,n])=>E(size)+' × '+n).join(' / ')).join('<br>')+'</div>').join('')+'<label class="check"><input id="size-attest" type="checkbox">已据客户需求核对以上每件商品的实际尺码数量</label>',footer:btn('确认配比','size-confirm',true),bind:()=>{$('#size-confirm').onclick=safe(()=>{if(!$('#size-attest').checked)throw Error('请先核对并勾选确认');F.commit('确认客户尺码配比',s=>{s.looks.filter(l=>l.selected).forEach(l=>{l.allocationsConfirmed=true;l.allocationsConfirmedAt=new Date().toISOString();});s.quote.exception=null;});F.closeModal();F.render();});}});
 $('#quote-apply').onclick=safe(()=>{apply();F.render();F.notify('报价已重新核算');});$('#q-discount-type').onchange=safe(()=>{F.commit('切换优惠方式',s=>{s.quote.discountType=$('#q-discount-type').value;s.quote.discount=0;s.quote.exception=null;});F.render();});$('#q-tax').onchange=safe(()=>{apply();F.render();});$('#quote-confirm').onclick=safe(()=>{if(dirty)throw Error('报价条件已编辑，请先应用报价条件后再确认');if(F.quoteGroups().errors.length)throw Error('请先处理报价检查中的问题');const snapshot=F.createSnapshot();F.delivery?.selectSnapshot(snapshot.id);F.notify('报价快照已确认：'+snapshot.id);F.go('delivery');});$('#quote-exception').onclick=safe(()=>{if(dirty)throw Error('请先应用当前报价条件');F.requireRole(['manager','admin']);F.modal({title:'负责人确认报价例外',body:'<p>例外在24小时内仅对当前商品、价格、数量与优惠有效。修改后自动失效；库存、数量和零额报价不能绕过。</p><label class="field" style="margin-top:18px"><span>业务原因</span><textarea id="exception-reason" rows="3"></textarea></label>',footer:btn('确认此版本例外','exception-save',true),bind:()=>{$('#exception-save').onclick=safe(()=>{F.approveException($('#exception-reason').value);F.closeModal();F.render();});}});});
};
function customerDialog(id){const c=F.state.clients.find(c=>c.id===id)||{id:F.uid('client'),name:'',person:'',type:'企业团购',city:'',priceTable:'批发价',note:''};F.modal({title:id?'编辑客户资料':'添加客户',body:'<div class="grid two">'+field('客户名称','c-name',c.name)+field('联系人','c-person',c.person)+select('客户类型','c-type',['企业团购','服装批发'],c.type)+field('所在城市','c-city',c.city)+field('指定价格表','c-price',c.priceTable)+'</div><label class="field"><span>内部服务备注</span><textarea id="c-note">'+E(c.note)+'</textarea><small>内部备注不会进入对客快照与 PPT。</small></label><div class="notice">指定表缺少 SKU 价格时阻断报价，不回退到批发价。可在数据导入维护相应表。</div>',footer:btn('保存客户','c-save',true),bind:()=>{$('#c-save').onclick=safe(()=>{const name=$('#c-name').value.trim(),person=$('#c-person').value.trim();if(!name||!person)throw Error('客户名称和联系人不能为空');const next={...c,name,person,type:$('#c-type').value,city:$('#c-city').value,priceTable:$('#c-price').value.trim()||'批发价',note:$('#c-note').value};F.commit('保存客户资料',s=>{const at=s.clients.findIndex(c=>c.id===id);if(at<0)s.clients.push(next);else s.clients[at]=next;s.quote.exception=null;});F.closeModal();F.render();});}});}
F.pages.customers=()=>{F.main.innerHTML=head('RELATIONSHIPS','客户管理','维护客户偏好与销售价格表，让每份方案更贴近客户。',btn('添加客户','customer-add',true,'plus'))+'<div class="grid three">'+F.state.clients.map(c=>'<article class="customer-card"><div class="customer-avatar">'+E(c.name.slice(0,1))+'</div><h3>'+E(c.name)+'</h3><p>'+E(c.person)+' · '+E(c.city)+'</p><div class="actions" style="margin-top:12px"><span class="badge">'+E(c.type)+'</span><span class="badge neutral">'+E(c.priceTable)+'</span></div><p style="margin-top:16px;min-height:45px">'+E(c.note||'暂无服务备注')+'</p><div class="actions"><button class="btn small" data-customer="'+c.id+'">编辑客户</button><button class="btn small primary" data-client-project="'+c.id+'">新建方案</button></div></article>').join('')+'</div>';$('#customer-add').onclick=()=>customerDialog();$$('[data-customer]').forEach(b=>b.onclick=()=>customerDialog(b.dataset.customer));$$('[data-client-project]').forEach(b=>b.onclick=safe(()=>{const c=F.state.clients.find(c=>c.id===b.dataset.clientProject);F.newProject(c.name+' · 新选品方案',c.id);F.go('brief');}));};
F.pages.settings=()=>{const s=F.state;F.main.innerHTML=head('WORKSPACE SETTINGS','工作台设置','管理演示角色、报价时效、企业展示和本地备份。')+'<div class="grid two"><section class="panel"><div class="panel-head"><h2>角色与业务默认值</h2>'+F.icon('users-round')+'</div>'+select('当前演示角色','set-role',[['sales','销售 / 选品'],['operator','商品运营'],['manager','业务负责人'],['admin','管理员']],s.role)+field('库存有效时长（小时）','set-ttl',s.settings.stockTTL,'number','min="1" max="168"')+'<div class="notice">角色切换用于体验权限流程。真实用户和服务端鉴权将在生产接入中实现，本地界面不构成安全边界。</div>'+btn('保存设置','settings-save',true)+'</section><section class="panel"><div class="panel-head"><h2>企业展示</h2>'+F.icon('building-2')+'</div><p class="small-text">品牌、颜色、Logo 与联系方式在交付页维护，确认报价时固化到对应版本。</p><div class="divider"></div><h3>'+E(s.settings.template.brand)+'</h3><p class="small-text">'+E(s.settings.template.contact)+'<br>'+E(s.settings.template.phone)+'</p><button class="btn secondary" style="margin-top:20px" data-go="delivery">编辑交付模板</button></section><section class="panel"><div class="panel-head"><h2>本地数据与恢复</h2>'+F.icon('hard-drive-download')+'</div><p class="small-text">方案、图片与报价保存在当前浏览器。备份包含内部客户资料，恢复会整体替换当前工作区；请先下载备份。</p><div class="actions" style="margin-top:20px">'+btn('下载完整备份','backup')+btn('恢复备份','restore')+btn('重置示例','reset')+'</div><input hidden id="restore-file" type="file" accept=".json"><div class="notice warn">清理浏览器存储会丢失本地数据。此原型没有云端同步或多人协作。</div></section><section class="panel"><div class="panel-head"><h2>最近操作</h2><span class="badge neutral">'+s.audit.length+' 条记录</span></div><ul class="plain-list">'+s.audit.slice(0,8).map(a=>'<li><b>'+E(a.action)+'</b><br><span class="tiny muted">'+date(a.at)+' · '+E(a.role)+'</span></li>').join('')+'</ul></section></div>';
 $('#settings-save').onclick=safe(()=>{const ttl=F.integer($('#set-ttl').value,'库存时长',1,168),role=$('#set-role').value;F.commit('更新工作台设置',s=>{s.role=role;s.settings.stockTTL=ttl;});F.render();F.notify('设置已保存');});$('#backup').onclick=F.backup;$('#restore').onclick=()=>$('#restore-file').click();$('#restore-file').onchange=safe(async e=>{const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024)throw Error('备份文件不能超过5MB');const raw=await file.text();F.modal({title:'恢复本地备份',body:'<p>将用所选备份整体替换当前工作区。请先下载现有备份，恢复后仍可用备份找回。</p>',footer:btn('先下载当前备份','restore-backup')+btn('确认恢复','restore-confirm',true),bind:()=>{$('#restore-backup').onclick=F.backup;$('#restore-confirm').onclick=safe(()=>{F.restore(raw);F.closeModal();F.go('dashboard');F.notify('备份已恢复');});}});});$('#reset').onclick=()=>F.modal({title:'重置到示例工作区',body:'<p>将替换当前本地方案、商品更新、图片和报价记录。下载备份后可以恢复。本操作不影响文件系统中的导出文件。</p>',footer:btn('先下载备份','reset-backup')+btn('确认重置示例','reset-confirm',true),bind:()=>{$('#reset-backup').onclick=F.backup;$('#reset-confirm').onclick=safe(()=>{F.restore(JSON.stringify(F.initial()));F.closeModal();F.go('dashboard');});}});
};
F.enhance=()=>{
 $('#sidebar').inert=window.innerWidth<=800&&!$('#sidebar').classList.contains('open');$('#menu-toggle').setAttribute('aria-expanded',String($('#sidebar').classList.contains('open')));$('#menu-toggle').onclick=()=>{const open=$('#sidebar').classList.toggle('open');$('#sidebar').inert=!open&&window.innerWidth<=800;$('#menu-toggle').setAttribute('aria-expanded',String(open));};
 $('#sidebar .sidebar-bottom').insertAdjacentHTML('beforeend','<div style="margin-top:12px"><a href="documents/prd.html" target="_blank">PRD</a> · <a href="documents/research.html" target="_blank">市场调研</a> · <a href="documents/implementation.html" target="_blank">实施规格</a></div>');
 if(F.route==='brief'){const input=$('#brief-budget');input.placeholder='留空表示不设预算上限';if(F.state.brief.budget===null)input.value='';$('#brief-qty').max='100000';$$('[name=brief-group]').forEach(i=>{const t=F.state.brief.groupSlots?.[i.value]||F.categories.slice(0,Number(i.value));i.closest('label').querySelector('.tiny').textContent=t.join(' + ');});}
 if(F.route==='settings')F.advanced?.renderSettings();
 if(F.route==='looks'){
   $$('.look-card').forEach(card=>{const id=card.querySelector('[data-edit-look]').dataset.editLook;const l=F.state.looks.find(l=>l.id===id),same=F.state.looks.filter(x=>x.group===l.group),at=same.indexOf(l);card.querySelector('.look-body').insertAdjacentHTML('beforeend','<div class="actions" style="margin-top:12px"><button class="btn small ghost" data-reroll="'+id+'">'+F.icon('shuffle')+' 保持锁定重搭</button><button class="btn small" data-order-look="'+id+'" data-dir="-1" '+(at===0?'disabled':'')+' aria-label="上移此候选">↑</button><button class="btn small" data-order-look="'+id+'" data-dir="1" '+(at===same.length-1?'disabled':'')+' aria-label="下移此候选">↓</button></div>');});
   $$('[data-reroll]').forEach(b=>b.onclick=safe(()=>{F.rerollLook(b.dataset.reroll);F.render();F.notify('已保持锁定商品重新搭配；请核对尺码与图片');}));
   $$('[data-order-look]').forEach(b=>b.onclick=safe(()=>{F.commit('调整候选展示顺序',s=>{const l=s.looks.find(l=>l.id===b.dataset.orderLook),same=s.looks.filter(x=>x.group===l.group),other=same[same.indexOf(l)+Number(b.dataset.dir)];if(!other)return;const a=s.looks.indexOf(l),c=s.looks.indexOf(other);[s.looks[a],s.looks[c]]=[s.looks[c],s.looks[a]];s.quote.exception=null;});F.render();}));
   const expected=F.state.brief.groups.length*F.state.brief.perGroup;if(F.state.looks.length&&F.state.looks.length<expected)F.main.querySelector('.page-heading').insertAdjacentHTML('afterend','<div class="notice warn">找到 '+F.state.looks.length+' 个符合价格、库存、时效及预算的不同组合，少于目标 '+expected+' 个。可调整需求或补充商品后重试。</div>');
 }
 if(F.route==='studio'&&$('#studio-generate')){
   $('#studio-generate').innerHTML=F.icon('sparkles')+'创建图片任务';$('#studio-generate').parentElement.insertAdjacentHTML('afterend','<p class="tiny muted" style="margin-top:10px">剩余 '+F.state.settings.credits+' 演示积分 · 每张模特示例预留1积分；电商拼版和外部上传不消耗积分，不发生收费。</p>');
   $('#studio-generate').onclick=safe(()=>{const count=Number($('#studio-count').value),kind=$('#studio-kind').value;if(F.state.imageJobs.some(j=>j.lookId===studioLook&&j.kind===kind&&['queued','running'].includes(j.status)))throw Error('此搭配已有相同用途任务正在处理，请等待或取消，避免重复提交');if(kind==='model'&&F.state.settings.credits<count)throw Error('演示积分不足，本次未提交任务');for(let i=0;i<count;i++)newJob(studioLook,kind);F.render();});
   $$('[data-cancel-job]').forEach(b=>b.onclick=safe(()=>{F.commit('取消图片任务',s=>{const j=s.imageJobs.find(j=>j.id===b.dataset.cancelJob);if(!['queued','running'].includes(j.status))throw Error('任务状态已变化');j.status='cancelled';refundJob(s,j);j.message='用户取消，演示积分已释放；不发生收费。';});F.render();}));
   $$('[data-retry-job]').forEach(b=>b.onclick=safe(()=>{const j=F.state.imageJobs.find(j=>j.id===b.dataset.retryJob);if(F.state.imageJobs.some(x=>x.lookId===j.lookId&&x.kind===j.kind&&['queued','running'].includes(x.status)))throw Error('同一搭配任务正在准备，请勿重复重试');studioLook=j.lookId;newJob(j.lookId,j.kind);F.render();}));
 }
};
window.addEventListener('storage',event=>{if(event.key===F.storageKey){F.notify('另一标签页已更新工作区。当前输入保留；请先备份草稿，再刷新加载新版本。','error');}});
window.addEventListener('resize',()=>{$('#sidebar').inert=window.innerWidth<=800&&!$('#sidebar').classList.contains('open');});
window.addEventListener('hashchange',()=>F.go(location.hash.slice(1)));
// 刷新时不把尚未完成的演示任务伪装成成功，可重试恢复。
if(F.state.imageJobs.some(j=>['running','queued'].includes(j.status))){F.commit('恢复中断的图片任务',s=>s.imageJobs.filter(j=>['running','queued'].includes(j.status)).forEach(j=>{j.status='failed';refundJob(s,j);j.message='页面刷新中断了本地任务，演示积分已释放，可重新准备。';}));}
F.go(location.hash.slice(1)||'dashboard');if(F.loadError)F.notify(F.loadError,'error');
})();
