/* Playwright 验证使用独立浏览器与127.0.0.1临时端口，结束自动关闭。 */
const {chromium}=require('C:/Users/admin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const root=__dirname,out=path.join(root,'verification');fs.mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.json':'application/json'};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(req.url.split('?')[0]),file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const record=(name)=>checks.push(name);try{
 await page.goto('http://127.0.0.1:'+server.address().port,{waitUntil:'networkidle'});await page.screenshot({path:path.join(out,'dashboard-desktop.png'),fullPage:true});record('首页实际渲染');
 for(const route of ['projects','brief','looks','studio','quotes','delivery','catalog','imports','media','customers','settings']){await page.evaluate(route=>F.go(route),route);assert.ok(await page.locator('h1').count(),route+'标题存在');assert.equal(await page.locator('#main').innerText().then(t=>t.includes('页面暂时无法显示')),false,route+'无错误页');}record('12个页面可访问');
 await page.evaluate(()=>F.go('looks'));await page.click('#looks-generate');assert.equal(await page.evaluate(()=>F.state.looks.length),8);assert.equal(await page.locator('.look-card').count(),2);record('1至4品类各2个候选');await page.screenshot({path:path.join(out,'looks-desktop.png'),fullPage:true});
 await page.locator('[data-edit-look]').first().click();await page.locator('[data-alloc-product]').first().fill('0');await page.click('#edit-save');await page.locator('#look-error .notice').waitFor();assert.ok(await page.locator('#modal').evaluate(e=>e.open));await page.click('#edit-cancel');record('尺码缺配阻断并保留输入');
 await page.locator('[data-studio-look]').first().click();await page.selectOption('#studio-count','1');await page.click('#studio-generate');await page.locator('[data-review]').first().waitFor({timeout:10000});await page.locator('[data-review]').first().click();await page.click('#review-approve');assert.ok((await page.locator('#notifications').innerText()).includes('完成每项复核'));await page.locator('[name=review-check]').evaluateAll(els=>els.forEach(e=>e.click()));await page.click('#review-approve');assert.equal(await page.evaluate(()=>F.state.imageJobs[0].status),'approved');record('模特样例任务与逐件复核');
 await page.click('#studio-board');const boardDownload=page.waitForEvent('download');await page.click('#board-create');const board=await boardDownload;await board.saveAs(path.join(out,'商品拼版.jpg'));assert.ok(fs.statSync(path.join(out,'商品拼版.jpg')).size>10000);await page.click('#board-close');record('实际生成并下载拼版JPG');
 await page.evaluate(()=>F.go('quotes'));assert.ok(await page.evaluate(()=>F.quoteGroups().errors.some(e=>e.includes('尺码配比'))));await page.click('#quote-sizes');await page.check('#size-attest');await page.click('#size-confirm');assert.equal(await page.evaluate(()=>F.quoteGroups().errors.length),0);await page.click('#quote-confirm');assert.equal(await page.evaluate(()=>F.state.snapshots.length),1);record('确认尺码配比后持久化报价快照');await page.screenshot({path:path.join(out,'delivery-desktop.png'),fullPage:true});
 await page.reload({waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>F.state.snapshots.length),1);record('刷新后报价及方案恢复');
 for(const route of ['dashboard','brief','looks','studio','quotes','delivery','catalog','imports','media','customers','settings']){await page.setViewportSize({width:390,height:844});await page.evaluate(route=>F.go(route),route);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);assert.equal(overflow,false,route+'移动端页面无整体横溢出');}record('11页面390px无整体溢出');
 await page.evaluate(()=>F.go('looks'));await page.screenshot({path:path.join(out,'looks-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{document.documentElement.style.fontSize='28px';F.go('brief');});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);record('字体放大与减少动画模式');
 assert.deepEqual(errors,[],'无浏览器脚本或资源错误');record('浏览器控制台与资源无错误');
 }finally{fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({at:new Date().toISOString(),checks,errors},null,2));await browser.close();server.close();}console.log(JSON.stringify({passed:checks.length,checks,errors}));})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
