/* 金额、库存、图片与报价版本的统一业务内核。原型状态只保存在当前浏览器。 */
(function(root){
  'use strict';
  const F=root.F={pages:{},route:'dashboard',clone:v=>JSON.parse(JSON.stringify(v))};
  const KEY='zhixuan-fashion-v2';
  F.uid=p=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
  F.esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  F.money=n=>Number.isSafeInteger(n)?'¥'+(n/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}):'待补价';
  F.parseMoney=t=>{if(!/^(0|[1-9]\d{0,8})(\.\d{1,2})?$/.test(String(t).trim()))throw Error('金额须为非负数，最多两位小数');const[a,b='']=String(t).trim().split('.');return Number(a)*100+Number(b.padEnd(2,'0'));};
  F.percentOf=(amount,rate)=>Number((BigInt(amount)*BigInt(F.parseMoney(String(rate)))+5000n)/10000n);
  F.integer=(v,label='数量',min=0,max=1000000)=>{if(!/^\d+$/.test(String(v))||Number(v)<min||Number(v)>max)throw Error(label+'须为 '+min+'–'+max+' 的整数');return Number(v);};
  const categories=['上衣','裤子','帽子','鞋']; F.categories=categories;
  F.defaultTemplates=()=>Object.fromEntries([1,2,3,4].map(n=>[n,categories.slice(0,n)]));
  const names=[['米杏珠地短袖 Polo','苔绿直筒休闲裤','苔绿简约棒球帽','米白轻量休闲鞋'],['藏蓝商务短袖 Polo','卡其直筒休闲裤','藏蓝简约棒球帽','藏蓝拼色休闲鞋'],['鼠尾草纯棉 T 恤','炭灰直筒休闲裤','浅卡其棒球帽','灰白轻量休闲鞋']];
  const colors=[['米杏','苔绿','苔绿','米白'],['藏蓝','卡其','藏蓝','藏蓝'],['鼠尾草','炭灰','浅卡其','灰白']];
  function initial(){
    const now=new Date().toISOString();
    const products=names.flatMap((row,r)=>row.map((name,c)=>{const id='p'+r+c,price=[[8000,6000,2000,9000],[9200,6800,2200,9900],[6500,7200,1800,8500]][r][c];return{id,sku:'ZX-'+(r+1)+(c+1),style:'ZX'+(r+1)+(c+1),name,category:categories[c],color:colors[r][c],unit:c===3?'双':c===2?'顶':'件',price,source:'演示供应商',warehouse:'主仓',sizes:(c===2?['均码']:c===3?['39','40','41','42','43']:['M','L','XL']).map((size,i)=>({sku:'ZX-'+(r+1)+(c+1)+'-'+size,size,stock:220+i*30,price,stockAsOf:now,priceAsOf:now})),image:'assets/catalog-grid.png',crop:{x:c/4,y:r/3,w:1/4,h:1/3},imageVersion:1,imageAllowed:true,status:'active',tags:r===0?['休闲','团建']:r===1?['商务','通勤']:['休闲','户外'],season:'四季',material:c===3?'织物 / 橡胶':'棉混纺',jdId:'',jdUrl:'',confirmed:true};}));
    return{schema:2,revision:1,role:'sales',productVersion:1,priceVersion:1,stockVersion:1,priceAsOf:now,stockAsOf:now,products,clients:[{id:'client-1',name:'森禾企业服务',person:'陈经理',type:'企业团购',city:'杭州',priceTable:'批发价',note:'秋季员工团建，优先舒适耐穿。'},{id:'client-2',name:'青屿商贸',person:'周女士',type:'服装批发',city:'广州',priceTable:'批发价',note:'门店秋季补货，偏好低饱和配色。'}],projectId:'project-1',projects:[],brief:{clientId:'client-1',title:'森禾 · 秋季团建服装方案',scene:'企业团建',style:'休闲',season:'四季',qty:100,budget:3000000,groups:[1,2,3,4],perGroup:2,progressive:true,exclude:'',text:'给森禾准备100套秋季团建服装，预算每套300元。上衣、裤子、帽子和鞋，提供一到四品类的递进比较。',confirmed:true},looks:[],quote:{mode:'alternatives',discountType:'percent',discount:5,fee:30000,taxMode:'included',taxRate:13,validDays:7,note:'现货报价，以订单确认时库存为准。',exception:null},imageJobs:[],snapshots:[],batches:[],media:[],audit:[],history:[],settings:{brand:'织选',stockTTL:24,credits:120,contact:'销售顾问 林亦（示例）',phone:'400-000-0000',template:{brand:'织选',color:'294839',logo:'',contact:'销售顾问 林亦（示例）',phone:'400-000-0000',version:1}}};
  }
  F.initial=initial;
  try{const raw=root.localStorage?.getItem(KEY);F.state=raw?JSON.parse(raw):initial();if(F.state.schema!==2||!Array.isArray(F.state.products))throw Error('数据版本不兼容');}catch(e){F.state=initial();F.loadError='本地数据无法读取，已开启临时示例。原存储未覆盖，请先导出备份后恢复。';}
  let storedRevision=null;try{storedRevision=JSON.parse(root.localStorage?.getItem(KEY)||'null')?.revision??null;}catch{}
  function assertFresh(){if(!root.localStorage)return;let disk;try{disk=JSON.parse(root.localStorage.getItem(KEY)||'null')?.revision??null;}catch{throw Error('本地存储已变化且无法解析，请下载当前备份后恢复');}if(disk!==storedRevision)throw Error('另一标签页已更新工作区，当前修改未覆盖。请先备份当前草稿，再刷新加载最新版本');}
  function persist(state){if(!root.localStorage)return;const s=JSON.stringify(state);if(s.length>4200000)throw Error('本地存储接近容量上限，请导出备份并减少大图');root.localStorage.setItem(KEY,s);storedRevision=state.revision;}
  F.save=()=>{try{assertFresh();persist(F.state);}catch(e){F.notify?.(e.message,'error');throw e;}};
  F.commit=(action,mutator)=>{assertFresh();const next=F.clone(F.state);mutator(next);for(const j of next.imageJobs||[]){if(j.reserved&&['failed','cancelled','stale'].includes(j.status)){next.settings.credits+=j.points||0;j.reserved=false;}}next.revision++;next.audit.unshift({id:F.uid('audit'),at:new Date().toISOString(),role:next.role,action,detail:''});next.audit=next.audit.slice(0,250);persist(next);F.state=next;return next;};
  F.storageKey=KEY;
  F.log=(action,detail='')=>F.commit(action,s=>{s.audit.unshift({id:F.uid('event'),at:new Date().toISOString(),role:s.role,action,detail});});
  F.product=id=>F.state.products.find(p=>p.id===id);
  F.stock=p=>p?.sizes?.every(s=>Number.isInteger(s.stock))?p.sizes.reduce((a,s)=>a+s.stock,0):null;
  F.price=(p,size)=>{if(!p)return null;if(size===undefined){const prices=p.sizes.map(s=>F.price(p,s.size));return prices.every(Number.isSafeInteger)?Math.min(...prices):null;}const client=F.state.clients.find(c=>c.id===F.state.brief.clientId),table=client?.priceTable||'批发价';const row=p.sizes.find(s=>s.size===size);if(table!=='批发价')return row?.priceTables?.[table]??null;return row?.price??null;};
  F.skuRows=()=>F.state.products.filter(p=>p.status==='active').flatMap(p=>p.sizes.map(s=>({productId:p.id,sku:s.sku,size:s.size,name:p.name,category:p.category,color:p.color,price:F.price(p,s.size),stock:s.stock,source:p.source,warehouse:p.warehouse})));
  F.requireRole=roles=>{if(!roles.includes(F.state.role))throw Error('当前演示角色无此操作权限，请在设置中切换角色');};
  F.photo=(p,cls='')=>{if(!p?.image||p.imageAllowed===false)return '<div class="photo missing '+F.esc(cls)+'" role="img" aria-label="商品图片待补充">待补图</div>';const c=p.crop;return '<div class="photo '+F.esc(cls)+'">'+(c?'<img alt="'+F.esc(p.name)+'" src="'+F.esc(p.image)+'" style="max-width:none;width:'+(100/c.w)+'%;height:'+(100/c.h)+'%;left:'+(-100*c.x/c.w)+'%;top:'+(-100*c.y/c.h)+'%">':'<img alt="'+F.esc(p.name)+'" src="'+F.esc(p.image)+'">')+'</div>';};
  F.invalidateImages=(ids,reason,state=F.state)=>{state.imageJobs.filter(j=>Object.keys(j.productVersions||{}).some(id=>ids.includes(id))).forEach(j=>{j.status='stale';j.review=null;j.message=reason;});state.looks.filter(l=>l.productIds.some(id=>ids.includes(id))).forEach(l=>{l.imageId=null;l.imageMode='original';});};
  F.touch=(s,reason='方案内容已变更')=>{s.quote.exception=null;s.brief.confirmed=true;s.looks.forEach(l=>{if(l.imageId){const j=s.imageJobs.find(x=>x.id===l.imageId);if(!j||j.lookRevision!==l.revision){l.imageId=null;l.imageMode='original';}}});};
  F.allocate=(p,qty)=>{const out={};let left=qty;p.sizes.forEach((s,i)=>{const n=Math.min(s.stock??0,Math.ceil(left/(p.sizes.length-i)));out[s.size]=n;left-=n;});if(left>0)out[p.sizes[0].size]+=left;return out;};
  F.rerollLook=id=>{F.requireRole(['sales','manager','admin']);const old=F.state.looks.find(l=>l.id===id);if(!old)throw Error('候选不存在');let candidates=[[]];for(const pid of old.productIds){const p=F.product(pid),choices=old.locks.includes(pid)?[p]:F.state.products.filter(x=>x.category===p.category&&x.status==='active'&&x.confirmed&&x.imageAllowed);if(candidates.length*choices.length>5000)throw Error('候选过多，请先缩小范围');candidates=candidates.flatMap(ps=>choices.map(p=>[...ps,p]));}const choices=candidates.filter(ps=>ps.map(p=>p.id).join('|')!==old.productIds.join('|')).map(ps=>({...F.clone(old),productIds:ps.map(p=>p.id),allocations:Object.fromEntries(ps.map(p=>[p.id,old.locks.includes(p.id)?old.allocations[p.id]:F.allocate(p,old.qty)])),imageId:null,imageMode:'original',allocationsConfirmed:false,revision:old.revision+1})).filter(l=>!F.calcLook(l).errors.length);if(!choices.length)throw Error('保持锁定后没有其他满足预算和库存的组合，可先解锁部分商品');const next=choices[0];F.commit('保持锁定重新搭配',s=>{s.looks[s.looks.findIndex(l=>l.id===id)]=next;s.imageJobs.filter(j=>j.lookId===id).forEach(j=>{j.status='stale';j.message='候选重搭后需重新复核';});F.touch(s);});return next;};
  F.generateLooks=()=>{
    const b=F.state.brief;if(!b.confirmed)throw Error('请先确认客户需求');
    F.requireRole(['sales','manager','admin']);
    const by=categories.map(cat=>F.state.products.filter(p=>p.category===cat&&p.status==='active'&&p.confirmed&&p.imageAllowed&&F.stock(p)>=b.qty&&p.sizes.every(s=>Number.isSafeInteger(F.price(p,s.size))&&F.price(p,s.size)>0)&&(!b.exclude||!b.exclude.split(/[,，、\s]+/).some(k=>k&&(p.name+p.color+p.tags.join('')).includes(k)))&&(b.season==='四季'||p.season==='四季'||p.season===b.season)).sort((a,c)=>Number(c.tags.includes(b.style))-Number(a.tags.includes(b.style))));
    const looks=[];for(const group of b.groups){const slots=b.groupSlots?.[group]||categories.slice(0,group);if(slots.length!==group||new Set(slots).size!==group||slots.some(c=>!categories.includes(c)))throw Error('组合模板槽位无效，请检查管理员配置');const groupLists=slots.map(cat=>by[categories.indexOf(cat)]);if(groupLists.some(ps=>!ps.length))throw Error(group+' 品类缺少满足库存、图片、价格或排除条件的商品');let combinations=[{ps:[],ranks:[]}];for(const list of groupLists){if(combinations.length*list.length>5000)throw Error('组合超过本地演示5000项搜索上限，请缩小商品范围后重试');combinations=combinations.flatMap(x=>list.map((p,i)=>({ps:[...x.ps,p],ranks:[...x.ranks,i]})));}const score=x=>x.ranks.reduce((a,n)=>a+n,0)+(new Set(x.ranks).size-1)*(b.progressive?10:0);combinations.sort((a,c)=>score(a)-score(c));let found=0;for(const {ps} of combinations){const look={id:F.uid('look'),name:group+' 品类 · '+(found===0?'舒适优选':found===1?'质感备选':'风格补充'),group,productIds:ps.map(p=>p.id),locks:b.progressive?ps.slice(0,-1).map(p=>p.id):[],manualLocks:[],selected:true,qty:b.qty,allocations:Object.fromEntries(ps.map(p=>[p.id,F.allocate(p,b.qty)])),reason:'符合'+b.scene+' / '+b.style+'，'+(b.progressive?'优先保留基础款递进；锁定项可手动解锁调整。':'独立组合，可逐件调整。'),revision:1,imageId:null,imageMode:'original'};if(!F.calcLook(look).errors.length){looks.push(look);found++;if(found>=b.perGroup)break;}}}
    if(!looks.length)throw Error('没有满足预算、尺码与库存时效的组合，请调整条件或更新数据');
    looks.forEach(l=>l.allocationsConfirmed=false);F.commit('生成搭配候选',s=>{s.brief.groupSlots||=F.defaultTemplates();s.brief.templateVersion||=1;s.looks=looks;F.touch(s);});return looks;
  };
  F.calcLook=(look,financial=true)=>{
    const errors=[],lines=[];if(!Number.isInteger(look.qty)||look.qty<=0)errors.push('采购套数必须为正整数');
    if(new Set(look.productIds).size!==look.group||look.productIds.length!==look.group)errors.push('品类数或商品重复');
    const cats=[];
    for(const id of look.productIds){const p=F.product(id);if(!p){errors.push('商品不存在');continue;}cats.push(p.category);if(p.status!=='active')errors.push(p.name+'未上架');if(!p.confirmed||!p.imageAllowed||!p.image)errors.push(p.name+'图片未确认或禁用');
      const allocation=look.allocations[id]||{};const sum=Object.values(allocation).reduce((a,n)=>a+Number(n),0);if(sum!==look.qty)errors.push(p.name+'尺码合计 '+sum+'，须等于 '+look.qty+' 套');
      for(const [size,qty] of Object.entries(allocation)){if(!Number.isInteger(qty)||qty<0){errors.push(p.name+'尺码数量不合法');continue;}if(!qty)continue;const sku=p.sizes.find(x=>x.size===size);if(!sku){errors.push(p.name+'尺码不存在');continue;}const price=F.price(p,size);if(!Number.isSafeInteger(price)||price<=0){errors.push(sku.sku+'缺少客户指定价格或零价待核实');continue;}if(!Number.isInteger(sku.stock)||qty>sku.stock)errors.push(sku.sku+'库存不足或未更新');const asOf=Date.parse(sku.stockAsOf||F.state.stockAsOf);if(!Number.isFinite(asOf)||asOf>Date.now()+300000||Date.now()-asOf>F.state.settings.stockTTL*3600000)errors.push(sku.sku+'库存时间无效或超过 '+F.state.settings.stockTTL+' 小时，需全量刷新');lines.push({productId:id,imageVersion:p.imageVersion,sku:sku.sku,size,name:p.name,category:p.category,color:p.color,unit:p.unit,qty,price,amount:price*qty,image:p.image,crop:p.crop,source:p.source,warehouse:p.warehouse});}
    }
    if(new Set(cats).size!==look.group)errors.push('每套只能有一个同类商品');
    const table=F.state.clients.find(c=>c.id===F.state.brief.clientId)?.priceTable||'批发价';for(const line of lines){const row=F.product(line.productId).sizes.find(s=>s.sku===line.sku),taxMode=table==='批发价'?(row.priceTaxMode||'included'):(row.priceTableTaxModes?.[table]||'included');if(taxMode!==F.state.quote.taxMode)errors.push(line.sku+'价格表税费口径与报价不一致，请使用对应含税/未税价格表');}
    if(look.imageMode==='model'){const j=F.state.imageJobs.find(j=>j.id===look.imageId);if(!j||j.status!=='approved'||j.lookRevision!==look.revision||Object.entries(j.productVersions).some(([id,v])=>F.product(id)?.imageVersion!==v||!F.product(id)?.imageAllowed))errors.push('采用图已失效，请重新复核或改用原图拼版');}
    const subtotal=lines.reduce((a,l)=>a+l.amount,0);const totals=financial?F.totals(subtotal):{subtotal,discount:0,fee:0,tax:0,total:subtotal,errors:[]};errors.push(...totals.errors);
    if(financial&&F.state.brief.budget!==null&&totals.total>F.state.brief.budget)errors.push('总额超过客户预算 '+F.money(F.state.brief.budget));
    return{lines,...totals,subtotal,perSet:look.qty?Math.round(totals.total/look.qty):0,errors:[...new Set(errors)]};
  };
  F.totals=subtotal=>{const q=F.state.quote,errors=[];let discount=0;
    if(q.discountType==='fixed'){if(!Number.isSafeInteger(q.discount)||q.discount<0)errors.push('固定优惠金额无效');else discount=q.discount;}else if(!Number.isFinite(q.discount)||q.discount<0||q.discount>100||!/^\d+(\.\d{1,2})?$/.test(String(q.discount)))errors.push('优惠率须为 0–100%，最多两位小数');else discount=F.percentOf(subtotal,q.discount);
    if(discount>subtotal)errors.push('优惠不能超过商品金额');else if(discount===subtotal)errors.push('优惠后商品金额必须大于零');const fee=q.fee;if(!Number.isSafeInteger(fee)||fee<0)errors.push('运费无效');const base=subtotal-discount+(fee||0);let tax=0;
    if(q.taxMode==='excluded'){if(!Number.isFinite(q.taxRate)||q.taxRate<0||q.taxRate>100||!/^\d+(\.\d{1,2})?$/.test(String(q.taxRate)))errors.push('税率须为 0–100%，最多两位小数');else if(base>=0)tax=F.percentOf(subtotal-discount+(q.feeTaxable===false?0:fee),q.taxRate);}const total=base+tax;if(!Number.isSafeInteger(total)||total<=0)errors.push('正式报价总额必须大于零');return{subtotal,discount,fee,tax,total,errors};};
  F.quoteGroups=()=>{
    const selected=F.state.looks.filter(l=>l.selected);if(!selected.length)return{groups:[],errors:['至少选中一个候选'],total:0};
    let groups=selected.map(l=>{const c=F.calcLook(l,F.state.quote.mode!=='combined');const j=F.state.imageJobs.find(j=>j.id===l.imageId);return{id:l.id,name:l.name,group:l.group,qty:l.qty,reason:l.reason,...c,modelImage:j?.status==='approved'?j.image:null,imageSource:j?.source||'original',imageKind:j?.kind||'original',imageLabel:j?.status==='approved'?(j.source==='sample'?'AI 模特示例 · 人工复核通过':j.source==='composition'?'商品电商拼版 · 人工复核通过':'外部生成图上传 · 人工复核通过'):'商品原图拼版'};});
    let errors=groups.flatMap(g=>g.errors.map(e=>g.name+'：'+e));
    selected.filter(l=>l.allocationsConfirmed===false).forEach(l=>errors.push(l.name+'：尺码配比为参考分配，请核对客户实际尺码并确认'));
    if(F.state.quote.mode==='combined'){
      const map=new Map();groups.forEach(g=>g.lines.forEach(l=>{const key=l.productId+'|'+l.sku;const existing=map.get(key);if(existing){existing.qty+=l.qty;existing.amount+=l.amount;}else map.set(key,{...l});}));const lines=[...map.values()];for(const l of lines){const sku=F.product(l.productId)?.sizes.find(s=>s.sku===l.sku);if(!sku||l.qty>sku.stock)errors.push(l.sku+'合并需求 '+l.qty+' 超过库存 '+(sku?.stock??0));}
      const totals=F.totals(lines.reduce((a,l)=>a+l.amount,0));errors.push(...totals.errors);if(F.state.brief.budget!==null&&totals.total>F.state.brief.budget)errors.push('合并采购超过客户总预算');const components=groups.map(({id,name,group,qty,reason,lines,modelImage,imageLabel,imageSource,imageKind})=>({id,name,group,qty,reason,lines,modelImage,imageLabel,imageSource,imageKind}));groups=[{id:'combined',name:'合并采购 · '+selected.length+' 组搭配',group:Math.max(...selected.map(l=>l.group)),qty:selected.reduce((a,l)=>a+l.qty,0),reason:selected.map(l=>l.name+' '+l.qty+'套').join('；'),lines,...totals,perSet:0,modelImage:null,imageLabel:'商品原图拼版',components}];
    }
    for(const g of groups){if(g.subtotal&&g.discount/g.subtotal>0.10000001&&!F.validException())errors.push('优惠超过 10%，需负责人确认当前方案例外');}
    if(!F.state.brief.confirmed)errors.push('客户需求尚未确认');if(!F.state.clients.some(c=>c.id===F.state.brief.clientId))errors.push('客户不存在');
    return{groups,errors:[...new Set(errors)],total:F.state.quote.mode==='combined'?groups[0]?.total:null};
  };
  F.signature=()=>JSON.stringify({brief:F.state.brief,looks:F.state.looks,q:{...F.state.quote,exception:null},p:F.state.priceVersion,s:F.state.stockVersion,v:F.state.productVersion});
  F.validException=()=>F.state.quote.exception?.signature===F.signature()&&Date.parse(F.state.quote.exception.expiresAt)>Date.now();
  F.approveException=reason=>{F.requireRole(['manager','admin']);if(!reason.trim())throw Error('请填写例外原因');const signature=F.signature();F.commit('负责人确认报价例外',s=>{s.quote.exception={signature,reason,at:new Date().toISOString(),expiresAt:new Date(Date.now()+86400000).toISOString(),role:s.role};});};
  F.createSnapshot=()=>{F.requireRole(['sales','manager','admin']);F.integer(F.state.quote.validDays,'有效期',1,30);const q=F.quoteGroups();if(q.errors.length)throw Error(q.errors.join('；'));const now=new Date();const snapshot={id:F.uid('quote'),createdAt:now.toISOString(),revision:F.state.revision,projectId:F.state.projectId,signature:F.signature(),mode:F.state.quote.mode,clientName:F.state.clients.find(c=>c.id===F.state.brief.clientId).name,title:F.state.brief.title,brief:F.clone(F.state.brief),quote:F.clone(F.state.quote),priceVersion:F.state.priceVersion,stockVersion:F.state.stockVersion,stockAsOf:F.state.stockAsOf,validUntil:new Date(+now+F.state.quote.validDays*86400000).toISOString(),brand:F.state.settings.brand,contact:F.state.settings.contact,template:F.clone(F.state.settings.template),prototype:true,groups:F.clone(q.groups).map(({errors,...g})=>g)};delete snapshot.quote.exception;F.commit('确认报价快照',s=>{s.snapshots.unshift(F.clone(snapshot));});return snapshot;};
  F.archiveProject=()=>{const fields=['brief','looks','quote','imageJobs'];F.commit('保存客户方案',s=>{const project={id:s.projectId,status:'active',updatedAt:new Date().toISOString(),...Object.fromEntries(fields.map(k=>[k,F.clone(s[k])]))};const at=s.projects.findIndex(p=>p.id===s.projectId);if(at<0)s.projects.unshift(project);else s.projects[at]=project;});};
  F.openProject=id=>{F.archiveProject();F.commit('切换客户方案',s=>{const p=s.projects.find(p=>p.id===id);if(!p)throw Error('方案不存在');s.projectId=id;for(const k of ['brief','looks','quote','imageJobs'])s[k]=F.clone(p[k]);});};
  F.newProject=(title,clientId,copy=false)=>{F.archiveProject();F.commit(copy?'复制方案':'新建方案',s=>{s.projectId=F.uid('project');s.brief={...(copy?s.brief:initial().brief),title,clientId,confirmed:false};if(!copy){s.brief.text='';s.brief.groupSlots=F.clone(s.settings.combinationTemplates||F.defaultTemplates());s.brief.templateVersion=s.settings.templateVersion||1;}s.looks=copy?s.looks.map(l=>({...l,id:F.uid('look'),imageId:null,imageMode:'original',allocationsConfirmed:false})):[];s.imageJobs=[];s.quote=copy?{...s.quote,exception:null}:{...initial().quote,fee:0};});F.archiveProject();};
  F.backup=()=>F.download(new Blob([JSON.stringify(F.state,null,2)],{type:'application/json'}),'织选-工作区备份.json');
  F.restore=raw=>{const data=JSON.parse(raw);if(data.schema!==2||!['products','clients','looks','projects','imageJobs','snapshots','batches','media','audit'].every(k=>Array.isArray(data[k]))||!data.brief||!data.quote||!data.settings?.template||!['sales','operator','manager','admin'].includes(data.role))throw Error('不是有效的织选 v2 备份');const ids=new Set();for(const p of data.products){if(!p.id||ids.has(p.id)||!categories.includes(p.category)||!Array.isArray(p.sizes)||!p.sizes.length||p.sizes.some(s=>!s.sku||!s.size||(s.stock!==null&&(!Number.isInteger(s.stock)||s.stock<0))||(s.price!==null&&(!Number.isSafeInteger(s.price)||s.price<0))))throw Error('备份商品或尺码数据结构无效');ids.add(p.id);}for(const l of data.looks){if(!Array.isArray(l.productIds)||l.productIds.some(id=>!ids.has(id))||!l.allocations||!Array.isArray(l.locks))throw Error('备份搭配数据结构无效');}const scan=v=>{if(typeof v==='string'&&(/^(javascript:|data:text\/html)/i.test(v)))throw Error('备份包含无效资源地址');if(v&&typeof v==='object')Object.values(v).forEach(scan);};scan(data);persist(data);F.state=data;};
  F.download=(blob,filename)=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);};
  if(typeof module!=='undefined')module.exports=F;
})(typeof window!=='undefined'?window:globalThis);
