-- FEAT-FASHION-001 / 数据库设计 v2.3：仅创建 T01～T16。
-- ID 由服务端生成；平台用户与字典编码只作逻辑引用，不建立跨模块外键。

create table fq_import_batch (
    id bigint not null,
    batch_no varchar(64) not null,
    template_code varchar(64) null,
    template_version varchar(32) null,
    import_type varchar(16) not null,
    operation_type varchar(16) not null default 'import',
    source_batch_id bigint null,
    source_code varchar(64) not null,
    warehouse_code varchar(64) null,
    file_name varchar(255) null,
    file_key varchar(512) null,
    file_hash char(64) null,
    mapping_snapshot json not null,
    scope_json json not null,
    scope_hash char(64) null,
    base_data_hash char(64) null,
    as_of datetime(3) not null,
    request_key varchar(128) not null,
    expected_count int not null default 0,
    actual_count int not null default 0,
    error_count int not null default 0,
    status varchar(24) not null default 'uploaded',
    validated_at datetime(3) null,
    published_at datetime(3) null,
    operator_note varchar(1000) null,
    error_message varchar(1000) null,
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_import_batch_no (batch_no),
    unique key uk_fq_import_request (request_key),
    key idx_fq_import_type_status_time (import_type, status, create_time),
    key idx_fq_import_source_time (source_code, create_time),
    constraint fk_fq_import_source foreign key (source_batch_id) references fq_import_batch (id) on delete restrict,
    constraint ck_fq_import_kind check (import_type in ('product','price','stock','image')),
    constraint ck_fq_import_operation check (operation_type in ('import','manual','verify','restore')),
    constraint ck_fq_import_status check (status in ('uploaded','validating','invalid','validated','publishing','success','failed','cancelled','conflict')),
    constraint ck_fq_import_counts check (expected_count >= 0 and actual_count >= 0 and error_count >= 0),
    constraint ck_fq_import_self check (source_batch_id is null or source_batch_id <> id),
    constraint ck_fq_import_row_version check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='导入批次主表';

create table fq_customer (
    id bigint not null,
    code varchar(64) not null,
    name varchar(80) not null,
    customer_type varchar(24) not null,
    contact_name varchar(80) null,
    contact_phone varchar(512) null,
    region varchar(120) null,
    salesperson_id bigint not null,
    collaborator_ids json not null default (json_array()),
    internal_note varchar(2000) null,
    status varchar(16) not null default 'active',
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_customer_code (code),
    key idx_fq_customer_owner_status (salesperson_id, status),
    key idx_fq_customer_name (name),
    constraint ck_fq_customer_type check (customer_type in ('group_purchase','wholesale')),
    constraint ck_fq_customer_status check (status in ('active','archived')),
    constraint ck_fq_customer_row_version check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='客户资料表';

create table fq_ai_agent (
    id bigint not null,
    agent_code varchar(64) not null,
    name varchar(100) not null,
    agent_type varchar(32) not null,
    description varchar(500) null,
    current_version_id bigint null,
    status varchar(16) not null default 'active',
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_ai_agent_code (agent_code),
    key idx_fq_ai_agent_type_status (agent_type, status),
    constraint ck_fq_ai_agent_type check (agent_type in ('orchestrator','requirement','selection','styling','quotation','image')),
    constraint ck_fq_ai_agent_status check (status in ('active','inactive')),
    constraint ck_fq_ai_agent_row_version check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='AI Agent主表';

create table fq_ai_agent_version (
    id bigint not null,
    agent_id bigint not null,
    version_no int not null,
    provider_code varchar(64) not null,
    model_name varchar(128) not null,
    system_instruction mediumtext not null,
    model_config_json json not null,
    tools_json json not null default (json_array()),
    handoffs_json json not null default (json_array()),
    input_schema_json json not null,
    output_schema_json json not null,
    guardrails_json json not null,
    max_steps int not null default 12,
    timeout_seconds int not null default 120,
    config_hash char(64) not null,
    status varchar(16) not null default 'draft',
    published_by bigint null,
    published_at datetime(3) null,
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_agent_version (agent_id, version_no),
    key idx_fq_agent_config_hash (config_hash),
    key idx_fq_agent_version_status (agent_id, status),
    constraint fk_fq_agent_version_agent foreign key (agent_id) references fq_ai_agent (id) on delete restrict,
    constraint ck_fq_agent_version_no check (version_no >= 1),
    constraint ck_fq_agent_max_steps check (max_steps between 1 and 50),
    constraint ck_fq_agent_timeout check (timeout_seconds between 1 and 600),
    constraint ck_fq_agent_version_status check (status in ('draft','published','retired')),
    constraint ck_fq_agent_published check ((status <> 'published') or (published_by is not null and published_at is not null)),
    constraint ck_fq_agent_version_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='AI Agent配置版本表';

create table fq_ai_conversation (
    id bigint not null,
    conversation_no varchar(64) not null,
    owner_user_id bigint not null,
    customer_id bigint null,
    quote_id bigint null,
    primary_agent_id bigint not null,
    title varchar(120) not null,
    channel varchar(16) not null default 'web',
    context_json json not null,
    summary_text text null,
    summary_up_to_seq int not null default 0,
    message_count int not null default 0,
    last_message_at datetime(3) null,
    status varchar(16) not null default 'active',
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_conversation_no (conversation_no),
    key idx_fq_conversation_owner (owner_user_id, status, last_message_at),
    key idx_fq_conversation_quote (quote_id, last_message_at),
    key idx_fq_conversation_customer (customer_id, last_message_at),
    constraint fk_fq_conversation_customer foreign key (customer_id) references fq_customer (id) on delete restrict,
    constraint fk_fq_conversation_agent foreign key (primary_agent_id) references fq_ai_agent (id) on delete restrict,
    constraint ck_fq_conversation_channel check (channel in ('web','api','voice')),
    constraint ck_fq_conversation_status check (status in ('active','closed','archived')),
    constraint ck_fq_conversation_counts check (summary_up_to_seq >= 0 and message_count >= 0),
    constraint ck_fq_conversation_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='AI对话主表';

create table fq_ai_message (
    id bigint not null,
    conversation_id bigint not null,
    seq_no int not null,
    parent_message_id bigint null,
    run_id bigint null,
    role varchar(16) not null,
    content_text mediumtext null,
    content_json json null,
    attachments_json json not null default (json_array()),
    provider_item_id varchar(128) null,
    visible_to_user tinyint not null default 1,
    content_hash char(64) not null,
    status varchar(16) not null default 'complete',
    error_message varchar(1000) null,
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_message_seq (conversation_id, seq_no),
    key idx_fq_message_time (conversation_id, create_time),
    key idx_fq_message_run (run_id),
    constraint fk_fq_message_conversation foreign key (conversation_id) references fq_ai_conversation (id) on delete restrict,
    constraint fk_fq_message_parent foreign key (parent_message_id) references fq_ai_message (id) on delete restrict,
    constraint ck_fq_message_seq check (seq_no >= 1),
    constraint ck_fq_message_role check (role in ('user','assistant','system_summary')),
    constraint ck_fq_message_content check (content_text is not null or content_json is not null),
    constraint ck_fq_message_visible check (visible_to_user in (0,1)),
    constraint ck_fq_message_status check (status in ('pending','streaming','complete','failed','superseded')),
    constraint ck_fq_message_self check (parent_message_id is null or parent_message_id <> id),
    constraint ck_fq_message_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='AI消息明细表';

create table fq_ai_run (
    id bigint not null,
    run_no varchar(64) not null,
    conversation_id bigint not null,
    agent_version_id bigint not null,
    parent_run_id bigint null,
    input_message_id bigint not null,
    trigger_type varchar(32) not null default 'chat',
    quote_id bigint null,
    quote_row_version bigint null,
    combo_id bigint null,
    request_key varchar(128) not null,
    agent_config_hash char(64) not null,
    deadline_at datetime(3) not null,
    budget_json json not null,
    context_snapshot_json json not null,
    output_type varchar(32) null,
    output_json json null,
    output_hash char(64) null,
    validation_json json null,
    apply_status varchar(16) not null default 'not_applied',
    apply_request_key varchar(128) null,
    apply_input_hash char(64) null,
    applied_by bigint null,
    applied_at datetime(3) null,
    applied_result_json json null,
    rejection_reason varchar(1000) null,
    trace_id varchar(128) null,
    status varchar(24) not null default 'queued',
    current_step_no int not null default 0,
    checkpoint_json json null,
    input_tokens bigint null,
    cached_tokens bigint null,
    output_tokens bigint null,
    reasoning_tokens bigint null,
    total_cost decimal(16,6) null,
    cost_currency char(3) null,
    run_attempt int not null default 0,
    execution_lease_id varchar(128) null,
    lease_owner varchar(128) null,
    fencing_token bigint not null default 0,
    next_retry_at datetime(3) null,
    lease_until datetime(3) null,
    last_event_seq bigint not null default 0,
    started_at datetime(3) null,
    finished_at datetime(3) null,
    error_code varchar(64) null,
    error_message varchar(1000) null,
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_run_no (run_no),
    unique key uk_fq_run_request (request_key),
    unique key uk_fq_run_apply_request (apply_request_key),
    key idx_fq_run_conversation (conversation_id, create_time),
    key idx_fq_run_status_retry (status, next_retry_at),
    key idx_fq_run_parent (parent_run_id),
    key idx_fq_run_quote (quote_id),
    constraint fk_fq_run_conversation foreign key (conversation_id) references fq_ai_conversation (id) on delete restrict,
    constraint fk_fq_run_agent_version foreign key (agent_version_id) references fq_ai_agent_version (id) on delete restrict,
    constraint fk_fq_run_parent foreign key (parent_run_id) references fq_ai_run (id) on delete restrict,
    constraint fk_fq_run_input_message foreign key (input_message_id) references fq_ai_message (id) on delete restrict,
    constraint ck_fq_run_parent_self check (parent_run_id is null or parent_run_id <> id),
    constraint ck_fq_run_trigger check (trigger_type in ('chat','parse_requirement','select_products','style','quote_explain','image_coordinate')),
    constraint ck_fq_run_apply check (apply_status in ('not_applied','applied','rejected','stale')),
    constraint ck_fq_run_status check (status in ('queued','running','waiting_approval','succeeded','failed','cancel_requested','cancelled','unknown')),
    constraint ck_fq_run_counters check (current_step_no >= 0 and run_attempt >= 0 and fencing_token >= 0 and last_event_seq >= 0),
    constraint ck_fq_run_tokens check ((input_tokens is null or input_tokens >= 0) and (cached_tokens is null or cached_tokens >= 0) and (output_tokens is null or output_tokens >= 0) and (reasoning_tokens is null or reasoning_tokens >= 0)),
    constraint ck_fq_run_cost check (total_cost is null or total_cost >= 0),
    constraint ck_fq_run_cost_currency check ((total_cost is null and cost_currency is null) or (total_cost is not null and cost_currency is not null)),
    constraint ck_fq_run_rejection check (apply_status not in ('rejected','stale') or rejection_reason is not null),
    constraint ck_fq_run_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='Agent运行表';

create table fq_product (
    id bigint not null,
    source_code varchar(64) not null,
    sku_code varchar(64) not null,
    style_code varchar(64) not null,
    name varchar(120) not null,
    category_code varchar(32) not null,
    color_code varchar(32) not null,
    color_name varchar(32) not null,
    size_code varchar(32) not null,
    size_system varchar(16) not null,
    unit varchar(16) not null,
    sale_price decimal(16,2) null,
    currency char(3) not null default 'CNY',
    tax_mode varchar(16) not null default 'included',
    price_as_of datetime(3) null,
    last_price_import_batch_id bigint null,
    brand varchar(80) null,
    material varchar(255) null,
    season varchar(32) not null default '四季',
    tags_json json not null default (json_array()),
    main_image_key varchar(512) null,
    images_json json not null default (json_array()),
    visual_version bigint not null default 1,
    last_ai_run_id bigint null,
    attributes_confirmed tinyint not null default 0,
    attributes_confirmed_by bigint null,
    attributes_confirmed_at datetime(3) null,
    jd_item_id varchar(64) null,
    jd_url varchar(2048) null,
    last_product_import_batch_id bigint null,
    status varchar(16) not null default 'draft',
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_product_sku (source_code, sku_code),
    unique key uk_fq_product_variant (source_code, style_code, color_code, size_system, size_code),
    key idx_fq_product_category_status (category_code, status),
    key idx_fq_product_style_color (source_code, style_code, color_code),
    key idx_fq_product_price_time (price_as_of, status),
    constraint fk_fq_product_price_batch foreign key (last_price_import_batch_id) references fq_import_batch (id) on delete restrict,
    constraint fk_fq_product_ai_run foreign key (last_ai_run_id) references fq_ai_run (id) on delete restrict,
    constraint fk_fq_product_import_batch foreign key (last_product_import_batch_id) references fq_import_batch (id) on delete restrict,
    constraint ck_fq_product_price check (sale_price is null or sale_price >= 0),
    constraint ck_fq_product_price_source check ((sale_price is null and price_as_of is null and last_price_import_batch_id is null) or (sale_price is not null and price_as_of is not null and last_price_import_batch_id is not null)),
    constraint ck_fq_product_currency check (currency = 'CNY'),
    constraint ck_fq_product_tax check (tax_mode in ('included','excluded')),
    constraint ck_fq_product_visual check (visual_version >= 1),
    constraint ck_fq_product_confirmed check (attributes_confirmed in (0,1)),
    constraint ck_fq_product_status check (status in ('draft','active','inactive')),
    constraint ck_fq_product_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='商品资料表';

create table fq_stock (
    id bigint not null,
    product_id bigint not null,
    warehouse_code varchar(64) not null,
    available_qty int not null,
    as_of datetime(3) not null,
    confirmation_type varchar(16) not null default 'import',
    verified_by bigint null,
    evidence_note varchar(1000) null,
    last_import_batch_id bigint not null,
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_stock_product_warehouse (product_id, warehouse_code),
    key idx_fq_stock_warehouse_time (warehouse_code, as_of),
    constraint fk_fq_stock_product foreign key (product_id) references fq_product (id) on delete restrict,
    constraint fk_fq_stock_batch foreign key (last_import_batch_id) references fq_import_batch (id) on delete restrict,
    constraint ck_fq_stock_qty check (available_qty >= 0),
    constraint ck_fq_stock_type check (confirmation_type in ('import','manual_verify','restore')),
    constraint ck_fq_stock_manual check (confirmation_type <> 'manual_verify' or (verified_by is not null and evidence_note is not null)),
    constraint ck_fq_stock_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='商品库存表';

create table fq_quote (
    id bigint not null,
    quote_no varchar(64) not null,
    version_no int not null default 1,
    source_quote_id bigint null,
    customer_id bigint not null,
    customer_name varchar(80) not null,
    title varchar(100) not null,
    salesperson_id bigint not null,
    requirement_text text null,
    requirement_json json not null,
    requirement_confirmed tinyint not null default 0,
    requested_qty int not null default 100,
    budget decimal(16,2) null,
    budget_basis varchar(16) not null default 'total',
    quote_mode varchar(16) not null default 'alternatives',
    progressive tinyint not null default 1,
    combo_template_json json not null,
    warehouse_code varchar(64) not null,
    currency char(3) not null default 'CNY',
    tax_mode varchar(16) not null default 'included',
    tax_rate decimal(5,2) null,
    fee_taxable tinyint not null default 1,
    discount_type varchar(16) not null default 'percent',
    discount_rate decimal(5,2) not null default 5.00,
    fixed_discount decimal(16,2) not null default 0,
    freight decimal(16,2) not null default 0,
    subtotal decimal(16,2) null,
    discount_amount decimal(16,2) null,
    tax_amount decimal(16,2) null,
    total_amount decimal(16,2) null,
    approval_json json null,
    valid_days int not null default 7,
    valid_until datetime(3) null,
    public_note varchar(2000) null,
    presentation_json json not null,
    content_hash char(64) null,
    confirmed_by bigint null,
    confirmed_at datetime(3) null,
    status varchar(16) not null default 'draft',
    void_reason varchar(1000) null,
    is_demo tinyint not null default 0,
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_quote_version (quote_no, version_no),
    key idx_fq_quote_customer_time (customer_id, create_time),
    key idx_fq_quote_owner_status (salesperson_id, status),
    key idx_fq_quote_valid_until (valid_until),
    constraint fk_fq_quote_source foreign key (source_quote_id) references fq_quote (id) on delete restrict,
    constraint fk_fq_quote_customer foreign key (customer_id) references fq_customer (id) on delete restrict,
    constraint ck_fq_quote_version check (version_no >= 1),
    constraint ck_fq_quote_request_qty check (requested_qty between 1 and 100000),
    constraint ck_fq_quote_budget check (budget is null or budget > 0),
    constraint ck_fq_quote_budget_basis check (budget_basis in ('total','per_set')),
    constraint ck_fq_quote_mode check (quote_mode in ('alternatives','combined')),
    constraint ck_fq_quote_flags check (requirement_confirmed in (0,1) and progressive in (0,1) and fee_taxable in (0,1) and is_demo in (0,1)),
    constraint ck_fq_quote_currency check (currency = 'CNY'),
    constraint ck_fq_quote_tax check ((tax_mode = 'included' and tax_rate is null) or (tax_mode = 'excluded' and tax_rate between 0 and 100)),
    constraint ck_fq_quote_discount check ((discount_type = 'percent' and discount_rate between 0 and 100 and fixed_discount = 0) or (discount_type = 'fixed' and discount_rate = 0 and fixed_discount >= 0)),
    constraint ck_fq_quote_freight check (freight >= 0),
    constraint ck_fq_quote_amounts check ((subtotal is null or subtotal >= 0) and (discount_amount is null or discount_amount >= 0) and (tax_amount is null or tax_amount >= 0) and (total_amount is null or total_amount >= 0)),
    constraint ck_fq_quote_valid_days check (valid_days between 1 and 30),
    constraint ck_fq_quote_status check (status in ('draft','confirmed','void','closed')),
    constraint ck_fq_quote_void check (status <> 'void' or void_reason is not null),
    constraint ck_fq_quote_self check (source_quote_id is null or source_quote_id <> id),
    constraint ck_fq_quote_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='报价方案主表';

create table fq_quote_combo (
    id bigint not null,
    quote_id bigint not null,
    combo_no varchar(32) not null,
    name varchar(100) not null,
    category_count int not null,
    set_qty int not null default 100,
    selected tinyint not null default 1,
    sort_no int not null default 0,
    reason varchar(2000) null,
    lock_json json not null default (json_array()),
    visual_hash char(64) not null,
    allocation_confirmed tinyint not null default 0,
    allocation_confirmed_by bigint null,
    allocation_confirmed_at datetime(3) null,
    selected_image_id bigint null,
    selected_image_no int null,
    subtotal decimal(16,2) null,
    discount_amount decimal(16,2) null,
    freight decimal(16,2) null,
    tax_amount decimal(16,2) null,
    total_amount decimal(16,2) null,
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_combo_no (quote_id, combo_no),
    key idx_fq_combo_selected_sort (quote_id, selected, sort_no),
    constraint fk_fq_combo_quote foreign key (quote_id) references fq_quote (id) on delete restrict,
    constraint ck_fq_combo_categories check (category_count between 1 and 4),
    constraint ck_fq_combo_qty check (set_qty between 1 and 100000),
    constraint ck_fq_combo_flags check (selected in (0,1) and allocation_confirmed in (0,1)),
    constraint ck_fq_combo_image_no check (selected_image_no is null or selected_image_no between 1 and 4),
    constraint ck_fq_combo_amounts check ((subtotal is null or subtotal >= 0) and (discount_amount is null or discount_amount >= 0) and (freight is null or freight >= 0) and (tax_amount is null or tax_amount >= 0) and (total_amount is null or total_amount >= 0)),
    constraint ck_fq_combo_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='报价方案组合表';

create table fq_quote_detail (
    id bigint not null,
    combo_id bigint not null,
    ai_run_id bigint null,
    line_no int not null,
    slot_code varchar(32) not null,
    product_id bigint not null,
    source_code varchar(64) not null,
    sku_code varchar(64) not null,
    style_code varchar(64) not null,
    product_name varchar(120) not null,
    category_code varchar(32) not null,
    color_code varchar(32) not null,
    color_name varchar(32) not null,
    size_code varchar(32) not null,
    size_system varchar(16) not null,
    unit varchar(16) not null,
    qty int not null,
    source_price decimal(16,2) null,
    quote_price decimal(16,2) null,
    amount decimal(16,2) null,
    price_batch_id bigint null,
    stock_batch_id bigint null,
    stock_qty int null,
    stock_as_of datetime(3) null,
    image_key varchar(512) null,
    image_hash char(64) null,
    image_version bigint null,
    image_source_json json null,
    remark varchar(500) null,
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_detail_line (combo_id, line_no),
    unique key uk_fq_detail_product (combo_id, product_id),
    key idx_fq_detail_product (product_id),
    key idx_fq_detail_price_batch (price_batch_id),
    key idx_fq_detail_stock_batch (stock_batch_id),
    constraint fk_fq_detail_combo foreign key (combo_id) references fq_quote_combo (id) on delete restrict,
    constraint fk_fq_detail_run foreign key (ai_run_id) references fq_ai_run (id) on delete restrict,
    constraint fk_fq_detail_product foreign key (product_id) references fq_product (id) on delete restrict,
    constraint fk_fq_detail_price_batch foreign key (price_batch_id) references fq_import_batch (id) on delete restrict,
    constraint fk_fq_detail_stock_batch foreign key (stock_batch_id) references fq_import_batch (id) on delete restrict,
    constraint ck_fq_detail_line check (line_no >= 1),
    constraint ck_fq_detail_qty check (qty > 0),
    constraint ck_fq_detail_prices check ((source_price is null or source_price >= 0) and (quote_price is null or quote_price >= 0) and (amount is null or amount >= 0)),
    constraint ck_fq_detail_stock check (stock_qty is null or stock_qty >= 0),
    constraint ck_fq_detail_image_version check (image_version is null or image_version >= 1),
    constraint ck_fq_detail_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='报价方案商品明细表';

create table fq_quote_image (
    id bigint not null,
    combo_id bigint not null,
    ai_run_id bigint null,
    source_image_id bigint null,
    image_type varchar(16) not null,
    source_mode varchar(16) not null,
    input_hash char(64) not null,
    inputs_json json not null,
    parameters_json json not null,
    requested_count int not null default 2,
    results_json json not null default (json_array()),
    provider_code varchar(64) null,
    provider_task_id varchar(128) null,
    request_key varchar(128) not null,
    status varchar(24) not null default 'queued',
    stale tinyint not null default 0,
    retry_count int not null default 0,
    next_retry_at datetime(3) null,
    lease_until datetime(3) null,
    estimated_cost decimal(16,6) null,
    actual_cost decimal(16,6) null,
    cost_currency char(3) null,
    billing_status varchar(16) not null default 'not_applicable',
    billing_events_json json not null default (json_array()),
    error_message varchar(1000) null,
    finished_at datetime(3) null,
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_image_request (request_key),
    unique key uk_fq_image_provider_task (provider_code, provider_task_id),
    key idx_fq_image_combo_time (combo_id, create_time),
    key idx_fq_image_run (ai_run_id),
    key idx_fq_image_status_retry (status, next_retry_at),
    constraint fk_fq_image_combo foreign key (combo_id) references fq_quote_combo (id) on delete restrict,
    constraint fk_fq_image_run foreign key (ai_run_id) references fq_ai_run (id) on delete restrict,
    constraint fk_fq_image_source foreign key (source_image_id) references fq_quote_image (id) on delete restrict,
    constraint ck_fq_image_type check (image_type in ('model','styling','ecommerce','composition')),
    constraint ck_fq_image_source_mode check (source_mode in ('sample','upload','provider','composition','reuse')),
    constraint ck_fq_image_count check (requested_count between 1 and 4),
    constraint ck_fq_image_status check (status in ('queued','running','success','partial','failed','cancel_requested','cancelled','unknown')),
    constraint ck_fq_image_counters check (stale in (0,1) and retry_count between 0 and 2),
    constraint ck_fq_image_cost check ((estimated_cost is null or estimated_cost >= 0) and (actual_cost is null or actual_cost >= 0)),
    constraint ck_fq_image_billing check (billing_status in ('not_applicable','reserved','unknown','settled')),
    constraint ck_fq_image_self check (source_image_id is null or source_image_id <> id),
    constraint ck_fq_image_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='方案图片记录表';

create table fq_quote_file (
    id bigint not null,
    quote_id bigint not null,
    file_type varchar(16) not null,
    purpose varchar(24) not null default 'customer',
    quote_hash char(64) not null,
    renderer_version varchar(64) not null,
    request_key varchar(128) not null,
    status varchar(16) not null default 'queued',
    files_json json not null default (json_array()),
    retry_count int not null default 0,
    next_retry_at datetime(3) null,
    lease_until datetime(3) null,
    error_message varchar(1000) null,
    last_download_at datetime(3) null,
    download_count int not null default 0,
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_file_request (request_key),
    key idx_fq_file_quote_time (quote_id, create_time),
    key idx_fq_file_status_retry (status, next_retry_at),
    constraint fk_fq_file_quote foreign key (quote_id) references fq_quote (id) on delete restrict,
    constraint ck_fq_file_type check (file_type in ('pptx','csv','image_zip','jpg')),
    constraint ck_fq_file_purpose check (purpose in ('customer','internal_expired')),
    constraint ck_fq_file_status check (status in ('queued','running','success','failed')),
    constraint ck_fq_file_counts check (retry_count between 0 and 2 and download_count >= 0),
    constraint ck_fq_file_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='方案导出文件表';

create table fq_import_detail (
    id bigint not null,
    batch_id bigint not null,
    detail_no int not null,
    source_row_no int null,
    row_type varchar(16) not null default 'input',
    product_id bigint null,
    business_key varchar(255) not null,
    raw_data json null,
    normalized_data json null,
    before_data json null,
    after_data json null,
    status varchar(16) not null default 'pending',
    error_json json not null default (json_array()),
    change_type varchar(16) null,
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_import_detail_no (batch_id, detail_no),
    key idx_fq_import_detail_status (batch_id, status),
    key idx_fq_import_detail_key (batch_id, business_key),
    key idx_fq_import_detail_product (product_id, create_time),
    constraint fk_fq_import_detail_batch foreign key (batch_id) references fq_import_batch (id) on delete restrict,
    constraint fk_fq_import_detail_product foreign key (product_id) references fq_product (id) on delete restrict,
    constraint ck_fq_import_detail_no check (detail_no >= 1),
    constraint ck_fq_import_source_row check (source_row_no is null or source_row_no >= 1),
    constraint ck_fq_import_row_type check (row_type in ('input','missing')),
    constraint ck_fq_import_detail_status check (status in ('pending','valid','invalid','applied')),
    constraint ck_fq_import_change check (change_type is null or change_type in ('added','changed','unchanged')),
    constraint ck_fq_import_detail_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='导入行明细表';

create table fq_ai_run_step (
    id bigint not null,
    run_id bigint not null,
    step_no int not null,
    run_attempt int not null,
    execution_lease_id varchar(128) not null,
    fencing_token bigint not null,
    deadline_at datetime(3) not null,
    parent_step_id bigint null,
    step_type varchar(24) not null,
    name varchar(100) not null,
    call_key varchar(128) not null,
    attempt_no int not null default 1,
    tool_call_id varchar(128) null,
    tool_name varchar(100) null,
    tool_version varchar(64) null,
    target_agent_id bigint null,
    child_run_id bigint null,
    provider_code varchar(64) null,
    external_request_key varchar(128) null,
    provider_response_id varchar(128) null,
    last_client_event_id varchar(128) null,
    event_version bigint not null default 0,
    input_json json null,
    input_hash char(64) not null,
    output_json json null,
    status varchar(24) not null default 'queued',
    approval_required tinyint not null default 0,
    approval_status varchar(16) not null default 'not_required',
    approval_input_hash char(64) null,
    approval_requested_at datetime(3) null,
    approval_expires_at datetime(3) null,
    approved_by bigint null,
    approved_at datetime(3) null,
    approval_reject_reason varchar(1000) null,
    checkpoint_json json null,
    input_tokens bigint null,
    output_tokens bigint null,
    cost decimal(16,6) null,
    cost_currency char(3) null,
    started_at datetime(3) null,
    finished_at datetime(3) null,
    error_code varchar(64) null,
    error_message varchar(1000) null,
    create_by bigint not null,
    create_time datetime(3) not null,
    update_by bigint not null,
    update_time datetime(3) not null,
    row_version bigint not null default 1,
    primary key (id),
    unique key uk_fq_step_no (run_id, step_no),
    unique key uk_fq_step_attempt (run_id, call_key, attempt_no),
    unique key uk_fq_step_external_request (provider_code, external_request_key),
    unique key uk_fq_step_provider_response (provider_code, provider_response_id),
    key idx_fq_step_run_status (run_id, status),
    key idx_fq_step_tool_call (tool_call_id),
    key idx_fq_step_child_run (child_run_id),
    key idx_fq_step_tool_time (tool_name, create_time),
    constraint fk_fq_step_run foreign key (run_id) references fq_ai_run (id) on delete restrict,
    constraint fk_fq_step_parent foreign key (parent_step_id) references fq_ai_run_step (id) on delete restrict,
    constraint fk_fq_step_target_agent foreign key (target_agent_id) references fq_ai_agent (id) on delete restrict,
    constraint fk_fq_step_child_run foreign key (child_run_id) references fq_ai_run (id) on delete restrict,
    constraint ck_fq_step_numbers check (step_no >= 1 and run_attempt >= 0 and fencing_token >= 0 and attempt_no between 1 and 3 and event_version >= 0),
    constraint ck_fq_step_type check (step_type in ('model','tool','handoff','guardrail','human_approval','checkpoint')),
    constraint ck_fq_step_status check (status in ('queued','running','waiting_approval','succeeded','failed','skipped','cancelled','unknown')),
    constraint ck_fq_step_self check (parent_step_id is null or parent_step_id <> id),
    constraint ck_fq_step_external check ((provider_code is null and external_request_key is null and provider_response_id is null) or (provider_code is not null and external_request_key is not null)),
    constraint ck_fq_step_approval check ((approval_required = 0 and approval_status = 'not_required' and approval_input_hash is null and approval_requested_at is null and approval_expires_at is null and approved_by is null and approved_at is null and approval_reject_reason is null) or (approval_required = 1 and approval_status in ('pending','approved','rejected','expired') and approval_input_hash is not null and approval_requested_at is not null and approval_expires_at is not null)),
    constraint ck_fq_step_approved check (approval_status <> 'approved' or (approved_by is not null and approved_at is not null)),
    constraint ck_fq_step_rejected check (approval_status not in ('rejected','expired') or approval_reject_reason is not null),
    constraint ck_fq_step_usage check ((input_tokens is null or input_tokens >= 0) and (output_tokens is null or output_tokens >= 0) and (cost is null or cost >= 0)),
    constraint ck_fq_step_cost_currency check ((cost is null and cost_currency is null) or (cost is not null and cost_currency is not null)),
    constraint ck_fq_step_row check (row_version >= 1)
) engine=innodb default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='Agent运行步骤表';

-- 循环与跨模块回指只在所有参与表存在后增加。
alter table fq_ai_agent
    add constraint fk_fq_agent_current_version foreign key (current_version_id) references fq_ai_agent_version (id) on delete restrict;
alter table fq_ai_conversation
    add constraint fk_fq_conversation_quote foreign key (quote_id) references fq_quote (id) on delete restrict;
alter table fq_ai_message
    add constraint fk_fq_message_run foreign key (run_id) references fq_ai_run (id) on delete restrict;
alter table fq_ai_run
    add constraint fk_fq_run_quote foreign key (quote_id) references fq_quote (id) on delete restrict,
    add constraint fk_fq_run_combo foreign key (combo_id) references fq_quote_combo (id) on delete restrict;
alter table fq_quote_combo
    add constraint fk_fq_combo_image foreign key (selected_image_id) references fq_quote_image (id) on delete restrict;
